import {defineCopy, type Locale} from '../localization-contract';
import type {DemoRecord, Run} from './engine';

export const businessCopy=defineCopy('automation-business',{
 pl:{
  financeTitle:'Płatności z wyciągu bankowego ↔ faktury z ERP',financeIntro:'Sprawdź, które faktury mają zgodną płatność, a które wymagają wyjaśnienia. Wynik to raport, bez zmiany faktur i płatności.',
  financeChecks:'Numer faktury · kwota w PLN · duplikaty',financeContract:'Łączymy po numerze faktury i porównujemy kwoty w PLN co do grosza. Przykład obejmuje faktury z ERP; płatności bez faktury nie są tu wyszukiwane. Powtórzony numer wymaga decyzji człowieka.',
  financeHeaders:['Numer faktury','Kontrahent (demo)','Kwota faktury','Kwota płatności','Waluta','Data płatności','Status dopasowania'],referenceHeaders:['Numer faktury w tytule płatności','Kwota płatności','Waluta','Data płatności'],
  financeManual:['Otwórz listę faktur z ERP i wyciąg bankowy','Znajdź płatność po numerze faktury','Porównaj kwoty i sprawdź powtórzone numery','Zapisz zgodne płatności i rozbieżności w raporcie'],
  financeStatuses:['Dopasowana płatność','Brak płatności w wyciągu','Kwota płatności różni się od faktury','Powtórzony numer faktury — sprawdź ręcznie'],pending:'Uruchom porównanie',
  servicesTitle:'Zapytanie klienta → zadanie z opiekunem w CRM',servicesIntro:'Przykład formularza z prośbą o ofertę serwisową. Kompletna, zatwierdzona sprawa tworzy zadanie dla opiekuna; braki i duplikaty trafiają do sprawdzenia. Nie jest to obieg faktur ani odczyt treści dokumentów.',servicesChecks:'Firma · opis sprawy · akceptacja · opiekun',
  servicesHeaders:['Zapytanie','Firma (demo)','Rodzaj sprawy','Akceptacja','Opiekun'],enquiry:'Prośba o ofertę serwisową',owner:'Opiekun serwisu',missing:'Brak — do sprawdzenia',yes:'Tak',no:'Nie',
  logisticsTitle:'Kurier: doręczono → ERP: zamówienie dostarczone',logisticsIntro:'Zdarzenie kuriera aktualizuje status zamówienia w symulowanym ERP. Brak statusu, powtórzenie lub rozbieżność zatrzymuje aktualizację. Ten przykład nie wysyła e-maila i nie aktualizuje CRM.',logisticsChecks:'Zdarzenie · waga przesyłki · status doręczenia · duplikaty',
  logisticsHeaders:['Zamówienie','Zdarzenie kuriera','Status kuriera','Waga / oczekiwana (kg)','ERP przed → po przyjęciu'],delivered:'Doręczono',deliveryException:'Problem z doręczeniem',dispatched:'Wysłane',orderDelivered:'Dostarczone',held:'Bez zmiany — wymaga sprawdzenia',
  financeResult:'{ok} faktur ma zgodną płatność. {review} wymaga wyjaśnienia. Powstał raport tylko do odczytu.',servicesResult:'{ok} zapytań utworzyło zadania dla opiekuna w symulowanym CRM. {review} zatrzymano do sprawdzenia.',logisticsResult:'{ok} zamówień zmieniło status w symulowanym ERP z „wysłane” na „dostarczone”. {review} pozostawiono bez zmiany do sprawdzenia.',orderResult:'{ok} poprawnych zamówień przekazano dalej w symulacji. {review} zatrzymano do sprawdzenia.',genericResult:'{ok} rekordów obsłużono w symulacji. {review} wymaga decyzji człowieka.',comparisonResult:'{ok} zgodnych par danych. {review} pozycji wymaga sprawdzenia w raporcie tylko do odczytu.',
  details:'Pokaż wyjątki i szczegóły wyniku',discuss:'Opisz podobny proces',unknown:'Nie wiem — ustalimy to razem.',keyHint:'Np. numer faktury, numer zamówienia, ID klienta. Możesz zostawić puste.',sourceHint:'Np. wyciąg bankowy CSV. Możesz zostawić puste.',manualComparison:'Ręcznie sprawdzam, które wpisy w dwóch źródłach pasują do siebie.',manualFinance:'Ręcznie sprawdzam, które płatności pasują do faktur.',briefResult:'Lista dopasowanych pozycji i wyjątków do sprawdzenia. Tylko raport, bez zmiany danych. Miejsce wyniku: ',keyNote:'Możliwe dopasowanie po: ',outlineCta:'Opisz swój przypadek',outlineNote:'Ten wariant wymaga ustalenia danych i reguł. Opisz swój przypadek — na tej podstawie możemy wybrać pierwszy zakres.'
 },
 en:{
  financeTitle:'Bank statement payments ↔ ERP invoices',financeIntro:'See which invoices have a matching payment and which need investigation. The output is a report; invoices and payments stay unchanged.',financeChecks:'Invoice number · amount in PLN · duplicates',financeContract:'Match by invoice number and compare PLN amounts to the penny. This example starts with ERP invoices; it does not find payments with no invoice. Repeated invoice numbers require a human decision.',financeHeaders:['Invoice number','Customer (demo)','Invoice amount','Payment amount','Currency','Payment date','Match status'],referenceHeaders:['Invoice number in payment reference','Payment amount','Currency','Payment date'],financeManual:['Open the ERP invoice list and bank statement','Find the payment by invoice number','Compare amounts and check repeated numbers','Record matches and discrepancies in a report'],financeStatuses:['Payment matched','No payment in statement','Payment amount differs from invoice','Repeated invoice number — review manually'],pending:'Run comparison',
  servicesTitle:'Customer enquiry → CRM task with an owner',servicesIntro:'A form requesting a service quote. A complete, approved enquiry creates a task for its owner; missing details and duplicates go to review. This is not invoice processing or document text extraction.',servicesChecks:'Company · request · approval · owner',servicesHeaders:['Enquiry','Company (demo)','Request type','Approval','Owner'],enquiry:'Request for a service quote',owner:'Service coordinator',missing:'Missing — review needed',yes:'Yes',no:'No',
  logisticsTitle:'Carrier: delivered → ERP: order delivered',logisticsIntro:'A carrier event updates the order in a simulated ERP. A missing status, repeated event or discrepancy stops the update. This example does not send email or update CRM.',logisticsChecks:'Event · shipment weight · delivery status · duplicates',logisticsHeaders:['Order','Carrier event','Carrier status','Weight / expected (kg)','ERP before → after acceptance'],delivered:'Delivered',deliveryException:'Delivery exception',dispatched:'Dispatched',orderDelivered:'Delivered',held:'Unchanged — review needed',
  financeResult:'{ok} invoices have matching payments. {review} need investigation. A read-only report was created.',servicesResult:'{ok} enquiries created tasks for their owner in the simulated CRM. {review} were held for review.',logisticsResult:'{ok} orders changed from dispatched to delivered in the simulated ERP. {review} stayed unchanged for review.',orderResult:'{ok} valid orders were passed on in the simulation. {review} were held for review.',genericResult:'{ok} records were processed in the simulation. {review} need a human decision.',comparisonResult:'{ok} matching pairs. {review} entries need review in the read-only report.',
  details:'Show exceptions and result details',discuss:'Describe a similar process',unknown:'I don’t know — we can work this out together.',keyHint:'For example, invoice number, order number or customer ID. You can leave this blank.',sourceHint:'For example, a bank statement CSV. You can leave this blank.',manualComparison:'I manually check which entries in two sources belong together.',manualFinance:'I manually check which payments match the invoices.',briefResult:'A list of matches and exceptions to review. Report only, with no data changes. Result destination: ',keyNote:'Possible matching field: ',outlineCta:'Describe your case',outlineNote:'This variant needs agreed data and rules. Describe your case so we can identify a first scope.'
 }
});
export function businessSummary(locale:Locale,industry:string,comparison:boolean,run:Run){
 const c=businessCopy[locale];const template=comparison?(industry==='finance'?c.financeResult:c.comparisonResult):industry==='services'?c.servicesResult:industry==='logistics'?c.logisticsResult:industry==='ecommerce'||industry==='manufacturing'?c.orderResult:c.genericResult;
 return template.replace('{ok}',String(run.accepted.length)).replace('{review}',String(run.reviewCount));
}
export function financeStatus(locale:Locale,row:DemoRecord,run:Run|null){
 const c=businessCopy[locale];if(!run)return c.pending;const rule=run.findings.find(f=>f.record===row.id)?.rule;return c.financeStatuses[rule==='comparison-missing'?1:rule==='comparison-mismatch'?2:rule==='comparison-duplicate'?3:0];
}
export function businessRecord(row:DemoRecord,industry:string){return industry==='finance'?row.reference:industry==='services'?`REQ-${row.id.slice(5)}`:industry==='logistics'?`ORD-${row.id.slice(5)}`:row.id;}
export function businessAction(locale:Locale,industry:string,row:DemoRecord,destination:number,fallback:string){const c=businessCopy[locale];return industry==='services'?(destination===2?`${businessRecord(row,industry)} → CRM · ${c.enquiry}`:`${businessRecord(row,industry)} → ${c.owner}`):industry==='logistics'?`${businessRecord(row,industry)} · ${row.reference} · ${c.delivered} → ERP: ${c.dispatched} → ${c.orderDelivered}`:fallback;}
