import {defineCopy} from '../localization-contract';
export const automationCopy=defineCopy('automation-ui',{
  "pl": {
    "title": "Wypróbuj automatyzację na przykładzie",
    "intro": "Wybierz przykład i zobacz, które rekordy przechodzą automatycznie, a które wymagają decyzji człowieka.",
    "demo": "Przykład na danych syntetycznych",
    "boundary": "Symulacja działa w przeglądarce. Nie łączy się z ERP, nie wysyła wiadomości i nie wykonuje płatności.",
    "industry": "Branża",
    "pattern": "Co chcesz zautomatyzować?",
    "before": "Przed",
    "after": "Po automatyzacji",
    "human": "Pracownik zajmuje się wyjątkami i decyzjami.",
    "humanNote": "Rekordy zgodne z regułami przechodzą dalej. Pozostałe trafiają do sprawdzenia.",
    "manual": [
      "E-mail",
      "Pracownik",
      "Excel",
      "Pracownik",
      "System",
      "E-mail",
      "Dział operacyjny"
    ],
    "stages": [
      "Wejście",
      "Walidacja",
      "Reguły biznesowe",
      "Rozdzielenie ścieżek",
      "Wyniki obu gałęzi",
      "Historia / wynik"
    ],
    "run": "Uruchom przykład",
    "running": "Przetwarzanie…",
    "reset": "Wyczyść wynik",
    "complete": "Przebieg zakończony",
    "ready": "Gotowy do uruchomienia",
    "step": "Etap",
    "normal": "Automatycznie",
    "review": "Do sprawdzenia",
    "total": "Rekordy",
    "queue": "Kolejka wyjątków",
    "audit": "Historia operacji",
    "input": "Pokaż dane wejściowe i reguły",
    "record": "Rekord",
    "reference": "Referencja",
    "quantity": "Wartość",
    "expected": "Oczekiwana wartość",
    "valid": "Dane poprawne",
    "yes": "Tak",
    "no": "Nie",
    "rule": "Reguła",
    "reason": "Powód",
    "next": "Następna czynność",
    "empty": "Uruchom przykład, aby zobaczyć wynik obliczony dla tych danych.",
    "normalNote": "Tylko rekordy bez naruszeń reguł trafiają do symulowanego systemu docelowego.",
    "target": "Wynik w systemie docelowym",
    "action": "Wykonana czynność",
    "auditNote": "Stały zegar demonstracyjny. Te same dane i reguły dają ten sam wynik.",
    "events": [
      "Dane odebrane",
      "Walidacja wykonana",
      "Reguły sprawdzone",
      "Akcja zapisana",
      "Wyjątek utworzony",
      "Przekazano do weryfikacji",
      "Przebieg zakończony",
      "Naruszenie reguły — akcja wstrzymana"
    ],
    "share": "Link do tego przykładu",
    "proof": "Zobacz testy i raport",
    "badQuery": "Nieznany parametr przykładu. Pokazano domyślny, bezpieczny scenariusz.",
    "builder": "Jak wygląda Twój proces?",
    "builderIntro": "Wybierz źródło danych, wykonywaną czynność i system docelowy. Na tej podstawie przygotujesz szkic zadania do omówienia.",
    "source": "Skąd przychodzą dane?",
    "manualQuestion": "Co dziś robi człowiek?",
    "destination": "Gdzie powinien trafić wynik?",
    "sources": [
      "E-mail",
      "Excel / CSV",
      "Formularz",
      "CRM",
      "ERP",
      "Sklep internetowy",
      "API",
      "Inne"
    ],
    "tasks": [
      "Przepisuje dane",
      "Sprawdza",
      "Porównuje",
      "Zatwierdza",
      "Aktualizuje status",
      "Wysyła powiadomienie",
      "Przygotowuje raport",
      "Obsługuje wyjątki"
    ],
    "destinations": [
      "ERP",
      "CRM",
      "Magazyn / WMS",
      "Księgowość",
      "Panel operacyjny",
      "E-mail",
      "API",
      "Inny system"
    ],
    "builderSteps": [
      "Walidacja",
      "Mapowanie",
      "Kolejka wyjątków",
      "Powiadomienie"
    ],
    "firstScope": "Przykładowy pierwszy zakres",
    "scopeTemplates": [
      "Import jednego typu danych z {0} do {1}, walidacja i lista wyjątków.",
      "Kontrola jednego zestawu danych z {0}, reguły poprawności i wynik w {1}.",
      "Porównanie jednego zestawu danych z {0}, raport różnic i wynik w {1}.",
      "Jeden obieg decyzji od {0} do {1}, z akceptacją człowieka i historią zmian.",
      "Synchronizacja jednego statusu z {0} do {1}, z kontrolą rozbieżności.",
      "Jedno powiadomienie z {0} do {1}, z kontrolą odbiorcy i historią wysyłki.",
      "Jeden powtarzalny raport z {0} do {1}, z walidacją źródła.",
      "Jedna kolejka wyjątków z {0} do {1}, z właścicielem i historią decyzji."
    ],
    "useBrief": "Przenieś szkic do wiadomości",
    "systems": "Integracja z Twoimi systemami",
    "qualifier": "Konkretna możliwość integracji zależy od dostępnego API, eksportu/importu, uprawnień i środowiska testowego.",
    "systemsNote": "Przykłady środowisk i źródeł — nie lista certyfikatów ani oficjalnych partnerstw.",
    "ladder": "Od jednej czynności do całego procesu",
    "levels": [
      "Pojedyncza integracja",
      "Automatyzacja procesu",
      "Kompletny moduł lub proces"
    ],
    "levelFlows": [
      [
        "Excel",
        "Walidacja",
        "ERP"
      ],
      [
        "Formularz",
        "CRM",
        "ERP",
        "Powiadomienie"
      ],
      [
        "E-commerce",
        "ERP",
        "WMS",
        "Transport",
        "Faktura",
        "Raport"
      ]
    ],
    "ladderNote": "Możemy zacząć od jednego importu lub połączyć kilka systemów w jednym procesie.",
    "deliver": "Co otrzymujesz",
    "deliverables": [
      "Działający przepływ",
      "Obsługa błędów i wyjątków",
      "Historia operacji",
      "Walidacja danych",
      "Testy",
      "Dokumentacja",
      "Kod lub rozwiązanie przekazane klientowi",
      "Jasne kryteria odbioru"
    ],
    "brief": "Masz proces lub zakres do przekazania?",
    "briefNote": "Nie wpisuj danych poufnych. Formularz przygotuje wiadomość w Twoim programie pocztowym; nic nie jest wysyłane automatycznie.",
    "send": "Otwórz przygotowany e-mail",
    "copy": "Skopiuj email",
    "copied": "Adres skopiowany.",
    "copyFailed": "Nie udało się skopiować. Zaznacz widoczny adres e-mail.",
    "subject": "Proces do oceny — automatyzacja",
    "technical": "Demonstracje techniczne",
    "technicalIntro": "Przykłady na danych syntetycznych pokazują sposób działania rozwiązań i ich weryfikacji. Nie przedstawiają wdrożeń wykonanych dla klientów.",
    "preview": "Zobacz działający przykład",
    "briefCta": "Pokaż mi swój proces",
    "small": "Możemy zacząć od jednego importu lub połączyć kilka systemów w jednym procesie.",
    "fallback": "Interaktywny przykład wymaga JavaScript. Możesz opisać proces e-mailem.",
    "loading": "Ładowanie przykładu…",
    "evidence": [
      "Zapas",
      "Opóźnienie (h)",
      "Status zgodny",
      "Zgoda"
    ],
    "product": "Symulator automatyzacji",
    "identity": "Niezależny wykonawca · integracje, migracje danych i systemy wewnętrzne",
    "engine": "Jak działa wspólny mechanizm?",
    "heroDiagram": "Od danych do aktualizacji systemu",
    "heroFlow": [
      "Dane z pliku lub systemu",
      "Sprawdzenie i reguły",
      "Aktualizacja systemu",
      "Wynik i historia"
    ],
    "builderActions": [
      "Import danych",
      "Sprawdzenie reguł",
      "Porównanie danych",
      "Decyzja człowieka",
      "Aktualizacja statusu",
      "Przygotowanie powiadomienia",
      "Przygotowanie raportu",
      "Klasyfikacja wyjątków"
    ],
    "normalBranch": "Poprawne rekordy → działanie automatyczne",
    "exceptionBranch": "Odrzucone rekordy → bez działania w systemie docelowym",
    "auditBoth": "Historia rejestruje obie gałęzie: przyjęcie, sprawdzenie, wynik lub wyjątek.",
    "humanReview": "Człowiek wyjaśnia wyjątek i zatwierdza dalszą decyzję. Brak automatycznej ponownej próby po decyzji.",
    "outline": "Ta kombinacja jest szkicem, nie skonfigurowanym przebiegiem. Trzeba uzgodnić obiekt danych, reguły, mapowanie, uprawnienia i właściciela decyzji. Wybierz domyślny scenariusz branży albo porównanie danych, aby uruchomić dostępny przykład.",
    "readOnly": "Raport rozbieżności — tylko odczyt",
    "readOnlyNote": "Porównanie nie poprawia danych i nie zapisuje niczego do ERP ani WMS. Miejsce raportu nie jest źródłem porównania.",
    "comparisonSource": "Z czym porównujemy?",
    "comparisonKey": "Po czym można znaleźć dopasowanie? (opcjonalnie)",
    "comparisonKeyDefault": "Identyfikator zamówienia",
    "comparisonDetails": "Przykład: zestaw A i zestaw B łączymy po polu reference, a value porównujemy dokładnie (tolerancja 0). Wspólne pole i jednostkę trzeba uzgodnić dla rzeczywistych danych. Porównanie jednostronne A → B; rekordy tylko w B nie są objęte tym przykładem. Duplikaty klucza nie są łączone automatycznie.",
    "comparisonScope": "Porównanie {0} z {2}. Sposób dopasowania: {3}. Lista zgodnych pozycji i rozbieżności do sprawdzenia, bez zmiany danych. Miejsce raportu: {1}.",
    "builderLimit": "To propozycja zakresu, nie potwierdzenie zgodności systemów. Trzeba uzgodnić format, mapowanie, uprawnienia i właściciela decyzji. Jeśli źródło i cel są tym samym systemem, wskaż różne obiekty lub uzasadnij operację wewnętrzną.",
    "builderMissing": "Uzupełnij drugi zestaw i klucz porównania przed przeniesieniem szkicu.",
    "referenceData": "Zestaw B — dane referencyjne",
    "sourceData": "Zestaw A",
    "reportRow": "Wiersz raportu zapisany",
    "matched": "Zgodne pary",
    "comparisonManual": [
      "Pobierz oba zestawy",
      "Połącz według klucza reference",
      "Porównaj pole value",
      "Zapisz rozbieżności do wyjaśnienia"
    ],
    "taskConstraints": [
      "Uzgodnij typ obiektu, mapowanie pól i klucz zapobiegający powtórnemu importowi.",
      "Uzgodnij reguły poprawności i raport błędów. Samo sprawdzenie nie poprawia danych.",
      "Nie musisz znać nazw pól ani reguł porównania. Ustalimy je wspólnie przed realizacją.",
      "Wskaż osobę uprawnioną do decyzji. Przepływ przekazuje prośbę i rejestruje decyzję; nie zastępuje zgody człowieka.",
      "Wskaż system nadrzędny, dozwolone zmiany statusu i obsługę spóźnionych zdarzeń.",
      "Uzgodnij odbiorcę, kanał, zgodę i ochronę przed powtórną wysyłką. Szkic nie wysyła wiadomości.",
      "Uzgodnij zakres danych, okres i zasady agregacji raportu.",
      "Wskaż właściciela wyjątków, sposób eskalacji i warunki ponownego przetworzenia po decyzji."
    ],
    "briefIntro": "Opisz zadanie i podaj używane systemy. Jeśli masz dokumentację API lub przykładowy eksport bez danych poufnych, dołącz je do e-maila.",
    "briefHelp": "Nie musisz samodzielnie przygotowywać specyfikacji technicznej. Dokumentację lub plik możesz dołączyć w swoim programie pocztowym."
  },
  "en": {
    "title": "Try an automation example",
    "intro": "Choose an example and see which records move automatically and which need a human decision.",
    "demo": "Demonstration with synthetic data",
    "boundary": "This simulation runs in your browser. It does not connect to an ERP, send messages or make payments.",
    "industry": "Industry",
    "pattern": "What would you like to automate?",
    "before": "Before",
    "after": "After automation",
    "human": "People handle exceptions and decisions.",
    "humanNote": "Records that pass the checks move on. The rest go to review.",
    "manual": [
      "Email",
      "Employee",
      "Spreadsheet",
      "Employee",
      "System",
      "Email",
      "Operations team"
    ],
    "stages": [
      "Input",
      "Validation",
      "Business rules",
      "Branch selection",
      "Outcomes of both branches",
      "Audit / result"
    ],
    "run": "Run example",
    "running": "Processing…",
    "reset": "Clear result",
    "complete": "Run completed",
    "ready": "Ready to run",
    "step": "Stage",
    "normal": "Automatic",
    "review": "For review",
    "total": "Records",
    "queue": "Exception queue",
    "audit": "Audit log",
    "input": "Show input data and rules",
    "record": "Record",
    "reference": "Reference",
    "quantity": "Value",
    "expected": "Expected value",
    "valid": "Valid input",
    "yes": "Yes",
    "no": "No",
    "rule": "Rule",
    "reason": "Reason",
    "next": "Next action",
    "empty": "Run the example to see the result calculated from these records.",
    "normalNote": "Only records without rule violations reach the simulated target system.",
    "target": "Target-system result",
    "action": "Completed action",
    "auditNote": "Fixed demonstration clock. The same data and rules produce the same result.",
    "events": [
      "Input received",
      "Validation completed",
      "Rules checked",
      "Action recorded",
      "Exception created",
      "Assigned for review",
      "Run completed",
      "Rule violation — action withheld"
    ],
    "share": "Link to this example",
    "proof": "View tests and report",
    "badQuery": "Unknown example parameter. A safe default scenario is shown.",
    "builder": "What does your process look like?",
    "builderIntro": "Choose the data source, the task and the destination system to prepare an outline we can discuss.",
    "source": "Where does the data come from?",
    "manualQuestion": "What is done manually today?",
    "destination": "Where should the result go?",
    "sources": [
      "Email",
      "Excel / CSV",
      "Form",
      "CRM",
      "ERP",
      "Online store",
      "API",
      "Other"
    ],
    "tasks": [
      "Enter data",
      "Check data",
      "Compare data",
      "Approve",
      "Update a status",
      "Send a notification",
      "Prepare a report",
      "Handle exceptions"
    ],
    "destinations": [
      "ERP",
      "CRM",
      "Warehouse / WMS",
      "Accounting",
      "Operations dashboard",
      "Email",
      "API",
      "Another system"
    ],
    "builderSteps": [
      "Validation",
      "Mapping",
      "Exception queue",
      "Notification"
    ],
    "firstScope": "An example first scope",
    "scopeTemplates": [
      "Import one data type from {0} to {1}, with validation and an exception list.",
      "Check one dataset from {0}, apply quality rules and deliver the result to {1}.",
      "Compare one dataset from {0}, report differences and deliver the result to {1}.",
      "One decision flow from {0} to {1}, with human approval and an audit trail.",
      "Synchronize one status from {0} to {1}, with discrepancy checks.",
      "One notification from {0} to {1}, with recipient checks and delivery history.",
      "One recurring report from {0} to {1}, with source validation.",
      "One exception queue from {0} to {1}, with an owner and decision history."
    ],
    "useBrief": "Use this outline in the message",
    "systems": "Integration with your systems",
    "qualifier": "The integration options depend on the available API, import/export capabilities, permissions and test environment.",
    "systemsNote": "Examples of environments and sources — not certifications or official partnerships.",
    "ladder": "From one task to a complete process",
    "levels": [
      "Single integration",
      "Process automation",
      "Complete module or process"
    ],
    "levelFlows": [
      [
        "Excel",
        "Validation",
        "ERP"
      ],
      [
        "Form",
        "CRM",
        "ERP",
        "Notification"
      ],
      [
        "Ecommerce",
        "ERP",
        "WMS",
        "Transport",
        "Invoice",
        "Report"
      ]
    ],
    "ladderNote": "We can start with one import or connect several systems in a single workflow.",
    "deliver": "What you receive",
    "deliverables": [
      "A working flow",
      "Error and exception handling",
      "Operation history",
      "Data validation",
      "Tests",
      "Documentation",
      "Code or solution handed over to you",
      "Clear acceptance criteria"
    ],
    "brief": "Have a process or project to hand over?",
    "briefNote": "Do not enter confidential data. The form prepares a message in your email application; nothing is sent automatically.",
    "send": "Open prepared email",
    "copy": "Copy email address",
    "copied": "Address copied.",
    "copyFailed": "Copy failed. Select the displayed email address.",
    "subject": "Process for review — automation",
    "technical": "Technical demonstrations",
    "technicalIntro": "Examples with synthetic data show how solutions work and how they are verified. They do not represent implementations delivered for clients.",
    "preview": "See a working example",
    "briefCta": "Show me your process",
    "small": "We can start with one import or connect several systems in a single workflow.",
    "fallback": "The interactive example needs JavaScript. You can describe your process by email.",
    "loading": "Loading the example…",
    "evidence": [
      "Stock",
      "Delay (h)",
      "Status matches",
      "Approved"
    ],
    "product": "Automation Playground",
    "identity": "Independent contractor · integrations, data migrations and internal systems",
    "engine": "How does the shared engine work?",
    "heroDiagram": "From incoming data to a system update",
    "heroFlow": [
      "Data from a file or system",
      "Checks and rules",
      "System update",
      "Result and history"
    ],
    "builderActions": [
      "Import data",
      "Check rules",
      "Compare data",
      "Human decision",
      "Update status",
      "Prepare notification",
      "Prepare report",
      "Classify exceptions"
    ],
    "normalBranch": "Valid records → automated action",
    "exceptionBranch": "Rejected records → no target-system action",
    "auditBoth": "History records both branches: receipt, checks, outcome or exception.",
    "humanReview": "A person investigates the exception and approves the next decision. No automatic retry after that decision.",
    "outline": "This combination is an outline, not a configured run. Agree the data object, rules, mapping, permissions and decision owner first. Select the industry default or data comparison to run an available example.",
    "readOnly": "Discrepancy report — read only",
    "readOnlyNote": "Comparison does not correct data or write to ERP or WMS. The report destination is not the comparison source.",
    "comparisonSource": "What should we compare it with?",
    "comparisonKey": "How can we find a match? (optional)",
    "comparisonKeyDefault": "Order identifier",
    "comparisonDetails": "Example: dataset A and dataset B join on reference; value is compared exactly (tolerance 0). Agree a common field and unit for real data. One-way comparison A → B; B-only records are outside this example. Duplicate keys are not matched automatically.",
    "comparisonScope": "Compare {0} with {2}. How to find a match: {3}. A list of matches and discrepancies to review, without changing data. Report destination: {1}.",
    "builderLimit": "This is a scope proposal, not confirmed system compatibility. Agree format, mapping, permissions and decision owner. If source and destination are the same system, specify different objects or justify the internal operation.",
    "builderMissing": "Provide the second dataset and matching key before transferring the brief.",
    "referenceData": "Dataset B — reference records",
    "sourceData": "Dataset A",
    "reportRow": "Report row recorded",
    "matched": "Matched pairs",
    "comparisonManual": [
      "Export both datasets",
      "Join by reference key",
      "Compare the value field",
      "Record differences for review"
    ],
    "taskConstraints": [
      "Agree the object type, field mapping and key that prevents repeated imports.",
      "Agree validation rules and an error report. Checking alone does not correct data.",
      "You do not need to know field names or comparison rules. We will agree them together before implementation.",
      "Identify the authorized decision maker. The flow routes a request and records a decision; it does not replace human approval.",
      "Identify the authoritative system, allowed status transitions and handling of late events.",
      "Agree recipient, channel, permission and duplicate-send protection. The outline sends no messages.",
      "Agree the data scope, reporting period and aggregation rules.",
      "Identify the exception owner, escalation path and conditions for reprocessing after a decision."
    ],
    "briefIntro": "Describe the task and the systems you use. If you have API documentation or a sample export without confidential data, attach it to your email.",
    "briefHelp": "You do not need to prepare a technical specification yourself. You can attach documentation or a file in your email application."
  }
});
