import {expect,test} from '@playwright/test';
test('Data Quality baseline, field lineage, one regression, comparison, quarantine, reset and exports',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto('/data-quality');await page.reload();await expect(page.getByRole('heading',{name:'Kontrola jakości danych w potoku',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Uruchom pakiet referencyjny',exact:true}).click();await expect(page.getByTestId('quality-overall')).toHaveText('PASS');await expect(page.getByTestId('quality-result')).toHaveCount(16);
  await page.getByRole('button',{name:'Kontrakt danych',exact:true}).click();await expect(page.getByTestId('quality-field')).toHaveCount(9);await expect(page.getByTestId('quality-field').filter({hasText:'gross_amount_raw'})).toContainText('Decimal(2)');
  await page.getByRole('button',{name:'Schema drift',exact:true}).click();const driftTable=page.locator('table').filter({hasText:'SCHEMA_OPTIONAL_ADDED'});await expect(driftTable).toContainText('source-customer-export/1.1');await expect(driftTable).toContainText('SCHEMA_OPTIONAL_ADDED');await expect(driftTable).toContainText('SCHEMA_REQUIRED_FIELD');await expect(driftTable).toContainText('mapping/customer-amount/2.1');
  await page.getByRole('button',{name:'Transformacje',exact:true}).click();await expect(page.getByTestId('quality-field').filter({hasText:'gross_amount_raw'})).toContainText('normalize_decimal_pl');
  await page.getByRole('button',{name:'Lineage',exact:true}).click();await expect(page.getByTestId('quality-lineage')).toContainText('1 234,50');await expect(page.getByTestId('quality-lineage')).toContainText('transactions.csv');
  await page.getByRole('button',{name:'Wprowadź kontrolowaną rozbieżność'}).click();await expect(page.getByTestId('quality-overall')).toHaveText('FAIL');await expect(page.getByTestId('quality-result')).toHaveCount(1);await expect(page.getByTestId('quality-result')).toContainText('123450.00');
  await page.getByRole('button',{name:'Dowód',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('122215.50');await expect(page.getByRole('dialog')).toContainText('gross_amount_raw');await page.keyboard.press('Escape');
  await page.getByLabel('Wynik testu',{exact:true}).selectOption('PASS');await expect(page.getByTestId('quality-result')).toHaveCount(15);await page.getByLabel('Szukaj wyniku').fill('no-match');await expect(page.getByTestId('quality-result')).toHaveCount(0);
  await page.getByRole('button',{name:'Lineage',exact:true}).click();await expect(page.getByTestId('quality-lineage')).toContainText('123450.00');await expect(page.getByTestId('quality-lineage')).toContainText('×100');await page.getByRole('button',{name:'Dowód pola'}).click();await expect(page.getByRole('dialog')).toContainText('typed_value');await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Regresja',exact:true}).click();await expect(page.getByTestId('quality-comparison')).toContainText('Nowe błędy: 1');await expect(page.getByTestId('quality-comparison')).toContainText('Zmienione pola: 1');
  await page.getByRole('button',{name:'Odrzucone',exact:true}).click();await expect(page.getByTestId('quality-rejected')).toHaveCount(1);await page.getByLabel('Zestaw odrzuceń').selectOption('negative');await expect(page.getByTestId('quality-rejected').first()).toContainText('Test: PASS');
  await page.getByRole('button',{name:'Przebiegi',exact:true}).click();expect(await page.getByRole('button',{name:'Raport przebiegu'}).count()).toBeGreaterThanOrEqual(2);
  await page.getByRole('button',{name:'Przywróć konfigurację referencyjną'}).click();await expect(page.getByTestId('quality-overall')).toHaveText('PASS');await page.getByRole('button',{name:'Regresja',exact:true}).click();await expect(page.getByTestId('quality-comparison')).toContainText('Nowe błędy: 0');await expect(page.getByTestId('quality-comparison')).toContainText('Zmienione pola: 0');
  await page.getByRole('button',{name:'Raport',exact:true}).click();for(const format of ['JSON','CSV']){const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:`Pobierz ${format}`}).click()]);expect(download.suggestedFilename()).toBe(`data-quality-acceptance.${format.toLowerCase()}`);}
  await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Lineage',exact:true}).click();await expect(page.getByTestId('quality-lineage')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
test('Data Quality imports JSON and rejects malformed input with recoverable UI',async({page,request})=>{
  const fixture=await (await request.get('/lab-api/data-quality/fixtures?format=json')).json();await page.goto('/data-quality');await page.getByRole('button',{name:'Wejście',exact:true}).click();await page.getByLabel('Wczytaj CSV/JSON').setInputFiles({name:'transactions.json',mimeType:'application/json',buffer:Buffer.from(fixture.content)});await page.getByRole('button',{name:'Uruchom na wczytanym wejściu'}).click();await expect(page.getByTestId('quality-overall')).toHaveText('PASS');
  await page.getByRole('button',{name:'Wejście',exact:true}).click();await page.getByLabel('Dane źródłowe').fill('{');await page.getByRole('button',{name:'Uruchom na wczytanym wejściu'}).click();await expect(page.getByRole('alert')).toContainText('422');await page.getByRole('button',{name:'Przywróć konfigurację referencyjną'}).click();await expect(page.getByTestId('quality-overall')).toHaveText('PASS');
});
