import {defineCopy} from './localization-contract';
export const apiProofCopy=defineCopy('api-tests',{
  "pl": {"architectureLabel":"Schemat architektury demonstratora","filterLabel":"Filtr wyników","contractLabel":"Walidacja kontraktu API",
    "back": "← Wszystkie przykłady",
    "eyebrow": "Przykład techniczny · dane demonstracyjne",
    "title": "Testy integracji API",
    "subtitle": "i zachowania interfejsu",
    "intro": "Wykonywalny pakiet testów dla synchronizacji zamówień B2B: od danych źródłowych, przez mapowanie, po odpowiedź systemu docelowego i raport PASS/FAIL.",
    "scope": "Zakres demonstracyjny",
    "metric1": "12 deterministycznych scenariuszy",
    "metric2": "2 syntetyczne endpointy",
    "metric3": "Raport wartości oczekiwanych i rzeczywistych",
    "flow": [
      "Payload źródłowy i kontrakt odpowiedzi API.",
      "Mapowanie → żądanie HTTP → walidacja odpowiedzi.",
      "Status, schemat, mapowanie, duplikat i timeout.",
      "Wartości oczekiwane i rzeczywiste, różnice JSON i raport JSON/CSV.",
      "Wyniki zgadzają się z macierzą scenariuszy; dodatek async: PASS → jedna regresja → PASS."
    ],
    "pack": "Pakiet scenariuszy",
    "result": "Wynik wykonania",
    "intent": "Zamierzone wyniki FAIL wykazują wykrycie rozbieżności — nie oznaczają błędu aplikacji.",
    "run": "Uruchom pakiet testów",
    "rerunAll": "Uruchom ponownie wszystkie",
    "running": "Wykonywanie…",
    "scenarios": "scenariuszy",
    "empty": "Pakiet sprawdzi mapowanie pól, walidację kontraktu, statusy HTTP, idempotencję, zgodność danych oraz zachowanie retry.",
    "all": "Wszystkie testy",
    "duration": "Suma czasów scenariuszy",
    "allFilter": "Wszystkie",
    "exportJson": "Eksport JSON",
    "exportCsv": "Eksport CSV",
    "expected": "Oczekiwane",
    "actual": "Rzeczywiste",
    "collapse": "Zwiń",
    "rerun": "Uruchom ponownie",
    "request": "Żądanie i dane",
    "diff": "Różnica",
    "noDiff": "Brak różnic względem kontraktu.",
    "contractTitle": "Walidacja kontraktu i kompatybilności",
    "contractBody": "Mały kontrakt odpowiedzi jest wykonywany na sześciu odpowiedziach syntetycznych. Dodatkowe pole opcjonalne zachowuje zgodność, a brak pola wymaganego lub zmiana typu narusza kontrakt.",
    "scenario": "Scenariusz",
    "responseVersion": "Wersja odpowiedzi",
    "status": "Wynik",
    "compat": "Kompatybilność",
    "demonstrates": "Co ten przykład pokazuje",
    "demoTitle": "Testowalny kontrakt zamiast niejasnej integracji",
    "demoIntro": "Scenariusze i dane są syntetyczne. W realnym zakresie kryteria powstają na podstawie uzgodnionej specyfikacji i przykładów.",
    "cards": [
      [
        "01 · Wejście",
        "Kontrakt i przykłady",
        "Specyfikacja pól, wartości słownikowych i przykładowe dane źródłowe oraz docelowe."
      ],
      [
        "02 · Scenariusze",
        "Jawne scenariusze",
        "Sukcesy, oczekiwane odrzucenia, błędy kontraktu oraz zachowanie transportu."
      ],
      [
        "03 · Wynik",
        "Raport PASS/FAIL",
        "Identyfikator, payload, oczekiwany i rzeczywisty wynik oraz czytelny JSON diff."
      ],
      [
        "04 · Odbiór",
        "Mierzalny odbiór",
        "Stały zestaw danych, uzgodnione wyniki i wykonywalny pakiet regresji do ponownego użycia."
      ]
    ],
    "scopeKicker": "Zakres wdrożeniowy",
    "scopeTitle": "Wydzielony odbiór integracji API",
    "scopeP1": "Specyfikacja API i przykłady → uzgodnione scenariusze → wykonywalny pakiet testów → raport rozbieżności → odbiór PASS/FAIL.",
    "scopeP2": "Zakres koncentruje się na wydzielonej integracji, regresji po zmianie lub walidacji migracji i jednoznacznych kryteriach odbioru.",
    "cta": "Omówić podobny zakres",
    "source": "Źródło",
    "contract": "Kontrakt",
    "mapping": "Walidacja i mapowanie",
    "target": "Cel",
    "acceptance": "Odbiór",
    "testReport": "Raport testów",
    "warning": "Ostrzeżenie",
    "contractFirst": "API oparte na kontrakcie",
    "version": "Wersja kontraktu",
    "compatible": "Zgodne",
    "breaking": "Niezgodne lub błędne",
    "fieldRule": "Pole / reguła",
    "expectedActual": "Oczekiwane / rzeczywiste",
    "cases": "12 scenariuszy testowych"
  },
  "en": {"architectureLabel":"Demo architecture diagram","filterLabel":"Result filter","contractLabel":"API contract validation",
    "back": "← All examples",
    "eyebrow": "Technical demonstration · synthetic data",
    "title": "API integration tests",
    "subtitle": "and interface behavior",
    "intro": "Executable test package for B2B order synchronization: from source data through mapping to the target-system response and PASS/FAIL report.",
    "scope": "Demonstration scope",
    "metric1": "12 deterministic scenarios",
    "metric2": "2 synthetic endpoints",
    "metric3": "Expected/actual report",
    "flow": [
      "Source payload and API response contract.",
      "Mapping → HTTP request → response validation.",
      "Status, schema, mapping, duplicate and timeout.",
      "Expected/actual, JSON diff and JSON/CSV report.",
      "Results match the scenario matrix; async supplement: PASS → one regression → PASS."
    ],
    "pack": "Scenario package",
    "result": "Execution result",
    "intent": "Intentional FAIL results prove discrepancy detection; they do not mean an application error.",
    "run": "Run test package",
    "rerunAll": "Rerun all",
    "running": "Running…",
    "scenarios": "scenarios",
    "empty": "The package checks field mapping, contract validation, HTTP statuses, idempotency, data consistency and retry behavior.",
    "all": "All tests",
    "duration": "Total scenario time",
    "allFilter": "All",
    "exportJson": "Export JSON",
    "exportCsv": "Export CSV",
    "expected": "Expected",
    "actual": "Actual",
    "collapse": "Collapse",
    "rerun": "Rerun",
    "request": "Request / payload",
    "diff": "Diff",
    "noDiff": "No differences against the contract.",
    "contractTitle": "Contract validation and compatibility",
    "contractBody": "A small response contract is executed against six synthetic responses. An added optional field is compatible; a missing required field or type change is breaking.",
    "scenario": "Scenario",
    "responseVersion": "Response version",
    "status": "Result",
    "compat": "Compatibility",
    "demonstrates": "What this example demonstrates",
    "demoTitle": "A testable contract instead of an unclear integration",
    "demoIntro": "Scenarios and data are synthetic. In a real scope, criteria are based on the agreed specification and examples.",
    "cards": [
      [
        "01 · Input",
        "Contract and examples",
        "Field specification, dictionary values and sample source/target payloads."
      ],
      [
        "02 · Test cases",
        "Explicit scenarios",
        "Success cases, expected rejections, contract errors and transport behavior."
      ],
      [
        "03 · Result",
        "PASS/FAIL report",
        "Identifier, payload, expected and actual result, and readable JSON diff."
      ],
      [
        "04 · Acceptance",
        "Measurable acceptance",
        "Stable dataset, agreed results and a reusable executable regression package."
      ]
    ],
    "scopeKicker": "Implementation scope",
    "scopeTitle": "Isolated API integration acceptance",
    "scopeP1": "API specification and examples → agreed scenarios → executable test pack → discrepancy report → PASS/FAIL acceptance.",
    "scopeP2": "The scope focuses on an isolated integration, post-change regression or migration validation with clear acceptance criteria.",
    "cta": "Discuss a similar scope",
    "source": "Source",
    "contract": "Contract",
    "mapping": "Validation / mapping",
    "target": "Target",
    "acceptance": "Acceptance",
    "testReport": "Test report",
    "warning": "Warning",
    "contractFirst": "Contract-first API",
    "version": "Contract version",
    "compatible": "Compatible",
    "breaking": "Breaking / invalid",
    "fieldRule": "Field / rule",
    "expectedActual": "Expected / actual",
    "cases": "12 test cases"
  }
});
