import {useContactHref} from './contact-copy';
import {useDomainText,useDomainValue} from './domain-copy';
import ProofFlow from './ProofFlow';
import SupplementPack from './SupplementPack';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useLocale } from './locale';
import { ApiTestResult, DemoTestStatus, expectedFixture, exportResultsCsv, runApiTest, runApiTestPack } from './api-test-pack';
import { runContractCompatibilityPack } from './api-contract';

type Filter = 'ALL' | DemoTestStatus;
function download(content: string, name: string, type: string) { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); }
import { apiProofCopy } from './api-copy';
export { apiProofCopy } from './api-copy';

export default function ApiTestsPage() { const contact=useContactHref();  const locale=useLocale(); const en=locale==='en'; const c=apiProofCopy[locale];
  const [results, setResults] = useState<ApiTestResult[]>([]); const [filter, setFilter] = useState<Filter>('ALL'); const [expanded, setExpanded] = useState<string | null>(null); const [running, setRunning] = useState<string[]>([]);
  const filtered = useMemo(() => results.filter(row => filter === 'ALL' || row.status === filter), [results, filter]);
  const counts = useMemo(() => ({ PASS: results.filter(x => x.status === 'PASS').length, FAIL: results.filter(x => x.status === 'FAIL').length, WARNING: results.filter(x => x.status === 'WARNING').length }), [results]);
  const duration = Math.round(results.reduce((sum, row) => sum + row.durationMs, 0) * 100) / 100; const contractResults = useMemo(() => runContractCompatibilityPack(), []);
  const runAll = async () => { setRunning(expectedFixture.map(x => x.id)); setExpanded(null); try { setResults(await runApiTestPack()); } finally { setRunning([]); } };
  const rerun = async (id: string) => { setRunning(current => [...current, id]); try { const next = await runApiTest(id); setResults(current => current.map(row => row.id === id ? next : row)); } finally { setRunning(current => current.filter(item => item !== id)); } };
  const domain=useDomainText(); const text=useDomainValue(); const name=(row:ApiTestResult)=>domain(row.name); const cat=(row:ApiTestResult)=>domain(row.category);
  return <main className="api-tests-page"><section className="api-intro shell"><Link className="back" to={en?'/en':'/'}>{c.back}</Link><div className="eyebrow">{c.eyebrow}</div><div className="api-intro-grid"><div><h1>{c.title}<br/><span>{c.subtitle}</span></h1><p>{c.intro}</p></div><div className="api-callout"><strong>{c.scope}</strong><span>{c.metric1}</span><span>{c.metric2}</span><span>{c.metric3}</span></div></div></section>
    <ProofFlow input={c.flow[0]} processing={c.flow[1]} failures={c.flow[2]} output={c.flow[3]} acceptance={c.flow[4]}/>
    <section className="architecture shell" aria-label={c.architectureLabel}><div className="arch-node"><small>{c.source}</small><strong>System A</strong><code>GET /source/orders</code></div><i>→</i><div className="arch-node accent"><small>{c.contract}</small><strong>{c.mapping}</strong><span>{c.cases}</span></div><i>→</i><div className="arch-node"><small>{c.target}</small><strong>System B</strong><code>POST /target/orders</code></div><i>→</i><div className="arch-node report"><small>{c.acceptance}</small><strong>{c.testReport}</strong><code>PASS / FAIL</code></div></section>
    <SupplementPack kind="async"/><section className="api-workspace shell"><div className="workspace-top"><div><span className="kicker">{c.pack}</span><h2>{c.result}</h2><p>{c.intent}</p></div><div className="workspace-actions"><button className="button primary" onClick={runAll} disabled={running.length > 0}>{running.length ? c.running : results.length ? c.rerunAll : c.run}</button></div></div>
      {!results.length ? <div className="api-empty"><div><span>12</span><small>{c.scenarios}</small></div><p>{c.empty}</p></div> : <div data-testid="api-results"><div className="api-summary"><article><span>{c.all}</span><strong data-testid="api-total">{results.length}</strong></article><article className="pass"><span>PASS</span><strong data-testid="api-pass">{counts.PASS}</strong></article><article className="fail"><span>FAIL</span><strong data-testid="api-fail">{counts.FAIL}</strong></article><article className="warning"><span>{c.warning}</span><strong data-testid="api-warning">{counts.WARNING}</strong></article><article><span>{c.duration}</span><strong>{duration} ms</strong></article></div><div className="api-toolbar"><div className="status-filters" aria-label={c.filterLabel}>{(['ALL','PASS','FAIL','WARNING'] as Filter[]).map(value => <button key={value} className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)}>{value === 'ALL' ? c.allFilter : value === 'WARNING' ? c.warning : value}<span>{value === 'ALL' ? results.length : counts[value]}</span></button>)}</div><div className="export-group"><button className="button secondary" onClick={() => download(JSON.stringify(results, null, 2), 'api-test-results.json', 'application/json')}>{c.exportJson}</button><button className="button secondary" onClick={() => download(`\uFEFF${exportResultsCsv(results)}`, 'api-test-results.csv', 'text/csv;charset=utf-8')}>{c.exportCsv}</button></div></div><div className="test-list">{filtered.map(row => <article className={`test-row ${row.status.toLowerCase()}`} key={row.id}><div className="test-main"><div className="test-id"><code>{row.id}</code><span className={`test-status ${row.status.toLowerCase()}`}>{row.status==='WARNING'?c.warning:row.status}</span></div><div className="test-name"><strong>{name(row)}</strong><small>{cat(row)} · {row.durationMs} ms</small></div><div className="test-expect"><small>{c.expected}</small><span>{text(row.expected)}</span></div><div className="test-actual"><small>{c.actual}</small><span>{text(row.actual)}</span></div><div className="test-actions"><button onClick={() => setExpanded(expanded === row.id ? null : row.id)}>{expanded === row.id ? c.collapse : 'JSON diff'}</button><button onClick={() => rerun(row.id)} disabled={running.includes(row.id)}>{running.includes(row.id) ? '…' : c.rerun}</button></div></div>{expanded === row.id && <div className="json-diff" data-testid="json-diff"><div><small>{c.request}</small><pre>{JSON.stringify(row.request, null, 2)}</pre></div><div><small>{c.diff}</small>{Object.keys(row.diff).length?<pre>{JSON.stringify(row.diff, null, 2)}</pre>:<p>{c.noDiff}</p>}</div></div>}</article>)}</div></div>}
    </section><section className="api-workspace shell" aria-label={c.contractLabel}><div className="workspace-top"><div><span className="kicker">{c.contractFirst}</span><h2>{c.contractTitle}</h2><p>{c.contractBody}</p></div></div><div className="api-summary"><article><span>{c.version}</span><strong data-testid="contract-version">target-order-response/1.2</strong></article><article className="pass"><span>{c.compatible}</span><strong>{contractResults.filter(row=>row.status==='PASS').length}</strong></article><article className="fail"><span>{c.breaking}</span><strong>{contractResults.filter(row=>row.status==='FAIL').length}</strong></article></div><div className="table-scroll" tabIndex={0}><table><thead><tr><th>{c.scenario}</th><th>{c.responseVersion}</th><th>{c.status}</th><th>{c.compat}</th><th>{c.fieldRule}</th><th>{c.expectedActual}</th></tr></thead><tbody>{contractResults.map(row=><tr key={row.id}><td><code>{row.id}</code><br/>{domain(row.name)}</td><td>{row.responseVersion}</td><td><span className={`test-status ${row.status.toLowerCase()}`}>{row.status}</span></td><td>{domain(row.compatibility)}</td><td>{row.field}<br/><small>{row.rule}</small></td><td>{text(row.expected)}<br/>{text(row.actual)}</td></tr>)}</tbody></table></div></section>
    <section className="technical shell section"><div className="section-heading"><div><span className="kicker">{c.demonstrates}</span><h2>{c.demoTitle}</h2></div><p>{c.demoIntro}</p></div><div className="pipeline">{c.cards.map(([b,h,p])=><article key={b}><b>{b}</b><h3>{h}</h3><p>{p}</p></article>)}</div></section><section className="commercial"><div className="shell commercial-grid"><div><span className="kicker">{c.scopeKicker}</span><h2>{c.scopeTitle}</h2></div><div><p><strong>{c.scopeP1.split(' → ')[0]}</strong>{c.scopeP1.includes(' → ')?' → '+c.scopeP1.split(' → ').slice(1).join(' → '):''}</p><p>{c.scopeP2}</p><a className="button primary" href={contact}>{c.cta}</a></div></div></section></main>;
}
