import {editorialCopy} from './editorial-copy';
import {homeJourney} from './home-journey-copy';
import {track} from './SiteMetrics';
import {inquiryAttribution,attributionText} from './inquiry-attribution';
import {exampleContext} from './BuyerJourney';
import {buyerCopy} from './buyer-copy';
import {useEffect,useRef,useState} from 'react';
import {Link,useLocation,useSearchParams} from 'react-router-dom';
import {useLocale,localizedPath} from './locale';
import {inquiryCopy,inquiryServices,inquiryGuidance} from './inquiry-copy';
import './services.css';
export function PrivacyPage(){const locale=useLocale(),c=inquiryCopy[locale];return <main className="shell section service-page"><h1>{c.privacyTitle}</h1><p>{c.privacyBody}</p><p>{c.privacy}</p><p>{c.analytics}</p><Link to={localizedPath('/contact',locale)}>{c.title}</Link></main>}
export function ContactForm({embedded=false}:{embedded?:boolean}){const locale=useLocale(),c=inquiryCopy[locale],[params,setParams]=useSearchParams(),location=useLocation();const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle');const [receipt,setReceipt]=useState('');const submission=useRef<string|null>(null);const initial=(location.state as {brief?:string}|null)?.brief??'';const b=buyerCopy[locale],context=exampleContext(params.get('example'),locale),reference=context?b.reference+': '+context.label+'\nhttps://work.matiushkin.com'+context.path+'\n\n':'';const service=inquiryServices.includes(params.get('service') as typeof inquiryServices[number])?params.get('service')!:context?.service??'other';
 const j=homeJourney[locale],started=useRef(false),formRef=useRef<HTMLFormElement>(null);
 useEffect(()=>{const form=formRef.current;if(!form)return;let seen=false;const observer=new IntersectionObserver(entries=>{if(!seen&&entries.some(e=>e.isIntersecting)){seen=true;track('form_view',location.pathname);observer.disconnect();}});observer.observe(form);return()=>observer.disconnect();},[location.pathname]);
 const Wrapper=embedded?'section':'main',Heading=embedded?'h2':'h1';
 const attribution=inquiryAttribution[locale],g=inquiryGuidance[locale],[selectedService,setSelectedService]=useState(service);
 return <Wrapper data-state={state} id={embedded?"send-task":undefined} className={embedded?"section contact-page editorial-contact":"shell section contact-page contact-page--standalone"}><div className={embedded?"shell contact-inner":undefined}>{!embedded&&<Link to={localizedPath('/',locale)}>{c.back}</Link>}{!embedded&&<Heading>{c.title}</Heading>}<div className="contact-grid"><div>{embedded&&<><p className="editorial-index">{editorialCopy[locale].contact}</p><Heading>{editorialCopy[locale].contactTitle}</Heading></>}<p>{c.intro}</p><p>{c.direct}: <a href="mailto:ivan@matiushkin.com">ivan@matiushkin.com</a></p><p className="contact-notice">{c.privacy}</p><Link to={localizedPath('/privacy',locale)}>{c.policy}</Link></div>{state==='success'?<div className="contact-status" role="status"><p>{c.success}</p><strong>{receipt}</strong></div>:<form aria-busy={state==='sending'} ref={formRef} onInput={()=>{if(!started.current){started.current=true;track("form_start",location.pathname);}}} method="post" action="/api/contact" className="contact-form" onSubmit={async e=>{e.preventDefault();if(state==='sending')return;const form=new FormData(e.currentTarget);submission.current??=crypto.randomUUID();setState('sending');try{const r=await fetch('/api/contact',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:submission.current,name:form.get('name'),email:form.get('email'),service:form.get('service'),message:reference+String(form.get('message')??'')+attributionText(form.get('discovery'),locale),website:form.get('website'),locale,path:localizedPath("/contact",locale)})});const data=await r.json() as {id?:string};if(!r.ok||!data.id)throw new Error('not_accepted');setReceipt(data.id);setState('success');}catch{setState('error');track('form_error',location.pathname);}}}>
 {context&&<aside className="buyer-context"><strong>{b.context}</strong><p><Link to={context.path}>{context.label}</Link></p><p>{b.contextNote}</p><button type="button" onClick={()=>{const next=new URLSearchParams(params);next.delete("example");setParams(next,{replace:true});}}>{b.remove}</button></aside>}<label>{c.email}<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>{c.message}<textarea name="message" aria-describedby="brief-hint" placeholder={c.placeholder} required minLength={20} maxLength={3900-reference.length} defaultValue={initial}/></label><p id="brief-hint" className="contact-notice">{c.hint}</p><details className="contact-guidance optional-details"><summary>{j.details}</summary><label>{c.name} ({g.optional})<input name="name" autoComplete="organization" maxLength={100}/></label><label>{c.service}<select name="service" value={selectedService} onChange={e=>setSelectedService(e.target.value)}>{inquiryServices.map((id,i)=><option key={id} value={id}>{c.options[i]}</option>)}</select></label><details className="contact-guidance"><summary>{g.details}</summary><ul>{g.prompts[inquiryServices.indexOf(selectedService as typeof inquiryServices[number])].map(prompt=><li key={prompt}>{prompt}</li>)}</ul><p>{g.unknown}</p></details><details className="contact-guidance"><summary>{attribution.label}</summary><label>{attribution.label}<select name="discovery" defaultValue="0">{attribution.options.map((option,i)=><option key={option} value={i}>{option}</option>)}</select></label><p>{attribution.note}</p></details></details><div className="honey" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div><button className="button primary" type="submit" disabled={state==='sending'}>{state==='sending'?c.sending:c.send}</button>{state==='error'&&<p role="alert">{c.error}</p>}<noscript><p>{c.direct}: <a href="mailto:ivan@matiushkin.com">ivan@matiushkin.com</a></p></noscript></form>}{!embedded&&<section className="contact-next"><h2>{g.next}</h2><ol>{g.steps.map(step=><li key={step}>{step}</li>)}</ol><p>{g.noCommitment}</p></section>}</div></div></Wrapper>
}

export default function ContactPage(){return <ContactForm/>;}
