import {useContactHref} from './contact-copy';
import {useErrorText} from './error-copy';
import {useDomainValue} from './domain-copy';
import {useDomainText} from './domain-copy';
import VerificationGuide from './VerificationGuide';
import {useEffect,useRef,useState,type ChangeEvent} from 'react';
import {Link} from 'react-router-dom';
import { useLocale } from './locale';
import {EvidenceView} from './WorkflowViews';
import './data-quality.css';
import {QualitySummary,QualityResults,QualityContract,QualityLineage,QualityRejected,QualityDiff,QualityReportDetails} from './QualityViews';
import {filterQuality,qualityFilters,schemaDriftScenarios,type QualityInput,type QualityReport,type QualityComparison} from './quality-model';
const root='/lab-api/data-quality';
async function api<T>(path:string,data?:unknown):Promise<T>{const r=await fetch(root+path,data===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error(`HTTP ${r.status}: ${(await r.text()).slice(0,300)}`);return r.json() as Promise<T>;}
import { dataQualityCopy } from './quality-copy';
export { dataQualityCopy } from './quality-copy';

export default function DataQualityPage(){ const contact=useContactHref(); const errorText=useErrorText();  const enumText=useDomainValue();  const valueText=useDomainValue();  const domain=useDomainText();
  const locale=useLocale(); const c=dataQualityCopy[locale];
  const [input,setInput]=useState<QualityInput|null>(null),[report,setReport]=useState<QualityReport|null>(null),[reference,setReference]=useState<QualityReport|null>(null),[history,setHistory]=useState<QualityReport[]>([]),[diff,setDiff]=useState<QualityComparison|null>(null),[tab,setTab]=useState('Wyniki'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filters,setFilters]=useState(qualityFilters),[record,setRecord]=useState('TX-104'),[field,setField]=useState('gross_amount'),[quarantine,setQuarantine]=useState('current'),[selected,setSelected]=useState<unknown>(null);const dialog=useRef<HTMLDialogElement>(null);
  const drift=schemaDriftScenarios();
  useEffect(()=>{let active=true;api<QualityInput>('/fixtures').then(r=>{if(active)setInput(r);}).catch(e=>{if(active)setError(errorText(String(e)));});return()=>{active=false;};},[]);
  async function run(mode:'baseline'|'inject'|'current'){setBusy(true);setError('');try{const r=await api<QualityReport>(mode==='baseline'?'/regression/reset':mode==='inject'?'/regression/inject':'/run',mode==='current'?{data:input}:{});const base=mode==='baseline'?r:reference;setReport(r);setInput(r.artifacts.input);if(mode==='baseline')setReference(r);setFilters({...qualityFilters,status:r.failed_scenarios?'FAIL':'ALL'});setQuarantine(r.rejected?'current':'negative');setRecord(r.artifacts.lineage.some(e=>e.record_id==='TX-104')?'TX-104':r.artifacts.lineage[0]?.record_id??'');setTab('Wyniki');setHistory(await api<QualityReport[]>('/runs'));setDiff(base?await api<QualityComparison>(`/runs/${base.run_id}/comparison/${r.run_id}`):null);}catch(e){setError(errorText(String(e)));}finally{setBusy(false);}}
  function show(v:unknown){setSelected(v);dialog.current?.showModal();}
  async function readFile(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{const format=file.name.toLowerCase().endsWith('.csv')?'csv':file.name.toLowerCase().endsWith('.json')?'json':null;if(!format||file.size>800000)throw new Error('Wymagany CSV/JSON do 800 kB.');setInput({filename:file.name,format,content:await file.text(),configuration:'baseline'});setError('');}catch(err){setError(errorText(String(err)));}e.target.value='';}
  async function download(format:'json'|'csv'){if(!report)return;try{const r=await fetch(`${root}/runs/${report.run_id}/report?format=${format}`);if(!r.ok)throw new Error('Błąd eksportu');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`data-quality-acceptance.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(errorText(String(e)));}}
  const edge=report?.artifacts.lineage.find(e=>e.record_id===record&&e.target_field===field);const rows=filterQuality(report?.artifacts.scenarios??[],filters);const mode=report?.artifacts.configuration??'baseline';
  return <main className="data-quality"><section className="shell tool-intro workflow-intro"><Link className="back" to={locale==='en'?'/en':'/'}>{c.back}</Link><div className="eyebrow">{c.eyebrow}</div><p className="wf-trust">{c.trust}</p><h1>{c.title}</h1><p className="lab-standards">{c.standards}</p><p><strong>{c.buyer}</strong> {c.buyerBody}</p><p className="lab-boundary">{c.scope} {c.scopeBody}</p></section>
  <section className="shell pipeline five">{c.flow.map(([h,p])=><article key={h}><b>{h}</b><p>{p}</p></article>)}</section>
  <section className="workspace shell lab-workspace"><VerificationGuide/><div className="workspace-top"><div><span className="kicker">{c.pack}</span><h2>{c.packTitle}</h2><p>{c.packBody}</p></div><div className="workspace-actions"><button className="button primary" disabled={busy||!input} onClick={()=>void run('baseline')}>{c.runRef}</button><button className="button secondary" disabled={busy||!reference} onClick={()=>void run('inject')}>{c.defect}</button><button disabled={busy||!input} onClick={()=>void run('baseline')}>{c.restore}</button></div></div>
  <div className="wf-note" data-testid="quality-mode"><strong>{mode==='controlled'?c.modeControlled:c.modeBase}</strong><p>{mode==='controlled'?c.modeControlledBody:c.modeBaseBody}</p></div>
  {busy&&<p role="status">{c.busy}</p>}{error&&<p role="alert">{error}</p>}
  <h3>{c.tech}</h3><p>{c.techBody}</p><nav className="lab-tabs" aria-label={c.sections}>{['Wejście','Wyniki','Kontrakt danych','Schema drift','Transformacje','Odrzucone','Lineage','Przebiegi','Regresja','Raport','Architektura'].map((t,i)=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{c.tabs[i]}</button>)}</nav>{!report&&["Kontrakt danych","Transformacje","Odrzucone","Lineage","Przebiegi","Regresja","Raport"].includes(tab)&&<div className="empty-state"><h3>{c.empty}</h3><p>{c.emptyBody}</p></div>}
  {tab==='Wejście'&&<><h3>{c.inputTitle}</h3><p>{c.inputBody}</p><label>{c.upload}<input type="file" aria-label={c.upload} accept=".csv,.json" onChange={e=>void readFile(e)}/></label>{input&&<><p>{input.filename} · {input.format}</p><textarea aria-label={c.sourceData} value={input.content} onChange={e=>setInput({...input,content:e.target.value,configuration:'baseline'})}/><button disabled={busy} onClick={()=>void run('current')}>{c.runCurrent}</button></>}{report&&<><h3>{c.actualStages}</h3><EvidenceView value={{staging:report.artifacts.staging,normalized:report.artifacts.normalized,candidate_target:report.artifacts.candidate_target,accepted_target:report.artifacts.target}}/></>}</>}
  {tab==='Wyniki'&&report&&<><QualitySummary report={report}/><div className="lab-toolbar">{([['status',c.resultFilter,['ALL','PASS','FAIL']],['category',c.category,['ALL',...new Set(report.artifacts.scenarios.map(r=>r.category))]],['entity',c.entity,['ALL','Transaction']],['severity',c.priority,['ALL','HIGH']]] as [keyof typeof filters,string,string[]][]).map(([key,label,options])=><label key={key}>{label}<select aria-label={label} value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}>{options.map(v=><option key={v} value={v}>{enumText(v)}</option>)}</select></label>)}<input aria-label={c.search} value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></div><QualityResults rows={rows} show={show}/></>}
  {tab==='Kontrakt danych'&&report&&<><h3>{c.contractTitle}</h3><p>{c.contractBody}</p><QualityContract fields={report.artifacts.contract}/></>}
  {tab==='Schema drift'&&<><h3>{c.driftTitle}</h3><p>{c.driftBody}</p><div className="table-scroll"><table><thead><tr>{c.driftHeaders.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{drift.map(row=><tr key={row.name}><td>{domain(row.name)}</td><td><span className={`test-status ${row.status.toLowerCase()}`}>{row.status}</span></td><td>{row.sourceSchemaVersion}<br/>{row.mappingVersion}<br/>{row.targetSchemaVersion}</td><td>{row.field}<br/><small>{row.rule}</small></td><td>{valueText(row.expected)}<br/>{valueText(row.actual)}</td><td>{domain(row.policy)}<br/><small>{c.quarantine} {row.quarantined}</small></td></tr>)}</tbody></table></div><EvidenceView value={drift}/></>}
  {tab==='Transformacje'&&report&&<><h3>{c.transformTitle}</h3><QualityContract fields={report.artifacts.contract} transforms/><h3>{c.rulesTitle}</h3><div className="table-scroll"><table><thead><tr>{c.ruleHeaders.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{report.artifacts.rules.map(r=><tr key={r.id}><td>{r.id}</td><td>{valueText(r.category)}</td><td>{domain(r.condition)}</td></tr>)}</tbody></table></div></>}
  {tab==='Lineage'&&report&&<><div className="lab-toolbar"><label>{c.targetRecord}<select aria-label={c.targetRecord} value={record} onChange={e=>setRecord(e.target.value)}>{[...new Set(report.artifacts.lineage.map(e=>e.record_id))].map(v=><option key={v} value={v}>{enumText(v)}</option>)}</select></label><label>{c.targetField}<select aria-label={c.targetField} value={field} onChange={e=>setField(e.target.value)}>{report.artifacts.contract.map(f=><option key={f.target}>{f.target}</option>)}</select></label></div>{edge?<QualityLineage edge={edge} show={show}/>:<p>{c.noLineage}</p>}</>}
  {tab==='Odrzucone'&&report&&<><h3>{c.rejectTitle}</h3><label>{c.rejectSet}<select aria-label={c.rejectSet} value={quarantine} onChange={e=>setQuarantine(e.target.value)}><option value="current">{c.currentRun}</option><option value="negative">{c.negative}</option></select></label><p>{c.rejectBody}</p><QualityRejected rows={quarantine==='current'?report.artifacts.rejected:report.artifacts.negative_rejected} show={show}/></>}
  {tab==='Przebiegi'&&<><h3>{c.runsTitle}</h3><p>{c.runsBody}</p><div className="table-scroll"><table><thead><tr>{c.runHeaders.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{history.map(r=><tr key={r.run_id}><td>{r.run_id}<br/>{r.input_sha256.slice(0,16)}…</td><td>{r.timestamp}</td><td>{r.records_received} / {r.accepted} / {r.rejected}</td><td>{r.quality_checks} / {r.failed_scenarios}</td><td>{r.overall_status}</td><td><button onClick={()=>show(r)}>{c.runReport}</button></td></tr>)}</tbody></table></div></>}
  {tab==='Regresja'&&<><h3>{c.regressionTitle}</h3>{diff?<><p>A: {diff.run_a}<br/>B: {diff.run_b}</p><QualityDiff diff={diff}/></>:<p>{c.regressionEmpty}</p>}</>}
  {tab==='Raport'&&report&&<><h3>{c.reportTitle}</h3><QualitySummary report={report}/><QualityReportDetails report={report}/><p>{c.reportBody}</p><div className="workspace-actions"><button onClick={()=>void download('json')}>{c.json}</button><button onClick={()=>void download('csv')}>{c.csv}</button></div><EvidenceView value={report}/></>}
  {tab==='Architektura'&&<><h3>{c.archTitle}</h3><p>{c.archBody}</p><a href="/lab-api/docs" target="_blank" rel="noreferrer">{c.docs}</a></>}
  </section><section className="shell section"><h2>{c.verify}</h2><p>{c.verifyBody}</p><h3>{c.criteria}</h3><p>{c.criteriaBody}</p><h3>{c.demoScope}</h3><p>{c.demoBody1}</p><p>{c.demoBody2}</p><a className="button primary" href={contact}>{c.cta}</a></section><dialog ref={dialog} className="issue-dialog" onClose={()=>setSelected(null)}><button className="dialog-close" aria-label={c.close} onClick={()=>dialog.current?.close()}>×</button><h2>{c.dialog}</h2><EvidenceView value={selected}/></dialog></main>;
}
