import {useContactHref} from './contact-copy';
import {useErrorText} from './error-copy';
import {useDomainValue} from './domain-copy';
import { useLocale, localizedPath } from './locale';
import { useProofLabel } from './proof-labels';
import { useProofText } from './proof-copy';
import VerificationGuide from './VerificationGuide';
import {useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {EvidenceView} from './WorkflowViews';
import {ErpMappings,ErpSummary,ErpTable} from './ErpViews';
import {filterErp,initialErpFilters,type ErpReport} from './erp-model';
import { useCounted } from './localized-count';
const root='/lab-api/erp-sync';
async function api(path:string,data:unknown={}):Promise<ErpReport>{const response=await fetch(root+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!response.ok)throw new Error(`HTTP ${response.status}: ${(await response.text()).slice(0,300)}`);return response.json() as Promise<ErpReport>;}
export default function ErpPage(){ const contact=useContactHref(); const errorText=useErrorText();  const enumText=useDomainValue();  const valueText=useDomainValue(); const counted=useCounted();  const homePath=localizedPath('/',useLocale()); const t = useProofText(); const label = useProofLabel();
  const [report,setReport]=useState<ErpReport|null>(null),[tab,setTab]=useState('Wyniki'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filters,setFilters]=useState(initialErpFilters),[selected,setSelected]=useState<unknown>(null);const dialog=useRef<HTMLDialogElement>(null);
  async function run(path:string,data:unknown={}){setBusy(true);setError('');try{const r=await api(path,data);setReport(r);setFilters({...initialErpFilters,status:r.failed_scenarios?'FAIL':'ALL'});setTab('Wyniki');}catch(e){setError(errorText(String(e)));}finally{setBusy(false);}}
  function show(value:unknown){setSelected(value);dialog.current?.showModal();}
  async function download(format:'json'|'csv'){if(!report)return;try{const r=await fetch(`${root}/runs/${report.run_id}/report?format=${format}`);if(!r.ok)throw new Error('Błąd eksportu');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`erp-acceptance.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(errorText(String(e)));}}
  const mode=report?.artifacts.configuration??'baseline';const visible=filterErp(report?.artifacts.scenarios??[],filters);
  return <main><section className="shell tool-intro workflow-intro"><Link className="back" to={homePath}>{t('s084694e0b7e7')}</Link><div className="eyebrow">{t('s2b3e6f59e1b3')}</div><p className="wf-trust">{t('s5ceffcb0c3a2')}</p><h1>{t('s526916526f65')}</h1><p className="lab-standards">{t('sa4acc3678bfe')}</p><p><strong>{t('sc14c246310c9')}</strong>{t('sf7dbc0974e5c')}</p><p className="lab-boundary">{t('se503d4e0681f')}</p></section>
  <section className="shell pipeline five">{[['Wejście','SYSTEM A: klient, produkty i wersjonowane pozycje zamówień.'],['Jak działa kontrola','Mapowanie → walidacja → stan transakcji → idempotencja i wersje.'],['Co system wykrywa','Brak mapowania, konflikt wersji, częściowy zapis, timeout.'],['Co otrzymujesz','Historia, kolejka wyjątków, uzgodnienie i raport JSON/CSV.'],['Jak odbierany jest wynik','Oczekiwane decyzje i stan celu zgadzają się z wynikiem.']].map(([h,p])=><article key={h}><b>{label(h)}</b><p>{label(p)}</p></article>)}</section>
  <section className="workspace shell lab-workspace"><VerificationGuide/><div className="workspace-top"><div><span className="kicker">{t('s22b3ec839262')}</span><h2>{t('s53d2b71b5872')}</h2><p>{t('sf0a3715d79c3')}</p></div><div className="workspace-actions"><button className="button primary" disabled={busy} onClick={()=>void run('/run',{data:{configuration:'baseline'}})}>{t('scb875025fd10')}</button><button className="button secondary" disabled={busy} onClick={()=>void run('/regression/inject')}>{t('s87604711bada')}</button><button disabled={busy} onClick={()=>void run('/regression/reset')}>{t('s515a0ab1d2aa')}</button></div></div>
  <div className="wf-note" data-testid="erp-mode"><strong>{mode==='controlled'?t('s298e1308fdc9'):mode==='recovered'?t('s346b870752ff'):t('s40affbabe284')}</strong><p>{mode==='controlled'?t('sd6ee92426713'):mode==='recovered'?t('s18d315361b81'):t('sbb7a1d08d70a')}</p></div>
  {busy&&<p role="status">{t('s3df58748ca62')}</p>}{error&&<p role="alert">{error}</p>}
  <h3>{t('s34c34a5f83a5')}</h3><p>{t('sf90b38090620')}</p><nav className="lab-tabs" aria-label={t('s6ab76d571cf9')}>{['Wejście','Wyniki','Mapowanie','Synchronizacja','Wyjątki','Uzgodnienie','Raport','Architektura'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{label(t)}</button>)}</nav>{!report&&["Synchronizacja","Wyjątki","Uzgodnienie","Raport"].includes(tab)&&<div className="empty-state"><h3>{t('sc80320394f65')}</h3><p>{t('s7c2891283548')}</p></div>}
  {tab==='Wejście'&&<><h3>{t('s85938690d69b')}</h3><p>{t('s8d281c273a19')}</p><p>{t('sd2061b4e5faf')}</p><a href="/lab-api/erp-sync/fixtures">{t('sd1274121b2a1')}</a>{report&&<EvidenceView value={{source:report.artifacts.source,entities:report.artifacts.entities}}/>}</>}
  {tab==='Wyniki'&&<>{report?<><ErpSummary report={report}/><div className="lab-toolbar">{([['status','Wynik testu',['ALL','PASS','FAIL']],['entity','Encja',['ALL','Customer','OrderLine']],['rule','Typ reguły',['ALL','entity','sync','mapping','idempotency','version','reference','retry','validation','reconciliation']],['severity','Priorytet',['ALL','high']]] as [keyof typeof filters,string,string[]][]).map(([key,caption,values])=><label key={key}>{label(caption)}<select aria-label={label(caption)} value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}>{values.map(v=><option key={v} value={v}>{enumText(v)}</option>)}</select></label>)}<input aria-label={t('se9b8e2de874d')} placeholder={t('s5a9efff9611a')} value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><span>{counted(visible.length,['pozycja','pozycje','pozycji'])}</span></div><ErpTable rows={visible} onEvidence={show}/></>:<p>{t('s330d66c5979f')}</p>}</>}
  {tab==='Mapowanie'&&<><h3>{t('s86505aaee3e8')}</h3>{report?<ErpMappings report={report} onEvidence={show}/>:<p>{t('sfa74adc496e2')}</p>}</>}
  {tab==='Synchronizacja'&&report&&<><h3>{t('s2f79d514fd76')}</h3><p>{report.run_id} · {report.timestamp}{t('se09d1977ad14')}</p><p>{t('s5cd8c21cdda2')}{report.created}{t('s4b744ecdff15')}{report.updated}{t('sdbf60ebdc234')}{report.no_op}{t('s2f0cbda72b0c')}{report.rejected}{t('sb155394ecba7')}{report.retried}</p><p>{t('s1543b31cf70d')}</p><div className="table-scroll"><table><thead><tr><th>#</th><th>{t('s2895913462f1')}</th><th>{t('sdb9afaa29fef')}</th><th>{t('s1c45911567c2')}</th></tr></thead><tbody>{report.artifacts.history.map((h,i)=><tr key={i}><td>{i+1}</td><td>{h.event_id}</td><td>{valueText(h.result)}</td><td><button onClick={()=>show(h)}>{t('s8dc7cb9eea1f')}</button></td></tr>)}</tbody></table></div></>}
  {tab==='Wyjątki'&&report&&<><h3>{t('s010a1f7755d0')}</h3><p>{t('seb782cd28da3')}</p><div className="table-scroll"><table><thead><tr><th>{t('s0a0d422c519e')}</th><th>{t('s186ee93735bb')}</th><th>{t('s942087cc2d41')}</th><th>{t('s920e413c7d41')}</th><th>{t('s5fe4f73e5e0b')}</th></tr></thead><tbody>{report.artifacts.exceptions.map(e=><tr key={e.event_id} data-testid="erp-exception"><td>{t('sd484891f0c72')}<br/>{e.input.external_id}</td><td>{e.rule}<br/>{e.severity}</td><td>{e.retryable?t('s6df1b5eca850'):t('sc38811a58a4b')}</td><td>{e.status}</td><td><button onClick={()=>show(e)}>{t('s85072bd712ac')}</button><button disabled={busy||!e.retryable} onClick={()=>void run('/retry/'+encodeURIComponent(e.event_id),{run_id:report.run_id})}>{t('s3a336f8b63af')}</button><button disabled={busy||!e.retryable} onClick={()=>void run('/retry/'+encodeURIComponent(e.event_id),{run_id:report.run_id,repair_mapping:true})}>{t('s627b18bf5d81')}</button></td></tr>)}</tbody></table></div>{!report.exceptions&&<p>{t('s7ea55caf9dd4')}</p>}</>}
  {tab==='Uzgodnienie'&&report&&<><h3>{t('s473ac8083cc0')}</h3><p>{t('s646672acdd5f')}</p><div className="table-scroll"><table><thead><tr><th>{t('s685f3bc5f7e2')}</th><th>{t('s32a09089e438')}</th><th>{t('s920e413c7d41')}</th><th>{t('s2b7eb54d460d')}</th><th>{t('s1c45911567c2')}</th></tr></thead><tbody>{report.artifacts.reconciliation.map((r,i)=><tr key={i} data-testid="erp-reconciliation"><td>{r.source_id??'—'}</td><td>{r.target_id??'—'}</td><td className={r.status==='MATCH'?'wf-pass':'wf-fail'}>{valueText(r.status)}</td><td>{Object.keys(r.differences).join(', ')||'—'}</td><td><button onClick={()=>show(r)}>{t('s0f4c1f331974')}</button></td></tr>)}</tbody></table></div></>}
  {tab==='Raport'&&report&&<><h3>{t('s9567867ae77b')}</h3><ErpSummary report={report}/><dl className="wf-report"><dt>{t('s26d3e7aaace4')}</dt><dd>{report.run_id}</dd><dt>{t('s786c3b1234b9')}</dt><dd>{report.timestamp}</dd><dt>{t('s73373981642c')}</dt><dd>{report.ruleset}</dd><dt>{t('sbbd07c4fc02c')}</dt><dd>{report.input_sha256}</dd><dt>{t('sb36498dc77b3')}</dt><dd>{report.source_records} / {report.target_records}</dd></dl><div className="workspace-actions"><button onClick={()=>void download('json')}>{t('s4dc00251c5cd')}</button><button onClick={()=>void download('csv')}>{t('s319b3b37a03d')}</button></div><p>{t('s7577e17b5510')}</p><EvidenceView value={report}/></>}
  {tab==='Architektura'&&<><h3>{t('s0fd81c2fa1c6')}</h3><p>{t('see025bbdf2bd')}</p><p>{t('s713bb93a1c0b')}</p><a href="/lab-api/docs" target="_blank" rel="noreferrer">{t('s59ac6a3d93c2')}</a></>}
  </section><section className="shell section"><h2>{t('see04c89ef492')}</h2><p>{t('s24322c20ae82')}</p><h3>{t('s5756755bb8ed')}</h3><p>{t('s1ea6bcf7e6ca')}</p><h3>{t('sddc798a1a631')}</h3><p>{t('s15c563b04a04')}</p><p>{t('s7a236efd1504')}</p><a className="button primary" href={contact}>{t('s33602450032d')}</a></section><dialog ref={dialog} className="issue-dialog" onClose={()=>setSelected(null)}><button className="dialog-close" aria-label={t('sb56e1e647517')} onClick={()=>dialog.current?.close()}>{t('s8db71ed28b0f')}</button><h2>{t('s8201801a1d92')}</h2><EvidenceView value={selected}/></dialog></main>;
}
