import {useDomainValue} from './domain-copy';
import {useDomainText} from './domain-copy';
import { useProofText } from './proof-copy';
import { useCounted } from './localized-count';
import type {HealthcareInterface,HealthcareReference,HealthcareReport,HealthcareScenario} from './healthcare-model';
export function HealthcareSummary({report}:{report:HealthcareReport}){ const counted=useCounted();  const t = useProofText(); return <div className="exception-value"><div><span>{t('sba37f6e51f26')}</span><strong data-testid="healthcare-overall">{report.overall_status}</strong></div><p>{counted(report.scenario_count,['scenariusz','scenariusze','scenariuszy'])}{t('sb91423be1bcc')}{report.passed_scenarios}{t('s6d489b84dedb')}{report.failed_scenarios}<br/>{counted(report.discrepancy_count,['rozbieżność','rozbieżności','rozbieżności'])}{t('sd1c216eebcdd')}{report.interfaces_tested}{t('s2e522172b1de')}{report.resources_processed}</p></div>;}
export function HealthcareTable({rows,onEvidence,onRerun}:{rows:HealthcareScenario[];onEvidence:(r:HealthcareScenario)=>void;onRerun:(id:string)=>void}){ const valueText=useDomainValue();  const domain=useDomainText();  const t = useProofText(); return <div className="table-scroll"><table><thead><tr><th>{t('sdd4b9f2b401e')}</th><th>{t('scb82f379942e')}</th><th>{t('s644855ad595f')}</th><th>{t('s60e6a5fcc71f')}</th><th>{t('s8e3c252723fc')}</th><th>{t('s1c45911567c2')}</th></tr></thead><tbody>{rows.map(r=><tr key={r.scenario_id} data-testid="healthcare-row"><td><strong>{domain(r.name)}</strong><br/><code>{r.scenario_id}</code><br/><small>{r.actual_rules.join(', ')||t('s2446f9962d0e')} · {valueText(r.severity)}</small></td><td>{r.interface}<br/>{r.resource_type}/{r.resource_id??'—'}</td><td>{r.expected}{t('s1e1be4354ebf')}{r.expected_http}<br/>{r.expected_rules.join(', ')||t('s942074b45ffd')}</td><td>{r.actual}{t('s1e1be4354ebf')}{r.actual_http}<br/><small>{t('s866bf1a63cd3')}{r.validation}</small>{r.issues.map((i,n)=><p key={n}>{valueText(i.actual)}</p>)}</td><td><strong className={r.result==='FAIL'?'wf-fail':'wf-pass'}>{r.result}</strong></td><td><button onClick={()=>onEvidence(r)}>{t('s1c45911567c2')}</button><button onClick={()=>onRerun(r.scenario_id)}>{t('sbe39b2ec63f9')}</button></td></tr>)}</tbody></table>{!rows.length&&<p>{t('s9a34ce7b6b27')}</p>}</div>;}
export function InterfaceMatrix({interfaces,onSelect}:{interfaces:HealthcareInterface[];onSelect:(i:HealthcareInterface)=>void}){ const t = useProofText(); return <div className="table-scroll"><table><caption>{t('sebda55e1704b')}</caption><thead><tr><th>{t('see8c0630b6d8')}</th><th>{t('s808c293d6b71')}</th><th>{t('sf7afd73ebe8b')}</th><th>{t('sfa2460b70c93')}</th><th>{t('s920e413c7d41')}</th><th>{t('s1c45911567c2')}</th></tr></thead><tbody>{interfaces.map(i=><tr key={i.id}><td>{i.id}</td><td>{i.source} → {i.target}</td><td>{i.resource}</td><td>{i.direction}{t('s40212a8065e6')}{i.expected_http}{t('s00bda6f12c7d')}{i.reject_http}<br/>{i.required_fields.length}{t('s0e65a1e1e214')}</td><td>{i.result}</td><td><button aria-label={`${t('sfa2460b70c93')} ${i.resource}`} onClick={()=>onSelect(i)}>{t('s98d215cfca48')}</button></td></tr>)}</tbody></table></div>;}
export function ReferenceGraph({edges,onSelect}:{edges:HealthcareReference[];onSelect:(e:HealthcareReference)=>void}){ const t = useProofText(); return <div className="table-scroll"><table><caption>{t('sa678fe497279')}</caption><thead><tr><th>{t('s94e2e1623946')}</th><th>{t('s593fab4e3859')}</th><th>{t('s49b85413ae88')}</th><th>{t('saf226c865440')}</th><th>{t('s1c45911567c2')}</th></tr></thead><tbody>{edges.map((e,i)=><tr key={i} data-testid="reference-edge" className={e.status==='FAIL'?'wf-denied':''}><td>{e.source}</td><td>{e.field} →</td><td>{e.reference}</td><td><strong className={e.status==='FAIL'?'wf-fail':'wf-pass'}>{e.resolved_target?t('s565339bc4d33'):t('s7d663cfa265e')}</strong><br/>{t('sbb37ce0d1a83')}{e.expected_target}</td><td><button onClick={()=>onSelect(e)}>{t('sdb6dcd9972cd')}</button></td></tr>)}</tbody></table></div>;}
