export type HealthcareIssue={rule:string;expected:string;actual:string;severity:string;evidence:Record<string,unknown>};
export type HealthcareScenario={scenario_id:string;name:string;interface:string;resource_type:string;resource_id:string|null;input:string;preconditions:string;expected:string;actual:string;expected_http:number;actual_http:number;expected_rules:string[];actual_rules:string[];severity:string;rule_type:string;result:string;validation:string;issues:HealthcareIssue[];evidence:Record<string,unknown>};
export type HealthcareInterface={id:string;source:string;target:string;resource:string;direction:string;required_fields:string[];reference_rules:{field:string;target:string}[];status_rules:string[];expected_http:number;reject_http:number;ruleset:string;result:string;scenario_count:number;example_payload:Record<string,unknown>|null};
export type HealthcareReference={source:string;field:string;reference:string;expected_target:string;resolved_target:string|null;status:string};
export type HealthcareInput={resources:Record<string,unknown>[];scenarios:Record<string,unknown>[]};
export type HealthcareReport={run_id:string;timestamp:string;ruleset:string;input_sha256:string;interfaces_tested:number;resources_processed:number;scenario_count:number;passed_scenarios:number;failed_scenarios:number;discrepancy_count:number;overall_status:string;artifacts:{scenarios:HealthcareScenario[];interfaces:HealthcareInterface[];references:HealthcareReference[];configuration:'baseline'|'controlled'|'custom';input:HealthcareInput;change:Record<string,unknown>|null}};
export type HealthcareFilters={status:string;severity:string;resource:string;rule:string;search:string};
export const initialHealthcareFilters:HealthcareFilters={status:'ALL',severity:'ALL',resource:'ALL',rule:'ALL',search:''};
export function filterHealthcare(rows:HealthcareScenario[],f:HealthcareFilters){return rows.filter(r=>(f.status==='ALL'||r.result===f.status)&&(f.severity==='ALL'||r.severity===f.severity)&&(f.resource==='ALL'||r.resource_type===f.resource)&&(f.rule==='ALL'||r.actual_rules.some(rule=>rule.startsWith(f.rule+'.'))||(f.rule==='contract'&&!r.actual_rules.length))&&JSON.stringify(r).toLocaleLowerCase('pl').includes(f.search.toLocaleLowerCase('pl')));}
