import {useContactHref} from './contact-copy';
import {useErrorText} from './error-copy';
import {useDomainValue} from './domain-copy';
import { useLocale, localizedPath } from './locale';
import { useProofLabel } from './proof-labels';
import { useProofText } from './proof-copy';
import VerificationGuide from './VerificationGuide';
import SupplementPack from './SupplementPack';
import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {EvidenceView} from './WorkflowViews';
import {HealthcareSummary,HealthcareTable,InterfaceMatrix,ReferenceGraph} from './HealthcareViews';
import {filterHealthcare,initialHealthcareFilters,type HealthcareInput,type HealthcareReport} from './healthcare-model';
import { useCounted } from './localized-count';

const root='/lab-api/healthcare-integration';
async function api<T>(path:string,data?:unknown):Promise<T>{const response=await fetch(root+path,data===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!response.ok)throw new Error(`HTTP ${response.status}: ${(await response.text()).slice(0,500)}`);return response.json() as Promise<T>;}
export default function HealthcarePage(){ const contact=useContactHref(); const errorText=useErrorText();  const enumText=useDomainValue();  const counted=useCounted();  const homePath=localizedPath('/',useLocale()); const t = useProofText(); const label = useProofLabel();
  const [input,setInput]=useState('');const [report,setReport]=useState<HealthcareReport|null>(null);const [tab,setTab]=useState('Wyniki');const [filters,setFilters]=useState(initialHealthcareFilters);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [selected,setSelected]=useState<unknown>(null);const [rerunResult,setRerunResult]=useState('');const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{let active=true;api<HealthcareInput>('/fixtures').then(data=>{if(active)setInput(JSON.stringify(data,null,2));}).catch(()=>{if(active)setError(errorText('Nie można pobrać danych API. Spróbuj ponownie za chwilę.'));});return()=>{active=false;};},[]);
  async function run(mode:'baseline'|'inject'|'reset'|'current'){
    setBusy(true);setError('');setRerunResult('');
    try{const path={baseline:'/scenarios/run',inject:'/regression/inject',reset:'/regression/reset',current:'/validate'}[mode];const r=await api<HealthcareReport>(path,mode==='current'?{data:JSON.parse(input)}:{});setReport(r);setInput(JSON.stringify(r.artifacts.input,null,2));setFilters({...initialHealthcareFilters,status:mode==='inject'?'FAIL':'ALL'});setTab('Wyniki');}
    catch(e){setError(errorText(e instanceof Error?e.message:'Błąd wykonania'));}finally{setBusy(false);}
  }
  function show(value:unknown){setSelected(value);dialog.current?.showModal();}
  async function rerun(id:string){if(!report||busy)return;setBusy(true);setError('');try{const data={...report.artifacts.input,scenarios:report.artifacts.input.scenarios.filter(s=>s.scenario_id===id)};const r=await api<HealthcareReport>('/validate',{data});setRerunResult(`${id}: ${r.overall_status} · ${r.run_id}`);show(r.artifacts.scenarios[0]);}catch(e){setError(errorText(String(e)));}finally{setBusy(false);}}
  async function download(format:'json'|'csv'){if(!report)return;try{const r=await fetch(`${root}/runs/${report.run_id}/report?format=${format}`);if(!r.ok)throw new Error('Nie można pobrać raportu');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=`healthcare-acceptance.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(errorText(String(e)));}}
  const rows=report?.artifacts.scenarios??[];const visible=filterHealthcare(rows,filters);const mode=report?.artifacts.configuration??'baseline';
  return <main>
    <section className="shell tool-intro workflow-intro"><Link className="back" to={homePath}>{t('s084694e0b7e7')}</Link><div className="eyebrow">{t('s2b3e6f59e1b3')}</div><p className="wf-trust">{t('s5ceffcb0c3a2')}</p><h1>{t('s3c38044f0f92')}</h1><p className="lab-standards">{t('sa031105d9714')}</p><p><strong>{t('sc14c246310c9')}</strong>{t('s2cbaf756b5e5')}</p><p className="lab-boundary">{t('s016586cea7ba')}</p></section>
    <section className="shell pipeline five">{[['Wejście','Syntetyczne zasoby Patient, Organization, Encounter, Observation, Appointment, ServiceRequest.'],['Jak działa kontrola','Kontrakt → typowane zasoby → referencje → scenariusze expected/actual.'],['Co system wykrywa','Brak identyfikatora lub referencji, status, timestamp, niespójny subject i odpowiedź HTTP.'],['Co otrzymujesz','Macierz interfejsów, graf referencji, dowody i raport JSON/CSV.'],['Jak odbierany jest wynik','Uzgodnione decyzje, reguły i odpowiedzi dają oczekiwane wyniki testów.']].map(([h,p])=><article key={h}><b>{label(h)}</b><p>{label(p)}</p></article>)}</section>
    <section className="workspace shell lab-workspace"><VerificationGuide/><div className="workspace-top"><div><span className="kicker">{t('sda1570d7872f')}</span><h2>{t('sd31af686dcf3')}</h2><p>{t('sacda1133a672')}</p></div><div className="workspace-actions"><button className="button primary" disabled={busy||!input} onClick={()=>void run('baseline')}>{t('scb875025fd10')}</button><button className="button secondary" disabled={busy||!input} onClick={()=>void run('inject')}>{t('s87604711bada')}</button><button disabled={busy||!input} onClick={()=>void run('reset')}>{t('s515a0ab1d2aa')}</button></div></div>
      <div className="wf-note" data-testid="healthcare-mode"><strong>{mode==='controlled'?t('s298e1308fdc9'):mode==='custom'?t('s27642a09dd05'):t('s40affbabe284')}</strong><p>{mode==='controlled'?t('s7fe0ac4f931b'):mode==='custom'?t('s327201850c96'):t('s245b2d3202fe')}</p></div>
      {busy&&<p role="status">{t('s09a7c037e6e6')}</p>}{error&&<p role="alert" className="error">{error}</p>}{rerunResult&&<p role="status">{t('se5d8c12364f8')}{rerunResult}</p>}
      <h3>{t('s34c34a5f83a5')}</h3><p>{t('sf90b38090620')}</p><nav className="lab-tabs" aria-label={t('s1a373329acf7')}>{['Wejście','Wyniki','Scenariusze','Interfejsy','Referencje','Raport','Architektura'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{label(t)}</button>)}</nav>{!report&&["Referencje"].includes(tab)&&<div className="empty-state"><h3>{t('sc80320394f65')}</h3><p>{t('s7c2891283548')}</p></div>}
      {tab==='Wejście'&&<><h3>{t('s9ba3db9f924b')}</h3><p>{t('sde8361148bbc')}</p><label>{t('s38c46cf1fa3c')}<textarea aria-label={t('sd9be1ac31a7a')} value={input} onChange={e=>setInput(e.target.value)} spellCheck={false}/></label><button disabled={busy} onClick={()=>void run('current')}>{t('s9130834c7a8d')}</button></>}
      {(tab==='Wyniki'||tab==='Scenariusze')&&<>{report?<><HealthcareSummary report={report}/><div className="lab-toolbar"><label>{t('s7086a774899a')}<select aria-label={t('s8e3c252723fc')} value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}>{['ALL','PASS','FAIL'].map(v=><option key={v} value={v}>{enumText(v)}</option>)}</select></label><label>{t('se22538e7e0d8')}<select aria-label={t('s89107103b539')} value={filters.severity} onChange={e=>setFilters({...filters,severity:e.target.value})}>{['ALL','high','warning'].map(v=><option key={v} value={v}>{enumText(v)}</option>)}</select></label><label>{t('s5288cbfe0b44')}<select aria-label={t('s376cccfe208b')} value={filters.resource} onChange={e=>setFilters({...filters,resource:e.target.value})}>{['ALL','Patient','Organization','Encounter','Observation','Appointment','ServiceRequest'].map(v=><option key={v} value={v}>{enumText(v)}</option>)}</select></label><label>{t('sddd0169ca141')}<select aria-label={t('s505a47457d3e')} value={filters.rule} onChange={e=>setFilters({...filters,rule:e.target.value})}>{['ALL','contract','reference','identifier','payload','transport'].map(v=><option key={v} value={v}>{enumText(v)}</option>)}</select></label><input aria-label={t('se9b8e2de874d')} placeholder={t('s604956ce2fbf')} value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><span>{counted(visible.length,['pozycja','pozycje','pozycji'])}</span></div><HealthcareTable rows={visible} onEvidence={show} onRerun={id=>void rerun(id)}/></>:<p>{t('s12ee21f90daa')}</p>}</>}
      {tab==='Interfejsy'&&<><h3>{t('s20630a1f0933')}</h3><p>{t('s75ebfd00d20e')}</p>{report?<InterfaceMatrix interfaces={report.artifacts.interfaces} onSelect={show}/>:<p>{t('sfa74adc496e2')}</p>}</>}
      {tab==='Referencje'&&<><h3>{t('s86c1d658dccd')}</h3><p>{t('scf788066b329')}</p>{report&&<>{report.artifacts.change&&<div className="wf-note"><strong>{t('secc49113c5b5')}</strong><p>{t('sea2661942aa4')}</p><button onClick={()=>show(report.artifacts.change)}>{t('se80d99e1c35b')}</button></div>}<ReferenceGraph edges={report.artifacts.references} onSelect={show}/></>}</>}
      {tab==='Raport'&&<>{report?<><h3>{t('s9567867ae77b')}</h3><HealthcareSummary report={report}/><dl className="wf-report"><dt>{t('s26d3e7aaace4')}</dt><dd>{report.run_id}</dd><dt>{t('s350b978d013e')}</dt><dd>{report.timestamp}{t('sf75a067fcae6')}</dd><dt>{t('s73373981642c')}</dt><dd>{report.ruleset}</dd><dt>{t('s8dafcc5148a1')}</dt><dd>{report.input_sha256}</dd></dl><div className="workspace-actions"><button onClick={()=>void download('json')}>{t('s4dc00251c5cd')}</button><button onClick={()=>void download('csv')}>{t('s319b3b37a03d')}</button></div><p>{t('s8dbdff20174e')}</p><EvidenceView value={report}/></>:<p>{t('sfa74adc496e2')}</p>}</>}
      {tab==='Architektura'&&<><h3>{t('s95b91787025a')}</h3><p>{t('s26796e044498')}</p><p>{t('s4b7701b252dd')}</p><a href="/lab-api/docs" target="_blank" rel="noreferrer">{t('s59ac6a3d93c2')}</a></>}
    </section>
    <section className="shell section"><h2>{t('see04c89ef492')}</h2><p>{t('s82c6435cd329')}</p><h3>{t('s5756755bb8ed')}</h3><p>{t('sec4186b865ef')}</p><h3>{t('sddc798a1a631')}</h3><p>{t('s42f4b28e04c6')}</p><p>{t('s917eeed6a4bc')}</p><p>{t('sd12758e6d520')}</p><a className="button primary" href={contact}>{t('s33602450032d')}</a></section>
    <dialog ref={dialog} className="issue-dialog" onClose={()=>setSelected(null)}><button className="dialog-close" aria-label={t('sb56e1e647517')} onClick={()=>dialog.current?.close()}>{t('s8db71ed28b0f')}</button><h2>{t('s943ff1ee7376')}</h2><EvidenceView value={selected}/></dialog>
  <SupplementPack kind="healthcare"/></main>;
}
