import {defineCopy} from './localization-contract';
export const homeJourney=defineCopy('home-journey',{
 en:{noCall:'No introductory call required. Start with a written description.',start:'How we start',steps:[['Describe the problem','Tell me what happens today and what you would like to improve.'],['I review the task','I check the available materials, clarify open questions and identify what is needed to start.'],['I suggest a practical next step','We agree a bounded task, its result, price and timing before paid work.'],['I build, test and hand over','I show progress, check the result against our agreement and hand over the code with setup instructions.']],reviewLimit:'The initial review checks fit and the next step. A detailed audit, architecture or prototype is a separate agreed scope.',about:'Work directly with me',bio:'I am Ivan Matiushkin, an independent specialist in Poland working remotely. I build custom software, internal tools and automations for specific business problems. You work directly with me, from written requirements to handover.',terms:'Agreements and payment',billing:'We agree scope, price, timing, ownership and support before work begins. Contracts and payments can be handled through Useme where applicable; Useme is an intermediary, not my company.',more:'Explore the automation demonstration',technical:'Technical examples and practical guides',proof:'What you can verify',limits:'Demonstration limits',proofs:[['Check a transfer before relying on the new system','A team needs to move records without overlooking missing or rejected data.','Load a sample, correct an error, replay failed records and compare source and target.','Uses synthetic data and a controlled target, not a live ERP migration.'],['Understand why revenue reports disagree','Historical exports and current records overlap or show different totals.','Inspect calculation rules, exclusions and source records; correct a mapping and reconcile again.','Uses synthetic EUR records, with no currency conversion or client financial data.']],other:'Something else',otherTitle:'Describe your situation in your own words',otherBody:'You do not need to choose a technology or know the solution. I will check whether I can help and what we need to clarify.',details:'Optional details',privacyMetrics:'Statistics count page views, contact clicks, form views, starts, sending errors and backend-accepted enquiries in aggregate. They contain no message text, email addresses, file contents or visitor identifiers. No analytics cookies are used. Source attribution is not yet linked to enquiries.'},
 pl:{noCall:'Nie musisz umawiać rozmowy. Zacznij od krótkiego opisu.',start:'Jak zaczynamy',steps:[['Opisz problem','Napisz, jak wygląda praca dziś i co chcesz usprawnić.'],['Sprawdzam zadanie','Przeglądam dostępne materiały, wyjaśniam otwarte kwestie i określam, czego potrzebuję do rozpoczęcia.'],['Proponuję konkretny następny krok','Przed płatną pracą uzgadniamy mały zakres, wynik, cenę i termin.'],['Realizuję, testuję i przekazuję','Pokazuję postępy, sprawdzam wynik według naszych ustaleń i przekazuję kod z instrukcją uruchomienia.']],reviewLimit:'Wstępna ocena dotyczy dopasowania zadania i następnego kroku. Szczegółowy audyt, architektura lub prototyp wymagają osobnego uzgodnienia.',about:'Współpracujesz bezpośrednio ze mną',bio:'Nazywam się Ivan Matiushkin. Jestem niezależnym specjalistą w Polsce i pracuję zdalnie. Tworzę oprogramowanie na zamówienie, narzędzia wewnętrzne i automatyzacje dla konkretnych problemów firmy. Współpracujesz ze mną bezpośrednio — od pisemnych ustaleń do przekazania rozwiązania.',terms:'Ustalenia i rozliczenie',billing:'Przed pracą uzgadniamy zakres, cenę, termin, własność i wsparcie. Umowę i rozliczenie można obsłużyć przez Useme tam, gdzie ma to zastosowanie; Useme jest pośrednikiem, nie moją firmą.',more:'Sprawdź demonstrację automatyzacji',technical:'Przykłady techniczne i praktyczne poradniki',proof:'Co możesz sprawdzić',limits:'Ograniczenia demonstracji',proofs:[['Sprawdź przeniesione dane przed zmianą systemu','Zespół musi przenieść rekordy bez przeoczenia braków i odrzuconych danych.','Wczytaj próbkę, popraw błąd, ponów tylko nieudane rekordy i porównaj źródło z celem.','Dane syntetyczne i kontrolowany cel, bez migracji rzeczywistego ERP.'],['Wyjaśnij różnice w raportach przychodów','Historyczne eksporty i bieżące rekordy obejmują te same okresy lub pokazują różne sumy.','Sprawdź reguły obliczeń, wyłączenia i rekordy źródłowe; popraw mapowanie i ponownie uzgodnij dane.','Syntetyczne rekordy w EUR, bez przewalutowania i danych finansowych klientów.']],other:'Inny problem',otherTitle:'Opisz sytuację własnymi słowami',otherBody:'Nie musisz wybierać technologii ani znać rozwiązania. Sprawdzę, czy mogę pomóc i co trzeba wyjaśnić.',details:'Dodatkowe informacje — opcjonalnie',privacyMetrics:'Statystyki obejmują zbiorcze liczby odsłon, kliknięć kontaktu, wyświetleń formularza, rozpoczęć, błędów wysyłki i zapytań przyjętych przez serwer. Nie zawierają treści wiadomości, adresów e-mail, zawartości plików ani identyfikatorów odwiedzających. Bez analitycznych cookies. Źródło wizyty nie jest jeszcze powiązane z zapytaniem.'}
});

export const homeWorkflow=defineCopy('home-workflow',{
 en:{title:'How I work with AI',body:'I use Codex to analyse existing code, implement changes and prepare tests. I have worked with AI tools for over three years, including around two years with Codex.',checks:'We agree the scope and acceptance criteria before work starts. I review the changes, test the result and hand over the code with clear instructions.'},
 pl:{title:'Jak pracuję z AI',body:'Używam Codex do analizy istniejącego kodu, wprowadzania zmian i przygotowywania testów. Z narzędzi AI korzystam od ponad trzech lat, w tym z Codex od około dwóch lat.',checks:'Przed rozpoczęciem uzgadniamy zakres i kryteria odbioru. Sprawdzam zmiany, testuję wynik i przekazuję kod z jasnymi instrukcjami.'}
});

export const homeGithub=defineCopy('home-github',{
 en:{title:'See the code behind the work',body:'Inspect the implementation, tests and setup instructions. The CRM case shows a focused change to an existing application.',source:'Portfolio source code',crm:'Atomic CRM — contact import review',boundary:'Independent examples with test data. Atomic CRM is by Marmelab; the case study identifies my extension and its limits.',profile:'My GitHub profile'},
 pl:{title:'Zobacz kod i sposób wykonania',body:'Sprawdź implementację, testy i instrukcje uruchomienia. Przykład CRM pokazuje konkretną zmianę w istniejącej aplikacji.',source:'Kod źródłowy portfolio',crm:'Atomic CRM — kontrola importu kontaktów',boundary:'Niezależne przykłady z danymi testowymi. Atomic CRM jest projektem Marmelab; opis wskazuje mój wkład i jego ograniczenia.',profile:'Mój profil GitHub'}
});
