import {homeJourney} from './home-journey-copy';
import {defineCopy} from './localization-contract';
export const inquiryCopy=defineCopy('inquiry',{
 pl:{title:'Opisz zadanie',intro:'Wystarczą 2–3 zdania: jakie systemy używasz, co nie działa i jaki wynik chcesz uzyskać. Nie potrzebujesz gotowej specyfikacji ani rozmowy telefonicznej. Odpowiem e-mailem z pytaniami lub propozycją pierwszego zakresu.',hint:'Na początek wystarczy opis — bez załączników i dostępów. Cena i termin wymagają osobnego uzgodnienia.',placeholder:'Opisz, jak wygląda praca dziś, co nie działa lub co chcesz usprawnić. Nie potrzebujesz specyfikacji technicznej.',name:'Imię lub firma',email:'Twój adres e-mail',service:'Temat',message:'Opis zadania',send:'Wyślij do oceny',sending:'Wysyłanie…',success:'Zapytanie zostało przekazane do wysyłki na mój adres. Zachowaj numer zgłoszenia:',error:'Nie udało się potwierdzić wysyłki. Spróbuj ponownie z tym samym formularzem lub napisz bezpośrednio na ivan@matiushkin.com.',privacy:'Użyję podanych danych tylko do odpowiedzi na zapytanie i uzgodnienia współpracy. Nie wpisuj haseł, danych klientów ani innych informacji poufnych. Wiadomość trafia do mojej skrzynki przez Cloudflare; e-mail obsługuje Google Workspace.',analytics:homeJourney.pl.privacyMetrics,direct:'Możesz też napisać bezpośrednio',policy:'Informacje o danych i statystykach',back:'← Strona główna',other:'Inne zadanie',options:['Integracja API / ERP','Migracja lub uzgodnienie danych','Testy integracyjne','Raport wyjątków','Inne zadanie'],link:'Wyślij przez formularz',additional:'Możesz wysłać przygotowany opis przez formularz lub otworzyć go w swoim programie pocztowym.',request:'Numer zgłoszenia',privacyTitle:'Dane w formularzu i statystyki',privacyBody:'Osobą kontaktową i odpowiedzialną za obsługę zapytań jest Ivan Matiushkin, ivan@matiushkin.com. Formularz wymaga adresu e-mail i opisu zadania; imię lub nazwa firmy są opcjonalne. Dane służą prowadzeniu korespondencji w sprawie zapytania. W sprawie dostępu, poprawienia lub usunięcia swojej korespondencji napisz na ten adres. Techniczne potwierdzenie wysyłki, bez treści i adresu e-mail, jest przechowywane około 24 godzin; zbiorcze statystyki strony około 90 dni. Korespondencja pozostaje w skrzynce na potrzeby obsługi zapytania i ewentualnej współpracy.'},
 en:{title:'Describe your task',intro:'Two or three sentences are enough: which systems you use, what is not working and what result you need. No finished specification or phone call required. I will reply by email with questions or a proposed first scope.',hint:'Start with a description — no attachments or system access needed. Price and timing require a separate agreement.',placeholder:'Tell me what happens today, what is not working or what you would like to improve. No technical specification needed.',name:'Name or company',email:'Your email address',service:'Subject',message:'Task description',send:'Send for review',sending:'Sending…',success:'Your enquiry has been accepted for sending to my inbox. Keep this reference:',error:'Sending could not be confirmed. Retry with the same form or email ivan@matiushkin.com directly.',privacy:'I will use your details only to respond to your enquiry and discuss working together. Do not include passwords, customer data or other confidential information. Cloudflare delivers the message to my inbox, which is hosted by Google Workspace.',analytics:homeJourney.en.privacyMetrics,direct:'You can also email me directly',policy:'About your data and site statistics',back:'← Home',other:'Another task',options:['API / ERP integration','Data migration or reconciliation','Integration testing','Exception reporting','Another task'],link:'Send using the contact form',additional:'Send your prepared description through the contact form or open it in your email application.',request:'Enquiry reference',privacyTitle:'Form data and site statistics',privacyBody:'Ivan Matiushkin handles enquiries and can be contacted at ivan@matiushkin.com. The form requires your email address and task description; your name or company is optional. Details are used for correspondence about your enquiry. To request access, correction or deletion of your correspondence, write to that address. The technical sending receipt, without message contents or your email address, is kept for about 24 hours; aggregate site statistics for about 90 days. Correspondence remains in the mailbox to handle the enquiry and any subsequent work.'}
});
export const inquiryServices=['api-integration','data-migration','integration-testing','exceptions','other'] as const;
export const inquiryGuidance=defineCopy('inquiry-guidance',{
 pl:{optional:'opcjonalnie',details:'Co warto opisać',next:'Co dalej?',steps:['Odpowiem e-mailem i sprawdzimy, czy mogę pomóc w tym zadaniu.','Ustalimy mały pierwszy zakres, wynik i sposób jego sprawdzenia.','Przed rozpoczęciem pracy osobno uzgodnimy cenę i termin.'],noCommitment:'Zapytanie nie jest zamówieniem płatnej pracy.',prompts:[
 ['Jakie dwa systemy mają wymieniać dane?','Co ma przechodzić między nimi, np. zamówienia lub faktury?','Co dziś trzeba robić ręcznie lub co nie działa?'],
 ['Skąd i dokąd mają trafić dane?','Jakie rekordy lub okres chcesz przenieść albo porównać?','Po czym poznasz, że wynik się zgadza?'],
 ['Jaki przepływ lub endpoint trzeba sprawdzić?','Jaki wynik jest oczekiwany i co obecnie zawodzi?','Czy jest środowisko testowe? Jeśli nie wiesz, napisz to.'],
 ['Jakie dwa zestawienia lub systemy się nie zgadzają?','Które wartości lub rekordy chcesz porównać?','Kto i jak powinien sprawdzać wykryte wyjątki?'],
 ['Co dziś robisz ręcznie lub co nie działa?','W jakich systemach pracujesz?','Jaki konkretny wynik byłby pomocny?']
 ],unknown:'Nie znasz odpowiedzi na wszystko? Opisz tylko to, co już wiesz.'},
 en:{optional:'optional',details:'Useful details',next:'What happens next?',steps:['I will reply by email so we can check whether I can help with the task.','We will define a small first scope, its output and how to check it.','We will agree price and timing separately before work starts.'],noCommitment:'An enquiry does not commit you to paid work.',prompts:[
 ['Which two systems need to exchange data?','What should move between them, such as orders or invoices?','What is manual or not working today?'],
 ['Where are the data coming from and going to?','Which records or period do you need to move or compare?','How will you know the result is correct?'],
 ['Which flow or endpoint needs checking?','What should happen and what currently fails?','Is a test environment available? It is fine if you do not know.'],
 ['Which two reports or systems disagree?','Which values or records need comparing?','Who should review the exceptions and how?'],
 ['What is manual or not working today?','Which systems do you use?','What specific result would help?']
 ],unknown:'You do not need every answer. Start with what you already know.'}
});
