export type LabDefinition = { title: string; problem: string; input: string; result: string; acceptance: string; limits: string; processing: string; failures: string; group: string };
export const labs: Record<string, LabDefinition> = {
  'data-quality': {
    title:'Kontrola jakości danych w potoku',group:'Dane i migracje',
    problem:'Walidacja transformacji, kontraktu danych i regresji między przebiegami z dowodem source-to-target.',
    input:'Syntetyczny eksport transakcji CSV/JSON.',processing:'Ingestion → staging → normalizacja → transformacje → quality → target.',
    failures:'Schemat, typ, referencja, zakres, spójność i błędna transformacja kwoty.',
    result:'Raport jakości, kwarantanna, lineage pola i porównanie przebiegów.',
    acceptance:'Referencja PASS; jedna kontrolowana wada zmienia jedno pole i daje jeden FAIL.',
    limits:'Deterministyczny fragment potoku demonstracyjnego; bez infrastruktury Data Lake i konektorów klientów.',
  },
  'operations-exceptions': {
    title:'Kontrola wyjątków w procesach operacyjnych',group:'Operacje i systemy',
    problem:'Kontrola eksportów zamówień, dokumentów, statusów i terminów z kolejką spraw wymagających działania.',
    input:'Syntetyczne eksporty CSV/JSON z tożsamością pliku i wiersza.',
    processing:'Parser → normalizacja → reguły → cross-check.',
    failures:'Brak dokumentu, status, termin, zapas i niespójne powiązania.',
    result:'Kolejka wyjątków, ślad źródłowy i raport JSON/CSV.',
    acceptance:'Referencja PASS; usunięcie jednego dokumentu daje jeden wyjątek i FAIL.',
    limits:'Kontrolowane eksporty, backend z izolacją sesji; adapter ERP/WMS/B2B jest osobnym zakresem.',
  },
  'erp-sync': {
    title: 'Synchronizacja i walidacja danych między systemami', group: 'Operacje i systemy',
    problem: 'Mapowanie, idempotencja, wyjątki i mierzalny odbiór synchronizacji dwóch syntetycznych systemów.',
    input: 'Klient, produkty i wersjonowane pozycje zamówień.',
    processing: 'Mapowanie → walidacja → stan transakcji → wersje → uzgodnienie.',
    failures: 'Brak mapowania, konflikt wersji, częściowy zapis i timeout.',
    result: 'Historia synchronizacji, dowody wyjątków i raport JSON/CSV.',
    acceptance: 'Referencja PASS; jedna kontrolowana zmiana daje jeden FAIL; naprawa przywraca zgodność.',
    limits: 'Syntetyczne adaptery, transakcje na poziomie pozycji; backend z izolacją sesji, bez konektorów ERP.',
  },
  'healthcare-integration': {
    title: 'Walidacja integracji systemów medycznych', group: 'Integracje i odbiór',
    problem: 'Kontrakty API, referencje zasobów inspirowanych FHIR i powtarzalny pakiet expected/actual z raportem PASS/FAIL.',
    input: 'Syntetyczne zasoby i komunikaty API w uzgodnionym kontrakcie.',
    processing: 'Kontrakt → model zasobów → referencje → scenariusze.',
    failures: 'Brak referencji, duplikat identyfikatora, status, timestamp i niespójność subject.',
    result: 'Macierz interfejsów, dowody i raport JSON/CSV.',
    acceptance: 'Referencja daje PASS; kontrolowana zmiana jednej referencji generuje jedną rozbieżność.',
    limits: 'Podzbiór inspirowany FHIR R4; dane syntetyczne, bez diagnozy i bez certyfikacji zgodności.',
  },
  'workflow-access': {
    title: 'Walidacja uprawnień i workflow', group: 'Integracje i odbiór',
    problem: 'Pakiet testów RBAC, akceptacji i przejść stanów z dowodami expected/actual oraz raportem PASS/FAIL.',
    input: 'Kanoniczny eksport użytkowników, ról, grup i workflow.',
    processing: 'RBAC → przejścia → akceptacje → scenariusze.',
    failures: 'Brak uprawnienia, konflikt ról, niedozwolone przejście i brak wymaganej akceptacji.',
    result: 'Powtarzalny pakiet scenariuszy, dowody i raport JSON/CSV.',
    acceptance: 'Oczekiwane decyzje i reguły są zgodne z wynikiem; kontrolowany nadmiar uprawnienia generuje jedną rozbieżność.',
    limits: 'Syntetyczny model dostępu; bez administracji rzeczywistym katalogiem i bez zapisu do produkcji.',
  },
  'transit-validation': {
    title: 'Walidacja integracji transportowej', group: 'Integracje i odbiór',
    problem: 'Niespójne identyfikatory i nieaktualne dane mogą przejść przez integrację mimo poprawnego transportu HTTP.',
    input: 'GTFS CSV: agency, stops, routes, trips, stop_times, calendar; GTFS-RT JSON lub protobuf base64; podzbiór XML NeTEx i SIRI; jawne mapowania.',
    processing: 'Parsery → kanoniczne przystanki podróży → walidacja plików, relacji i czasu → porównanie formatów.',
    failures: 'Stary feed, nieznany trip, błędna sekwencja, duplikat entity, uszkodzony XML, brak referencji i mapowania.',
    result: 'Raport JSON/CSV: identyfikator przebiegu, hash wejścia, reguła, oczekiwane i rzeczywiste wartości, dowód i wynik odbioru.',
    acceptance: 'Poprawny zestaw testowy nie generuje rozbieżności. Każdy negatywny scenariusz wykrywa przypisaną regułę. Powtórzenie wejścia daje ten sam raport.',
    limits: 'Publiczny scenariusz obejmuje opisany podzbiór NeTEx/SIRI, walidację relacji, mapowań i spójności danych. Profil GTFS wymaga calendar.txt, uporządkowanych stop_times i jawnego mapowania ID. Integracja ze środowiskiem operatora i wymagany profil zgodności są konfigurowane dla danego projektu. Zegar oceny: 2026-09-16 12:00 UTC.',
  },
};
