import {defineCopy} from './localization-contract';
export const guideSlugs=['guides/csv-before-erp-import','guides/verify-data-migration'] as const;
export const migrationGuides=defineCopy('migration-guides',{
 en:{label:'Practical migration guides',service:'Discuss a CSV migration',demo:'Try the working migration example',disclosure:'Independent technical walkthrough using synthetic data. Not a client deployment.',related:'Related guide',offerTitle:'Start with a migration readiness check',offer:'Have a CSV export and a new ERP to populate? Start with one file and one target specification. I check the fields, identifiers, values and mappings, then provide a report of rejected records and the rules needed for a test import.',offerList:['Send a sanitised sample, the target field specification and an approximate row count.','Receive a validation report, proposed field mapping and agreed acceptance checks.','Decide on the test import after reviewing the findings. Production access and cutover are a separate agreed stage.'],articles:[
 {title:'How to check a CSV before importing it into an ERP',description:'A practical CSV validation checklist: identifiers, dates, amounts, duplicates and mappings, illustrated with a runnable synthetic migration.',intro:'A file opening correctly in a spreadsheet does not make it ready for an ERP import. Each source record needs a valid, unambiguous destination. A rejected row must remain identifiable so it can be corrected later.',sections:[
 ['1. Agree what one row represents','Decide whether a row is an order, an order line or another business object. Define a stable source identifier and the fields required by the destination. Preserve identifiers as text when leading zeros matter. Agree the currency, decimal separator and date format instead of guessing them during import.'],
 ['2. Check values before changing them','Check missing fields, malformed dates, invalid amounts and repeated identifiers. A repeated identifier with different contents needs investigation; it should not silently disappear as a duplicate. Keep the original value and the reason for rejection so the correction can be reviewed.'],
 ['3. Treat mappings as a separate check','A well-formed product code may still be unknown to the target system. All six synthetic source rows in the working example pass validation. Removing the SKU-X99 product mapping nevertheless prevents TX-104 and TX-106 from being delivered. Validation and target mapping answer different questions.'],
 ['4. Run a controlled import','Load the built-in sample in Migration Showcase, validate it and review the mapping. Use the guided walkthrough to remove the product mapping and run the migration. Four rows reach the target; two remain as exceptions. Inspect the affected identifiers before correcting the mapping.'],
 ['5. Keep an acceptance checklist','Before a larger run, agree the expected row count, financial control totals, field comparisons and handling of rejected records. Keep the input and mapping version. An exception report should identify the source row, failed rule and next action. The demo exports HTML and JSON evidence after reconciliation.'],
 ['Limits of the example','The demonstration uses six synthetic records and a simulated target. It does not establish performance at your volume or compatibility with a specific ERP. A real scope needs the target specification, permissions and a representative test sample.']]},
 {title:'How to verify that a data migration succeeded',description:'Compare source and target records, reconcile control totals and replay only failed records. A synthetic migration from FAIL to PASS.',intro:'An import job finishing without a crash is only one signal. Acceptance requires evidence that the intended records reached the target with the expected values, and that every difference has been explained.',sections:[
 ['1. Define the comparison before the run','Agree which records belong in scope and how their identifiers match between systems. Compare relevant fields as well as record counts. Equal totals alone can hide offsetting errors; equal counts can hide one missing and one unexpected record.'],
 ['2. Read the failed result','The synthetic source contains six records with a gross control total of PLN 1,534.50. With the SKU-X99 mapping removed, only four reach the target, whose gross total is PLN 250.00. Reconciliation returns FAIL. The missing target records are TX-104 and TX-106.'],
 ['3. Correct configuration without rewriting good records','Restore the missing mapping. This changes the configuration but does not itself deliver the two missing records. The previous four target records remain in place. A corrected setting is not yet evidence of a successful migration.'],
 ['4. Replay only failed records','The failed-only replay selects TX-104 and TX-106, skips TX-101, TX-102, TX-103 and TX-105, and records two new writes. Inspect the attempt history to confirm what was selected and skipped. Then explicitly run reconciliation again.'],
 ['5. Inspect the accepted evidence','The final result is six source records and six target records, with PLN 1,534.50 on each side and all six comparisons matching. Download HTML for review or JSON for machine-readable evidence. Keep the run identifier, input hash, mapping, attempts and per-record comparisons together.'],
 ['6. Interpret PASS within its scope','Here PASS means source and target match under the implemented migration checks. It does not prove every business rule or production requirement. The separate Revenue BI example uses different acceptance rules: explicitly excluded source defects can coexist with reconciliation PASS. Read the definition for the workflow being accepted.']]}
 ]},
 pl:{label:'Praktyczne poradniki migracji',service:'Omów migrację CSV',demo:'Sprawdź działający przykład migracji',disclosure:'Niezależny opis techniczny z danymi syntetycznymi. To nie jest wdrożenie dla klienta.',related:'Powiązany poradnik',offerTitle:'Zacznij od sprawdzenia gotowości danych do migracji',offer:'Masz eksport CSV i nowy ERP do uzupełnienia? Zacznij od jednego pliku i jednej specyfikacji docelowej. Sprawdzę pola, identyfikatory, wartości i mapowania, a następnie przygotuję raport odrzuconych rekordów oraz reguły importu testowego.',offerList:['Prześlij próbkę bez danych poufnych, specyfikację pól docelowych i przybliżoną liczbę wierszy.','Otrzymasz raport walidacji, propozycję mapowania pól i uzgodnione kryteria odbioru.','Po sprawdzeniu wyników zdecydujemy o imporcie testowym. Dostęp produkcyjny i przełączenie systemów to osobno uzgadniany etap.'],articles:[
 {title:'Jak sprawdzić CSV przed importem do ERP',description:'Praktyczna lista kontroli CSV: identyfikatory, daty, kwoty, duplikaty i mapowanie, pokazana na działającej migracji danych syntetycznych.',intro:'To, że plik otwiera się w arkuszu, nie oznacza gotowości do importu do ERP. Każdy rekord potrzebuje poprawnego, jednoznacznego miejsca docelowego. Odrzucony wiersz musi dać się odnaleźć i poprawić.',sections:[
 ['1. Ustal, co oznacza jeden wiersz','Czy wiersz jest zamówieniem, pozycją zamówienia czy innym obiektem? Ustal stały identyfikator źródłowy i pola wymagane przez cel. Zachowaj identyfikatory jako tekst, jeśli początkowe zera mają znaczenie. Uzgodnij walutę, separator dziesiętny i format daty zamiast zgadywać je przy imporcie.'],
 ['2. Sprawdź wartości przed ich zmianą','Sprawdź brakujące pola, niepoprawne daty i kwoty oraz powtarzające się identyfikatory. Ten sam identyfikator z różną treścią wymaga wyjaśnienia; nie powinien znikać jako duplikat. Zachowaj pierwotną wartość i przyczynę odrzucenia, aby można było ocenić poprawkę.'],
 ['3. Osobno sprawdź mapowania','Poprawny kod produktu może być nieznany w systemie docelowym. Wszystkie sześć syntetycznych wierszy przykładu przechodzi walidację. Usunięcie mapowania SKU-X99 mimo to blokuje dostarczenie TX-104 i TX-106. Walidacja i mapowanie odpowiadają na różne pytania.'],
 ['4. Wykonaj import kontrolny','Wczytaj wbudowaną próbkę w Migration Showcase, zweryfikuj ją i sprawdź mapowanie. Przejście z podpowiedziami pozwala usunąć mapowanie produktu i uruchomić migrację. Cztery rekordy trafiają do celu, a dwa pozostają wyjątkami. Sprawdź ich identyfikatory przed poprawieniem mapowania.'],
 ['5. Zachowaj kryteria odbioru','Przed większym przebiegiem uzgodnij liczbę rekordów, sumy kontrolne kwot, porównywane pola i obsługę odrzuceń. Zachowaj wejście i wersję mapowania. Raport wyjątku powinien wskazać wiersz źródłowy, niespełnioną regułę i kolejną czynność. Demonstracja eksportuje dowody HTML i JSON po uzgodnieniu.'],
 ['Ograniczenia przykładu','Demonstracja używa sześciu syntetycznych rekordów i symulowanego celu. Nie potwierdza wydajności przy Twojej skali ani zgodności z konkretnym ERP. Rzeczywisty zakres wymaga specyfikacji celu, uprawnień i reprezentatywnej próbki testowej.']]},
 {title:'Jak sprawdzić, czy migracja danych się powiodła',description:'Porównaj źródło z celem, uzgodnij sumy kontrolne i ponów tylko błędne rekordy. Syntetyczna migracja od FAIL do PASS.',intro:'Zakończenie importu bez awarii to tylko jeden sygnał. Odbiór wymaga dowodów, że właściwe rekordy trafiły do celu z oczekiwanymi wartościami i że każda różnica została wyjaśniona.',sections:[
 ['1. Ustal porównanie przed migracją','Uzgodnij zakres rekordów i sposób łączenia identyfikatorów między systemami. Porównuj istotne pola oraz liczbę rekordów. Równe sumy mogą ukrywać błędy, które się znoszą; równe liczby wierszy mogą maskować rekord brakujący i nadmiarowy.'],
 ['2. Odczytaj wynik nieudanej migracji','Syntetyczne źródło zawiera sześć rekordów z sumą kontrolną brutto 1 534,50 PLN. Po usunięciu mapowania SKU-X99 do celu trafiają tylko cztery, o łącznej kwocie brutto 250,00 PLN. Uzgodnienie zwraca FAIL. Brakujące rekordy docelowe to TX-104 i TX-106.'],
 ['3. Popraw konfigurację bez przepisywania poprawnych rekordów','Przywróć brakujące mapowanie. Zmienia to konfigurację, ale nie dostarcza jeszcze brakujących rekordów. Cztery wcześniej dostarczone rekordy pozostają na miejscu. Poprawione ustawienie nie jest jeszcze dowodem udanej migracji.'],
 ['4. Ponów tylko błędne rekordy','Ponowienie wybiera TX-104 i TX-106, pomija TX-101, TX-102, TX-103 i TX-105 oraz zapisuje dwa nowe rekordy. W historii prób sprawdź wybór i pominięcia. Następnie jawnie uruchom ponowne uzgodnienie.'],
 ['5. Sprawdź dowody odbioru','Wynik końcowy to sześć rekordów źródłowych i sześć docelowych, po 1 534,50 PLN z każdej strony oraz sześć zgodnych porównań. Pobierz HTML do przeglądu albo JSON do dalszego przetwarzania. Zachowaj razem identyfikator przebiegu, skrót wejścia, mapowanie, próby i porównania rekordów.'],
 ['6. Odczytuj PASS w granicach zakresu','Tutaj PASS oznacza zgodność źródła z celem według kontroli migracji. Nie potwierdza każdej reguły biznesowej ani wymagań produkcyjnych. Osobny przykład Revenue BI ma inne reguły odbioru: jawnie pominięte wady źródeł mogą współistnieć z PASS uzgodnienia. Przeczytaj definicję odbieranego procesu.']]}
 ]}
});
