import {ProofBusinessContext,ProofNextStep} from './ProofOutreach';
import {useErrorText} from './error-copy';
import {useDomainValue} from './domain-copy';
import { useLocale, localizedPath } from './locale';
import { useProofLabel } from './proof-labels';
import { useProofText } from './proof-copy';
import VerificationGuide from './VerificationGuide';
import {useEffect,useRef,useState,type ChangeEvent} from 'react';
import {Link} from 'react-router-dom';
import {EvidenceView} from './WorkflowViews';
import {OperationsSummary,OperationsResults,OperationsRules,OperationsQueue,OperationsDocuments,OperationsReportDetails} from './OperationsViews';
import {filterExceptions,opFilters,type OpFile,type OpInput,type OpException,type OpReport} from './operations-model';
const root='/lab-api/operations-exceptions';
const tables=['orders','customers','products','shipments','documents','invoices','quality','imports'];
async function api<T>(path:string,data?:unknown):Promise<T>{const r=await fetch(root+path,data===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error(`HTTP ${r.status}: ${(await r.text()).slice(0,300)}`);return r.json() as Promise<T>;}
export default function OperationsPage(){ const errorText=useErrorText();  const enumText=useDomainValue();  const homePath=localizedPath('/',useLocale()); const t = useProofText(); const label = useProofLabel();
  const [input,setInput]=useState<OpInput|null>(null),[report,setReport]=useState<OpReport|null>(null),[tab,setTab]=useState('Wyniki'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filters,setFilters]=useState(opFilters),[resultFilter,setResultFilter]=useState('ALL'),[search,setSearch]=useState(''),[selected,setSelected]=useState<unknown>(null),[trace,setTrace]=useState<unknown>(null);const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{let active=true;api<OpInput>('/fixtures').then(r=>{if(active)setInput(r);}).catch(e=>{if(active)setError(errorText(String(e)));});return()=>{active=false;};},[]);
  async function run(mode:'baseline'|'inject'|'current'){setBusy(true);setError('');try{const r=await api<OpReport>(mode==='baseline'?'/regression/reset':mode==='inject'?'/regression/inject':'/run',mode==='current'?{data:input}:{});setReport(r);setInput(r.artifacts.input);setResultFilter(r.failed_scenarios?'FAIL':'ALL');setSearch('');setFilters(opFilters);setTrace(null);setTab('Wyniki');}catch(e){setError(errorText(String(e)));}finally{setBusy(false);}}
  function show(value:unknown){setSelected(value);dialog.current?.showModal();}
  async function importFiles(e:ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files??[]);if(!input)return;try{const replacements:OpFile[]=[];for(const file of files){const parts=file.name.toLowerCase().split('.'),format=parts.pop(),table=parts.join('.');if(!tables.includes(table)||(format!=='csv'&&format!=='json'))throw new Error('Nazwa pliku musi wskazywać tabelę, np. orders.csv lub documents.json.');if(file.size>800000)throw new Error('Limit pliku: 800 kB.');replacements.push({name:file.name,table,format,content:await file.text()});}setInput({files:input.files.map(f=>replacements.find(r=>r.table===f.table)??f)});setError('');}catch(err){setError(errorText(String(err)));}e.target.value='';}
  function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function download(format:'csv'|'json'){if(!report)return;try{const r=await fetch(`${root}/runs/${report.run_id}/report?format=${format}`);if(!r.ok)throw new Error('Błąd eksportu');downloadBlob(await r.blob(),`operations-acceptance.${format}`);}catch(e){setError(errorText(String(e)));}}
  async function csvFixture(){try{setInput(await api<OpInput>('/fixtures?format=csv'));setError('');}catch(e){setError(errorText(String(e)));}}
  function source(e:OpException){setTrace({source:e.source,normalized_order:e.evidence.normalized_order,related_source_rows:e.evidence.source_rows,document_lookup:e.evidence.document_lookup});}
  const mode=report?.artifacts.configuration??'baseline';const rows=(report?.artifacts.scenarios??[]).filter(r=>(resultFilter==='ALL'||r.result===resultFilter)&&JSON.stringify(r).toLocaleLowerCase('pl').includes(search.toLocaleLowerCase('pl')));
  return <main><section className="shell tool-intro workflow-intro premium-intro"><Link className="back" to={homePath}>{t('s084694e0b7e7')}</Link><div className="eyebrow">{t('s2b3e6f59e1b3')}</div><p className="wf-trust">{t('sad519059e508')}</p><h1>{t('s7d6f41005e1d')}</h1><ProofBusinessContext example="operations-exceptions" quickStart/><p className="lab-standards">{t('s08ecec0bbd05')}</p><p><strong>{t('sc14c246310c9')}</strong>{t('s245443eebbe4')}</p><p className="lab-boundary">{t('se9e6b9f50ae8')}</p></section>
  <section className="shell pipeline five">{[['Wejście','Eksport danych operacyjnych CSV/JSON.'],['Jak działa kontrola','Parser → normalizacja → reguły → cross-check.'],['Co system wykrywa','Brak dokumentu, niespójny status, termin i zapas.'],['Co otrzymujesz','Kolejka wyjątków, źródło rekordu i raport.'],['Jak odbierany jest wynik','Reguły wykrywają uzgodnione przypadki i dają oczekiwany wynik.']].map(([h,p])=><article key={h}><b>{label(h)}</b><p>{label(p)}</p></article>)}</section>
  <section id="proof-workspace" tabIndex={-1} className="workspace shell lab-workspace"><VerificationGuide/><div className="workspace-top"><div><span className="kicker">{t('s95d36afe0c2a')}</span><h2>{t('s3605a2279a94')}</h2><p>{t('s29202adc12e5')}</p></div><div className="workspace-actions"><button className="button primary" disabled={busy||!input} onClick={()=>void run('baseline')}>{t('scb875025fd10')}</button><button className="button secondary" disabled={busy||!input} onClick={()=>void run('inject')}>{t('s87604711bada')}</button><button disabled={busy||!input} onClick={()=>void run('baseline')}>{t('s515a0ab1d2aa')}</button></div></div>
  <div className="wf-note" data-testid="operations-mode"><strong>{mode==='controlled'?t('s298e1308fdc9'):mode==='imported'?t('sc39dba500679'):t('s40affbabe284')}</strong><p>{mode==='controlled'?t('s44263be01899'):mode==='imported'?t('s9511828baa09'):t('s476eea69fbe1')}</p></div>
  {busy&&<p role="status">{t('s2586211c6b25')}</p>}{error&&<p role="alert">{error}</p>}
  <h3>{t('s34c34a5f83a5')}</h3><p>{t('sf90b38090620')}</p><nav className="lab-tabs" aria-label={t('s3dcea9f1450a')}>{['Wejście','Wyniki','Reguły','Wyjątki','Zamówienia','Dokumenty','Raport','Architektura'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{label(t)}</button>)}</nav>{!report&&["Reguły","Wyjątki","Zamówienia","Dokumenty","Raport"].includes(tab)&&<div className="empty-state"><h3>{t('sc80320394f65')}</h3><p>{t('s7c2891283548')}</p></div>}
  {tab==='Wejście'&&<><h3>{t('s0e634c107515')}</h3><p>{t('sabf5730423bc')}</p><p>{t('se4818b07e456')}{tables.join(', ')}{t('sae33a98f20a2')}</p><label>{t('sc88f2942ff9f')}<input aria-label={t('sc88f2942ff9f')} type="file" multiple accept=".csv,.json" onChange={e=>void importFiles(e)}/></label><div className="workspace-actions"><button disabled={busy||!input} onClick={()=>void csvFixture()}>{t('sc4ecb15e9457')}</button><button disabled={busy||!input} onClick={()=>void run('current')}>{t('scbbc2539b911')}</button></div><div className="table-scroll"><table><thead><tr><th>{t('s5956c3e6d7d4')}</th><th>{t('s5d3015b63d8a')}</th><th>{t('s2f343666aaa8')}</th><th>{t('s1ef599ec6f5f')}</th></tr></thead><tbody>{input?.files.map(f=><tr key={f.table}><td>{f.name}</td><td>{f.table}</td><td>{f.format}</td><td><button onClick={()=>show(f)}>{t('sc4fa51491320')}{f.table}</button><button onClick={()=>downloadBlob(new Blob([f.content],{type:'text/plain;charset=utf-8'}),f.name)}>{t('s5fed611aa257')}{f.name}</button></td></tr>)}</tbody></table></div></>}
  {tab==='Wyniki'&&<>{report?<><OperationsSummary report={report}/><div className="lab-toolbar"><label>{t('s8e3c252723fc')}<select aria-label={t('s8e3c252723fc')} value={resultFilter} onChange={e=>setResultFilter(e.target.value)}>{['ALL','PASS','FAIL'].map(v=><option key={v} value={v}>{enumText(v)}</option>)}</select></label><input aria-label={t('se9b8e2de874d')} value={search} placeholder={t('s8ec936a9bb71')} onChange={e=>setSearch(e.target.value)}/></div><OperationsResults rows={rows} show={show}/></>:<p>{t('s57b487a3c5b5')}</p>}</>}
  {tab==='Reguły'&&report&&<><h3>{t('s1df9ac97fd39')}</h3><p>{t('sd341e4eb265a')}</p><OperationsRules rules={report.artifacts.rules}/></>}
  {tab==='Wyjątki'&&report&&<><h3>{t('sb8856b1f0afc')}</h3><p>{t('s63c08e9aeae9')}</p><div className="lab-toolbar">{([['severity','Priorytet',['ALL','HIGH','MEDIUM','LOW']],['entity','Encja',['ALL','Order']],['rule','Reguła',['ALL',...report.artifacts.rules.map(r=>r.id)]]] as [keyof typeof filters,string,string[]][]).map(([key,caption,options])=><label key={key}>{label(caption)}<select aria-label={label(caption)} value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}>{options.map(v=><option key={v} value={v}>{enumText(v)}</option>)}</select></label>)}<input aria-label={t('sc381c2470024')} value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></div><OperationsQueue rows={filterExceptions(report.artifacts.exceptions,filters)} show={show} trace={source}/>{trace!==null&&<section data-testid="operations-trace"><h3>{t('s18e5a18cbcee')}</h3><EvidenceView value={trace}/></section>}</>}
  {tab==='Zamówienia'&&report&&<><h3>{t('s0d34b3d0b607')}</h3><p>{t('s25b34652178e')}</p><EvidenceView value={report.artifacts.tables.orders}/></>}
  {tab==='Dokumenty'&&report&&<><h3>{t('saa738e77562f')}</h3><OperationsDocuments report={report} show={show}/></>}
  {tab==='Raport'&&report&&<><h3>{t('s5877f42f11be')}</h3><OperationsSummary report={report}/><OperationsReportDetails report={report}/><div className="workspace-actions"><button onClick={()=>void download('json')}>{t('s4dc00251c5cd')}</button><button onClick={()=>void download('csv')}>{t('s319b3b37a03d')}</button></div><p>{t('s2a8f941af897')}</p><EvidenceView value={report}/></>}
  {tab==='Architektura'&&<><h3>{t('s378d2b500b95')}</h3><p>{t('s12b56bc082b9')}</p><a href="/lab-api/docs" target="_blank" rel="noreferrer">{t('s59ac6a3d93c2')}</a></>}
  </section><section className="shell section"><h2>{t('see04c89ef492')}</h2><p>{t('s07e5e2738617')}</p><h3>{t('s5756755bb8ed')}</h3><p>{t('s66742a92200f')}</p><h3>{t('sddc798a1a631')}</h3><p>{t('sdd59f2011ea4')}</p><p>{t('sd4c89304f8b7')}</p></section><ProofNextStep example="operations-exceptions"/><dialog ref={dialog} className="issue-dialog" onClose={()=>setSelected(null)}><button className="dialog-close" aria-label={t('sb56e1e647517')} onClick={()=>dialog.current?.close()}>{t('s8db71ed28b0f')}</button><h2>{t('s858bfc05dace')}</h2><EvidenceView value={selected}/></dialog></main>;
}
