import {useDomainValue} from './domain-copy';
import {useDomainText} from './domain-copy';
import { useProofText } from './proof-copy';
import { useCounted } from './localized-count';
import type {OpException,OpReport,OpRule,OpScenario} from './operations-model';
export function OperationsSummary({report:r}:{report:OpReport}){ const counted=useCounted();  const t = useProofText(); return <div className="exception-value"><div><span>{t('s27167285cb8b')}</span><strong data-testid="operations-overall">{r.overall_status}</strong></div><p>{counted(r.scenario_count,['scenariusz','scenariusze','scenariuszy'])}{t('sb91423be1bcc')}{r.passed_scenarios}{t('s6d489b84dedb')}{r.failed_scenarios}<br/>{counted(r.exceptions_detected,['wyjątek','wyjątki','wyjątków'])}{t('s5667010caf96')}<br/>{t('sc8b525462ede')}{r.high}{t('s4193dc268892')}{r.medium}{t('sc02c771b6c75')}{r.low}</p></div>;}
export function OperationsResults({rows,show}:{rows:OpScenario[];show:(r:unknown)=>void}){ const valueText=useDomainValue();  const domain=useDomainText();  const t = useProofText(); return <div className="table-scroll"><table><thead><tr><th>{t('sdd4b9f2b401e')}</th><th>{t('s8cf67d704387')}</th><th>{t('s644855ad595f')}</th><th>{t('s60e6a5fcc71f')}</th><th>{t('s8e3c252723fc')}</th><th>{t('s1c45911567c2')}</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} data-testid="operations-result"><td>{domain(r.name)}<br/><code>{r.id}</code></td><td>{r.record}</td><td>{valueText(r.expected)}</td><td>{valueText(r.actual)}</td><td className={r.result==='FAIL'?'wf-fail':'wf-pass'}>{r.result}</td><td><button onClick={()=>show(r.evidence)}>{t('s1c45911567c2')}</button></td></tr>)}</tbody></table>{!rows.length&&<p>{t('sf835e77c3e0d')}</p>}</div>;}
export function OperationsRules({rules}:{rules:OpRule[]}){ const valueText=useDomainValue();  const domain=useDomainText();  const t = useProofText(); return <div className="table-scroll"><table><thead><tr><th>{t('sdfaaa170c07d')}</th><th>{t('sf87248d78a7b')}</th><th>{t('se7293ffb0f8a')}</th><th>{t('s89107103b539')}</th><th>{t('see4a8e213448')}</th><th>{t('s5380095eca64')}</th></tr></thead><tbody>{rules.map(r=><tr key={r.id} data-testid="operations-rule"><td><code>{r.id}</code></td><td>{valueText(r.category)}</td><td>{domain(r.expected_condition)}</td><td>{valueText(r.severity)}</td><td>{r.input_fields.join(', ')}</td><td>{domain(r.action)}</td></tr>)}</tbody></table></div>;}
export function OperationsQueue({rows,show,trace}:{rows:OpException[];show:(r:unknown)=>void;trace:(r:OpException)=>void}){ const valueText=useDomainValue();  const domain=useDomainText();  const t = useProofText(); return <div className="table-scroll"><table><thead><tr><th>{t('s89107103b539')}</th><th>{t('s8cf67d704387')}</th><th>{t('sa1c5ae7bcb34')}</th><th>{t('s644855ad595f')}</th><th>{t('s60e6a5fcc71f')}</th><th>{t('s83f07dc6e90d')}</th><th>{t('s4e1afbf85390')}</th><th>{t('s1c45911567c2')}</th></tr></thead><tbody>{rows.map(r=><tr key={r.exception_id} data-testid="operations-exception"><td>{valueText(r.severity)}<br/>{r.status}</td><td>{r.entity}/{r.entity_id}</td><td><code>{r.rule}</code></td><td>{valueText(r.expected)}</td><td>{valueText(r.actual)}</td><td>{r.deadline}</td><td>{domain(r.recommended_action)}</td><td><button onClick={()=>show({exception_id:r.exception_id,rule:r.rule,severity:r.severity,expected:r.expected,actual:r.actual,required_document:r.evidence.required_document,documents_found:r.evidence.documents_found,source:r.source,evidence:r.evidence})}>{t('s85072bd712ac')}</button><button onClick={()=>trace(r)}>{t('s50b4eec13492')}</button></td></tr>)}</tbody></table>{!rows.length&&<p>{t('s9521df65f5d5')}</p>}</div>;}
export function OperationsDocuments({report:r,show}:{report:OpReport;show:(r:unknown)=>void}){ const t = useProofText(); return <div className="table-scroll"><table><thead><tr><th>{t('s462e78d00fa8')}</th><th>{t('s44ad0ec2cbe4')}</th><th>{t('se5a33d15512c')}</th><th>{t('s920e413c7d41')}</th><th>{t('s1c45911567c2')}</th></tr></thead><tbody>{r.artifacts.tables.orders.map((order,i)=>{const docs=r.artifacts.tables.documents.filter(d=>d.order_id===order.order_id);const shipments=r.artifacts.tables.shipments.filter(s=>s.order_id===order.order_id);const found=docs.some(d=>d.type===order.required_document);return <tr key={i} data-testid="operations-document"><td>{String(order.order_id)} → {shipments.map(s=>String(s.shipment_id)).join(', ')}</td><td>{String(order.required_document)}</td><td>{docs.map(d=>String(d.type)).join(', ')||'—'}</td><td className={found?'wf-pass':'wf-fail'}>{found?t('sacc1839d9681'):t('missingDocument')+': '+String(order.required_document)}</td><td><button onClick={()=>show({order,shipments,documents:docs,missing:found?[]:[order.required_document]})}>{t('sc8d5012a6680')}</button></td></tr>;})}</tbody></table></div>;}
export function OperationsReportDetails({report:r}:{report:OpReport}){ const t = useProofText(); return <dl className="wf-report"><dt>{t('s26d3e7aaace4')}</dt><dd>{r.run_id}</dd><dt>{t('s786c3b1234b9')}</dt><dd>{r.timestamp}</dd><dt>{t('s73373981642c')}</dt><dd>{r.ruleset}</dd><dt>{t('s7a1db26b149a')}</dt><dd>{r.input_sha256}</dd><dt>{t('s3d8c0d48851a')}</dt><dd>{r.records_checked} / {r.controls_executed}</dd><dt>{t('s1bcc6f0d10ce')}</dt><dd>{r.unresolved} / {r.resolved}</dd></dl>;}
