import {defineCopy} from './localization-contract';
export const practicalSlugs=['guides/api-retries-and-duplicates','guides/reconcile-revenue-reports','examples/migration-acceptance-report'] as const;
export const practicalCopy=defineCopy('practical-resources',{
 en:{label:'Problems, checks and a sample deliverable',disclosure:'Independent working demonstration using synthetic data. Not a client deployment.',open:'Try the working example',contact:'Discuss a small first task',related:'Related practical examples',sampleLink:'See a sample acceptance report',download:'Download',sample:{title:'What a migration acceptance report looks like',description:'A downloadable synthetic migration report: missing records, correction, failed-only replay and source-to-target checks. View the result without running the demo.',intro:'Before commissioning a check, see the kind of evidence you can receive. This saved report was calculated by the existing migration engine from six synthetic records. It shows the failed result as well as the accepted result.',scope:'A first paid task can cover one export and one target specification: identify rejected or missing records, explain the differences and agree measurable acceptance checks. Price and timing are agreed after reviewing the scope.',before:'Before correction',after:'After correction and replay',source:'Source',target:'Target',rows:'Records',total:'Gross total · PLN',replay:'Only the failed records were replayed',selected:'Selected',skipped:'Unchanged',writes:'New writes',generated:'Sample generated',files:'Inspect or keep the evidence',html:'Open readable HTML report',json:'JSON evidence',csv:'Synthetic source CSV',limits:'This is an example deliverable, not an assessment of your systems. The target is simulated. PASS covers the implemented checks; it does not establish ERP compatibility or performance at your volume.',reproduce:'Reproduce it: load the sample in Migration Showcase, validate, remove the SKU-X99 mapping, migrate and reconcile. Restore the mapping, replay failed records and reconcile again.',request:'To scope your own check, describe the source and target, the fields that must match and what currently differs. Start with a sanitised sample; do not send credentials or production data through the contact form.'},articles:[
 {title:'API retries and duplicate records: what to check before retrying',description:'A practical guide to API timeouts, duplicate records, idempotency and acceptance tests, with runnable synthetic examples.',intro:'An order update times out. Retrying may recover the flow—or create a second order if the destination already accepted the first request. The first task is to establish what happened, not simply increase the retry count.',sections:[
 ['A timeout leaves an unanswered question','The caller did not receive a usable response. That alone does not show whether the destination committed the record. Keep the source identifier, request identity, payload fingerprint and attempt history. If the outcome cannot be established, keep it unresolved and route it for investigation.'],
 ['Separate a repeated request from a changed request','A repeat of the same operation should preserve its request identity. The same identity with a different payload needs an explicit conflict policy. A retry mechanism is incomplete if it checks only the HTTP status and cannot tell these situations apart. The destination API determines which guarantees are actually available.'],
 ['Check the existing synthetic API test pack','Open API Tests and run the pack. IDM-007 checks that the synthetic duplicate response returns HTTP 200 with idempotentReplay=true. RTY-012 injects a 504 response followed by 201 and remains WARNING. These are controlled endpoint checks, not proof of a real vendor’s delivery guarantees. The displayed fixture durations are illustrative, not performance measurements.'],
 ['Inspect a stronger recovery example','Migration Showcase preserves accepted target records while replaying only failed records. Remove SKU-X99: TX-104 and TX-106 remain exceptions. Restore it and replay: only those two are written. A further replay writes nothing. This demonstrates selective recovery in a controlled target, not distributed exactly-once delivery.'],
 ['Agree what counts as acceptance','For a real API flow, test an identical repeat, the same key with changed contents, timeout before acceptance, timeout after acceptance and recovery after restart. The last three require a representative test environment and evidence from the destination. Record source/target IDs, attempts and the observed final state. Do not infer a successful write from a retry counter.'],
 ['A small first assignment','Start with one API operation, its documentation and sanitised failed request/response examples. The deliverable can be a reproducible test pack, a list of confirmed failure modes and proposed recovery rules. Implementation and production rollout are separately scoped after the actual API constraints are understood.']]},
 {title:'Why CRM, ERP and spreadsheet revenue totals disagree',description:'Separate booked and invoiced revenue, remove overlapping history and trace unexplained amounts to source records using a synthetic reconciliation example.',intro:'Different revenue totals are not automatically broken data. A won CRM deal, a posted invoice and a historical revenue row represent different events. Reconciliation starts by defining which question each total answers.',sections:[
 ['Define the metric before comparing totals','Booked Revenue uses accepted closed-won CRM deals. Invoiced Revenue uses accepted posted ERP invoices. Reported Revenue combines accepted history through June 2026 with ERP invoices from July 2026. CRM deals are not added to that total. Booked minus invoiced can reflect timing; a won deal without an invoice is a business variance, not necessarily a data defect.'],
 ['Choose the authoritative period','In the working example, history is authoritative through 30 June 2026 and ERP from 1 July. Two July historical records total €4,050 and are excluded as overlap. They remain visible in the evidence. Adding every historical row to every invoice would count an overlapping period twice.'],
 ['Explain excluded amounts, including dirty records','The raw historical EUR total is €87,000. Initially €64,200 is accepted; €18,400 awaits Northstar customer mapping, €4,050 is overlap and €350 has an invalid period. ERP contributes €36,800 in accepted invoices. A duplicate and unsupported product are excluded under explicit rules; an unknown currency remains in a separate bucket with no invented FX conversion.'],
 ['Correct the mapping, then run reconciliation','Initially Reported Revenue is €101,000: €64,200 + €36,800. Map Northstar to CUST-1042 and explicitly re-run reconciliation. Accepted history becomes €82,600 and Reported Revenue becomes €119,400. The €18,400 change is explained by one customer mapping; other source records are unchanged.'],
 ['Read PASS within its definition','Reconciliation PASS means monetary records are accounted for as included or explicitly excluded, controls agree and no blocking configuration exception remains. Source Data Quality can still show WARNING because duplicate, date, product and currency defects remain in the original data. PASS does not erase them.'],
 ['Trace the result before trusting the dashboard','Open Revenue BI, inspect the sources, run reconciliation, correct Northstar and reconcile again. In the dashboard, trace July revenue to its ERP invoices and excluded historical rows. Download the HTML or JSON evidence. For your own data, a first assignment can define one metric, reconcile two sanitised exports and explain every difference before dashboard development.']]}
 ]},
 pl:{label:'Problemy, kontrole i przykładowy rezultat',disclosure:'Niezależna działająca demonstracja na danych syntetycznych. To nie jest wdrożenie klienta.',open:'Sprawdź działający przykład',contact:'Omów małe pierwsze zadanie',related:'Powiązane przykłady praktyczne',sampleLink:'Zobacz przykładowy raport odbioru',download:'Pobierz',sample:{title:'Jak wygląda raport odbioru migracji',description:'Syntetyczny raport migracji do pobrania: brakujące rekordy, poprawka, ponowienie błędów i porównanie źródła z celem. Zobacz wynik bez uruchamiania demonstracji.',intro:'Przed zleceniem kontroli zobacz, jakie dowody możesz otrzymać. Ten zapisany raport obliczono istniejącym mechanizmem migracji na sześciu syntetycznych rekordach. Pokazuje wynik nieudany oraz wynik po poprawce.',scope:'Pierwsze płatne zadanie może objąć jeden eksport i jedną specyfikację celu: wskazanie odrzuconych lub brakujących rekordów, wyjaśnienie różnic i uzgodnienie mierzalnych kryteriów odbioru. Cenę i termin ustalamy po sprawdzeniu zakresu.',before:'Przed poprawką',after:'Po poprawce i ponowieniu',source:'Źródło',target:'Cel',rows:'Rekordy',total:'Suma brutto · PLN',replay:'Ponowiono tylko błędne rekordy',selected:'Wybrane',skipped:'Bez zmian',writes:'Nowe zapisy',generated:'Przykład wygenerowano',files:'Sprawdź lub zachowaj dowody',html:'Otwórz czytelny raport HTML',json:'Dowody JSON',csv:'Syntetyczny plik źródłowy CSV',limits:'To przykładowy rezultat, a nie ocena Twoich systemów. Cel jest symulowany. PASS dotyczy zaimplementowanych kontroli; nie potwierdza zgodności z konkretnym ERP ani wydajności przy Twojej skali.',reproduce:'Odtwórz wynik: wczytaj próbkę w Migration Showcase, zweryfikuj ją, usuń mapowanie SKU-X99, wykonaj migrację i uzgodnienie. Przywróć mapowanie, ponów błędne rekordy i ponownie uzgodnij dane.',request:'Aby określić zakres własnej kontroli, opisz źródło i cel, pola wymagające zgodności oraz obecne różnice. Zacznij od próbki bez danych poufnych; nie wysyłaj haseł ani danych produkcyjnych przez formularz.'},articles:[
 {title:'Ponowienia API i duplikaty rekordów: co sprawdzić przed kolejną próbą',description:'Praktyczny poradnik o timeoutach API, duplikatach, idempotencji i testach odbioru z działającymi przykładami na danych syntetycznych.',intro:'Aktualizacja zamówienia kończy się timeoutem. Ponowienie może przywrócić proces albo utworzyć drugie zamówienie, jeśli cel zaakceptował już pierwsze żądanie. Najpierw trzeba ustalić, co się wydarzyło, zamiast zwiększać liczbę prób.',sections:[
 ['Timeout pozostawia pytanie bez odpowiedzi','Wywołujący nie otrzymał użytecznej odpowiedzi. Sam ten fakt nie mówi, czy cel zapisał rekord. Zachowaj identyfikator źródłowy, tożsamość żądania, skrót jego treści i historię prób. Jeśli nie da się ustalić wyniku, pozostaw go nierozstrzygniętym i skieruj do wyjaśnienia.'],
 ['Odróżnij ponowienie od zmienionego żądania','Powtórzenie tej samej operacji powinno zachować jej tożsamość. Ta sama tożsamość z inną treścią wymaga jawnej reguły konfliktu. Mechanizm ponowień jest niepełny, jeśli sprawdza tylko status HTTP i nie rozróżnia tych sytuacji. Dostępne gwarancje zależą od API docelowego.'],
 ['Sprawdź istniejący syntetyczny pakiet testów API','Otwórz API Tests i uruchom pakiet. IDM-007 sprawdza, czy syntetyczna odpowiedź na duplikat zwraca HTTP 200 i idempotentReplay=true. RTY-012 wstrzykuje odpowiedź 504, a następnie 201 i zachowuje WARNING. To kontrolowane testy endpointów, a nie dowód gwarancji dostarczenia konkretnego dostawcy. Pokazane czasy próbki są ilustracyjne, nie stanowią pomiaru wydajności.'],
 ['Sprawdź dokładniejszy przykład odzyskiwania','Migration Showcase zachowuje zaakceptowane rekordy celu i ponawia tylko błędne. Usuń SKU-X99: TX-104 i TX-106 pozostają wyjątkami. Przywróć mapowanie i ponów: zapisane zostaną tylko te dwa rekordy. Kolejne ponowienie niczego nie zapisuje. To selektywne odzyskiwanie w kontrolowanym celu, nie gwarancja exactly-once w systemie rozproszonym.'],
 ['Ustal warunki odbioru','Dla rzeczywistego procesu API sprawdź identyczne ponowienie, ten sam klucz ze zmienioną treścią, timeout przed akceptacją, timeout po akceptacji oraz odzyskanie po restarcie. Ostatnie trzy przypadki wymagają reprezentatywnego środowiska testowego i dowodów z celu. Zapisz identyfikatory źródła i celu, próby oraz końcowy zaobserwowany stan. Sam licznik prób nie potwierdza zapisu.'],
 ['Małe pierwsze zlecenie','Zacznij od jednej operacji API, jej dokumentacji i przykładów nieudanych żądań oraz odpowiedzi bez danych poufnych. Rezultatem może być powtarzalny pakiet testów, lista potwierdzonych problemów i proponowane reguły odzyskiwania. Implementację oraz uruchomienie produkcyjne uzgadniamy osobno po poznaniu ograniczeń API.']]},
 {title:'Dlaczego sumy przychodów w CRM, ERP i arkuszu się różnią',description:'Oddziel sprzedaż z CRM od faktur, usuń nakładającą się historię i znajdź źródło różnic na syntetycznym przykładzie uzgadniania przychodów.',intro:'Różne sumy przychodów nie muszą oznaczać błędnych danych. Wygrana szansa CRM, zaksięgowana faktura i historyczny wiersz przychodu opisują różne zdarzenia. Uzgadnianie zaczyna się od ustalenia, na jakie pytanie odpowiada każda suma.',sections:[
 ['Zdefiniuj metrykę przed porównaniem sum','Sprzedaż pozyskana obejmuje zaakceptowane wygrane transakcje CRM. Przychód z faktur obejmuje zaakceptowane zaksięgowane faktury ERP. Przychód raportowany łączy zaakceptowaną historię do czerwca 2026 z fakturami ERP od lipca. Transakcji CRM nie dodajemy do tej sumy. Różnica sprzedaży i faktur może wynikać z terminów; wygrana transakcja bez faktury jest odchyleniem biznesowym, niekoniecznie wadą danych.'],
 ['Wybierz okres obowiązywania źródła','W działającym przykładzie historia jest źródłem nadrzędnym do 30 czerwca 2026, a ERP od 1 lipca. Dwa lipcowe rekordy historyczne o sumie 4 050 EUR są pomijane jako nakładanie okresów. Pozostają widoczne w dowodach. Dodanie całej historii do wszystkich faktur policzyłoby wspólny okres dwukrotnie.'],
 ['Wyjaśnij pominięte kwoty i wady źródeł','Surowa suma historii w EUR wynosi 87 000. Początkowo zaakceptowano 64 200; kwota 18 400 czeka na mapowanie klienta Northstar, 4 050 nakłada się na ERP, a 350 ma niepoprawny okres. ERP wnosi 36 800 EUR zaakceptowanych faktur. Duplikat i nieobsługiwany produkt są pomijane według jawnych reguł; nieznana waluta pozostaje osobno, bez wymyślonego przeliczenia kursu.'],
 ['Popraw mapowanie i ponów uzgodnienie','Początkowy przychód raportowany to 101 000 EUR: 64 200 + 36 800. Przypisz Northstar do CUST-1042 i jawnie ponów uzgodnienie. Zaakceptowana historia wzrośnie do 82 600, a przychód raportowany do 119 400 EUR. Zmianę o 18 400 wyjaśnia jedno mapowanie klienta; pozostałe rekordy źródłowe się nie zmieniają.'],
 ['Odczytuj PASS zgodnie z definicją','PASS uzgodnienia oznacza, że kwoty uwzględniono albo jawnie pominięto, kontrole są zgodne i nie ma blokującego wyjątku konfiguracji. Jakość źródeł nadal może mieć WARNING, ponieważ duplikaty oraz wady dat, produktów i walut pozostają w oryginalnych danych. PASS ich nie usuwa.'],
 ['Sprawdź źródło wyniku przed użyciem panelu','Otwórz Revenue BI, sprawdź źródła, uzgodnij dane, popraw Northstar i powtórz uzgodnienie. W panelu prześledź przychód lipcowy do faktur ERP i pominiętych rekordów historii. Pobierz dowody HTML lub JSON. Dla własnych danych pierwsze zadanie może objąć definicję jednej metryki, uzgodnienie dwóch eksportów bez danych poufnych i wyjaśnienie każdej różnicy przed budową panelu.']]}
 ]}
});
