import {defineCopy} from './localization-contract';
export const L=defineCopy('quality-views',{
  "pl": {
 "stages":["ŹRÓDŁO","SUROWE","ZNORMALIZOWANE","TYPOWANE","CEL"],"runA":"PRZEBIEG A","runB":"PRZEBIEG B","runId":"Identyfikator przebiegu",
    "pipeline": "Odbiór potoku danych",
    "scenarios": [
      "scenariusz",
      "scenariusze",
      "scenariuszy"
    ],
    "input": "Wejście",
    "accepted": "zaakceptowane",
    "rejected": "odrzucone",
    "checks": "Kontrole jakości",
    "causes": "przyczyny błędów",
    "rule": "Reguła / scenariusz",
    "record": "Rekord / pole",
    "expected": "Oczekiwane",
    "actual": "Rzeczywiste",
    "test": "Wynik testu",
    "evidence": "Dowód",
    "noRows": "Brak wyników dla filtrów.",
    "sourceTarget": "Źródło → cel",
    "targetType": "Typ docelowy",
    "transform": "Transformacja",
    "inputType": "Typ wejścia",
    "requiredNull": "Wymagane / null",
    "rules": "Reguły / wartości",
    "required": "Wymagane",
    "optional": "Opcjonalne",
    "allowed": "null dozwolony",
    "noNull": "bez null",
    "expectedTarget": "Oczekiwana wartość docelowa:",
    "controlled": "Kontrolowana zmiana: ×100 po normalizacji. Wadliwa wartość docelowa nie została dopuszczona do zaakceptowanego zbioru.",
    "hash": "Hash rekordu źródłowego:",
    "fieldEvidence": "Dowód pola",
    "sourceRow": "Źródło / wiersz",
    "priority": "Priorytet / wynik",
    "dataReject": "Dane: REJECT",
    "currentError": "Błąd bieżącego przebiegu",
    "rejectEvidence": "Dowód odrzucenia",
    "noRejected": "Brak odrzuconych rekordów.",
    "qualityChange": "Zmiana jakości A → B",
    "newErrors": "Nowe błędy:",
    "resolved": "Usunięte:",
    "changedRecords": "Zmienione rekordy:",
    "changedFields": "Zmienione pola:",
    "compare": "Porównanie zbiorów docelowych przed bramką odbioru. Utrata dopuszczenia rekordu jest osobną zmianą metryki, nie dodatkową zmianą pola.",
    "recordHead": "Rekord",
    "field": "Pole",
    "metric": "Zmiana liczby zaakceptowanych:",
    "metricRejected": "odrzuconych:",
    "metricFailures": "błędów jakości:",
    "hashRules": "Hash wejścia i wersji reguł",
    "clockRules": "Zegar scenariusza / reguły",
    "processedErrors": "Przetworzone rekordy / błędy transformacji",
    "sumChecks": "Kontrole sum i liczności",
    "control": "Kontrola",
    "diagnosis": "Diagnoza",
    "sameCause": "Ta sama przyczyna:"
  },
  "en": {
 "stages":["SOURCE","RAW","NORMALIZED","TYPED","TARGET"],"runA":"RUN A","runB":"RUN B","runId":"Run ID",
    "pipeline": "Data pipeline acceptance",
    "scenarios": [
      "scenario",
      "scenarios",
      "scenarios"
    ],
    "input": "Input",
    "accepted": "accepted",
    "rejected": "rejected",
    "checks": "Quality checks",
    "causes": "failure causes",
    "rule": "Rule / scenario",
    "record": "Record / field",
    "expected": "Expected",
    "actual": "Actual",
    "test": "Test result",
    "evidence": "Evidence",
    "noRows": "No results for these filters.",
    "sourceTarget": "Source → target",
    "targetType": "Target type",
    "transform": "Transformation",
    "inputType": "Input type",
    "requiredNull": "Required / null",
    "rules": "Rules / values",
    "required": "Required",
    "optional": "Optional",
    "allowed": "null allowed",
    "noNull": "no null",
    "expectedTarget": "Expected target value:",
    "controlled": "Controlled change: ×100 after normalization. The faulty target value was not admitted into the accepted dataset.",
    "hash": "Source record hash:",
    "fieldEvidence": "Field evidence",
    "sourceRow": "Source / row",
    "priority": "Priority / result",
    "dataReject": "Data: REJECT",
    "currentError": "Current-run error",
    "rejectEvidence": "Rejection evidence",
    "noRejected": "No rejected records.",
    "qualityChange": "Quality change A → B",
    "newErrors": "New errors:",
    "resolved": "Resolved:",
    "changedRecords": "Changed records:",
    "changedFields": "Changed fields:",
    "compare": "Comparison of target datasets before the acceptance gate. Loss of accepted-record admission is a separate metric change, not an additional field change.",
    "recordHead": "Record",
    "field": "Field",
    "metric": "Accepted-count change:",
    "metricRejected": "rejected:",
    "metricFailures": "quality failures:",
    "hashRules": "Input and ruleset hash",
    "clockRules": "Scenario clock / ruleset",
    "processedErrors": "Processed records / transformation errors",
    "sumChecks": "Sum and count checks",
    "control": "Control",
    "diagnosis": "Diagnosis",
    "sameCause": "Same cause:"
  }
});
