import {useDomainValue} from './domain-copy';
import {counted} from './polish';
import { useLocale } from './locale';
import {qualityValue as value,type QualityReport,type QualityScenario,type QualityField,type QualityEdge,type QualityFailure,type QualityComparison} from './quality-model';
import { L } from './quality-views-copy';

export function QualitySummary({report:r}:{report:QualityReport}){const locale=useLocale();const t=L[locale];return <div className="exception-value"><div><span>{t.pipeline}</span><strong data-testid="quality-overall">{r.overall_status}</strong></div><p>{counted(r.scenario_count,t.scenarios as [string,string,string])} · PASS: {r.passed_scenarios} · FAIL: {r.failed_scenarios}<br/>{t.input}: {r.records_received} · {t.accepted}: {r.accepted} · {t.rejected}: {r.rejected}<br/>{t.checks}: {r.quality_checks} · {t.causes}: {r.quality_failures}</p></div>;}
export function QualityResults({rows,show}:{rows:QualityScenario[];show:(v:unknown)=>void}){ const valueText=useDomainValue(); const t=L[useLocale()];return <div className="table-scroll"><table><thead><tr><th>{t.rule}</th><th>{t.record}</th><th>{t.expected}</th><th>{t.actual}</th><th>{t.test}</th><th>{t.evidence}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id+r.record_id+i} data-testid="quality-result"><td><code>{r.id}</code><br/>{valueText(r.category)} · {valueText(r.severity)}</td><td>{r.record_id}<br/>{r.field}</td><td>{valueText(r.expected)}</td><td>{valueText(r.actual)}</td><td className={r.result==='FAIL'?'wf-fail':'wf-pass'}>{r.result}</td><td><button onClick={()=>show(r.evidence)}>{t.evidence}</button></td></tr>)}</tbody></table>{!rows.length&&<p>{t.noRows}</p>}</div>;}
export function QualityContract({fields,transforms=false}:{fields:QualityField[];transforms?:boolean}){const t=L[useLocale()];return <div className="table-scroll"><table><thead><tr><th>{t.sourceTarget}</th><th>{transforms?t.transform:t.targetType}</th><th>{t.inputType}</th><th>{t.requiredNull}</th><th>{t.rules}</th></tr></thead><tbody>{fields.map(f=><tr key={f.target} data-testid="quality-field"><td>{f.source} →<br/>{f.target}</td><td>{transforms?f.transformation:f.type}{transforms&&<><br/>{f.type}</>}</td><td>{f.input_type}</td><td>{f.required?t.required:t.optional} / {f.allowed_null?t.allowed:t.noNull}</td><td>{f.rules.join(', ')}<br/>{f.allowed_values?.join(', ')}</td></tr>)}</tbody></table></div>;}
export function QualityLineage({edge,show}:{edge:QualityEdge;show:(v:unknown)=>void}){const t=L[useLocale()];return <section data-testid="quality-lineage"><h3>{edge.record_id} · <code>{`target.${edge.target_field}`}</code></h3><div className="pipeline five">{[['SOURCE',`${edge.source.file} · ${edge.source.position_kind} ${edge.source.row} · ${edge.source_field}`],['RAW',value(edge.raw_value)],['NORMALIZED',value(edge.normalized_value)],['TYPED',`${edge.typed_type}: ${value(edge.typed_value)}`],['TARGET',value(edge.target_value)]].map(([label,text],index)=><article key={label}><b>{t.stages[index]}</b><p>{text}</p></article>)}</div><p>{t.transform}: <code>{edge.transformation}</code>. {t.expectedTarget} <strong>{value(edge.expected_value)}</strong>.</p>{edge.controlled_change&&<p className="wf-fail">{t.controlled}</p>}<p>{t.hash} <code>{edge.source.input_hash}</code></p><button onClick={()=>show(edge)}>{t.fieldEvidence}</button></section>;}
export function QualityRejected({rows,show}:{rows:QualityFailure[];show:(v:unknown)=>void}){ const valueText=useDomainValue(); const t=L[useLocale()];return <div className="table-scroll"><table><thead><tr><th>{t.sourceRow}</th><th>{t.recordHead}</th><th>{t.rule}</th><th>{t.expected}</th><th>{t.actual}</th><th>{t.priority}</th><th>{t.evidence}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.root_id+i} data-testid="quality-rejected"><td>{r.source.file}<br/>{r.source.row}</td><td>{r.record_id}</td><td>{r.rule}</td><td>{valueText(r.expected)}</td><td>{valueText(r.actual)}</td><td>{valueText(r.severity)}<br/>{t.dataReject}<br/>{r.expected_rejection?`Test: ${r.scenario_result}`:t.currentError}</td><td><button onClick={()=>show(r)}>{t.rejectEvidence}</button></td></tr>)}</tbody></table>{!rows.length&&<p>{t.noRejected}</p>}</div>;}
export function QualityDiff({diff:d}:{diff:QualityComparison}){const t=L[useLocale()];return <section data-testid="quality-comparison"><div className="exception-value"><div><span>{t.qualityChange}</span><strong>{t.newErrors} {d.new_failures.length}</strong></div><p>{t.resolved} {d.resolved_failures.length}<br/>{t.changedRecords} {d.changed_records}<br/>{t.changedFields} {d.changed_fields}</p></div><p>{t.compare}</p><div className="table-scroll"><table><thead><tr><th>{t.recordHead}</th><th>{t.field}</th><th>{t.runA}</th><th>{t.runB}</th></tr></thead><tbody>{d.changes.map((c,i)=><tr key={i}><td>{c.record_id}</td><td>{c.field}</td><td>{value(c.before)}</td><td>{value(c.after)}</td></tr>)}</tbody></table></div><p>{t.metric} {d.metric_differences.accepted} · {t.metricRejected} {d.metric_differences.rejected} · {t.metricFailures} {d.metric_differences.quality_failures}</p></section>;}
export function QualityReportDetails({report:r}:{report:QualityReport}){const t=L[useLocale()];return <><dl className="wf-report"><dt>{t.runId}</dt><dd>{r.run_id}</dd><dt>{t.hashRules}</dt><dd>{r.input_sha256}</dd><dt>{t.clockRules}</dt><dd>{r.timestamp} / {r.ruleset}</dd><dt>{t.processedErrors}</dt><dd>{r.records_processed} / {r.transformation_failures}</dd></dl><h3>{t.sumChecks}</h3><div className="table-scroll"><table><thead><tr><th>{t.control}</th><th>{t.expected}</th><th>{t.actual}</th><th>{t.diagnosis}</th></tr></thead><tbody>{r.artifacts.aggregate_controls.map(a=><tr key={a.rule}><td>{a.rule}</td><td>{value(a.expected)}</td><td>{value(a.actual)}</td><td>{a.status}{a.grouped_under.length>0&&<><br/>{t.sameCause} {a.grouped_under.join(', ')}</>}</td></tr>)}</tbody></table></div></>;}
