import {defineCopy} from './localization-contract';
export const dataQualityCopy=defineCopy('data-quality',{
  "pl": {
    "back": "← Wszystkie przykłady",
    "eyebrow": "Demonstracja techniczna",
    "trust": "Dane syntetyczne · niezależna implementacja · powtarzalne reguły jakości",
    "title": "Kontrola jakości danych w potoku",
    "standards": "wczytywanie danych · transformacje · reguły jakości · lineage · regresja",
    "buyer": "Wynik dla odbiorcy:",
    "buyerBody": "raport jakości danych, odrzucone rekordy, ślad transformacji od źródła do celu oraz porównanie zmian między przebiegami.",
    "scope": "Pierwszy zakres:",
    "scopeBody": "próbka danych, eksport lub fragment potoku. Odpowiedzialność obejmuje uzgodnione transformacje, reguły jakości, scenariusze regresji i raport odbiorczy.",
    "flow": [
      [
        "Wejście",
        "Eksport CSV/JSON lub próbka transakcji."
      ],
      [
        "Jak działa kontrola",
        "Wczytywanie → obszar przejściowy → normalizacja → transformacja."
      ],
      [
        "Co system wykrywa",
        "Schemat, typ, referencja, transformacja i spójność."
      ],
      [
        "Co otrzymujesz",
        "Raport jakości, kwarantanna, lineage i różnice przebiegów."
      ],
      [
        "Jak odbierany jest wynik",
        "Kontrakt, reguły i transformacje dają oczekiwany wynik."
      ]
    ],
    "pack": "Pakiet odbiorczy fragmentu potoku",
    "packTitle": "Od surowej wartości do odebranego zbioru",
    "packBody": "Zbiór docelowy jest widoczny przed odbiorem. Wadliwy rekord trafia do kwarantanny i nie powiększa zaakceptowanego zbioru. Oczekiwane REJECT w scenariuszu negatywnym daje test PASS.",
    "runRef": "Uruchom pakiet referencyjny",
    "defect": "Wprowadź kontrolowaną rozbieżność",
    "restore": "Przywróć konfigurację referencyjną",
    "modeControlled": "KONTROLOWANA REGRESJA TRANSFORMACJI",
    "modeBase": "KONFIGURACJA REFERENCYJNA",
    "modeControlledBody": "TX-104: po poprawnej normalizacji 1 234,50 → 1234.50 celowo zastosowano mnożnik ×100. Wartość w zbiorze docelowym: 123450.00. Jedna przyczyna; różnica agregatu jest dowodem tej samej regresji.",
    "modeBaseBody": "Referencyjne transformacje nie zawierają celowej zmiany. Bieżące wejście jest sprawdzane niezależnie; wynik PASS nie jest zakładany z góry. Pakiet referencyjny ustala RUN A do porównania przebiegów.",
    "busy": "Wykonywanie potoku…",
    "tech": "Dla osoby technicznej",
    "techBody": "Sprawdź wejście, reguły, identyfikator przebiegu i dowody w zakładkach poniżej.",
    "tabs": [
      "Wejście",
      "Wyniki",
      "Kontrakt danych",
      "Schema drift",
      "Transformacje",
      "Odrzucone",
      "Lineage",
      "Przebiegi",
      "Regresja",
      "Raport",
      "Architektura"
    ],
    "empty": "Brak wyniku",
    "emptyBody": "Uruchom pakiet referencyjny, aby zobaczyć dane tej sekcji i dowód wykonania.",
    "inputTitle": "Plik → obszar przejściowy → model kanoniczny → zbiór docelowy",
    "inputBody": "CSV UTF-8 z przecinkiem lub JSON jako tablica rekordów. Dane są przesyłane do API Workera i zapisywane w raporcie D1 (lokalnie: SQLite). Używaj danych syntetycznych. Wczytanie pliku wyłącza kontrolowaną wadę transformacji.",
    "upload": "Wczytaj CSV/JSON",
    "runCurrent": "Uruchom na wczytanym wejściu",
    "actualStages": "Rzeczywiste etapy przebiegu",
    "resultFilter": "Wynik testu",
    "category": "Kategoria",
    "entity": "Encja",
    "priority": "Priorytet",
    "search": "Szukaj wyniku",
    "contractTitle": "Jawny kontrakt źródła i celu",
    "contractBody": "Kwoty są obliczane jako Decimal; JSON przechowuje je jako ciągi z dwoma miejscami dziesiętnymi. Daty mają jawny format, a wartości null są dozwolone tylko w note.",
    "driftTitle": "Schema drift i wersjonowane mapowanie",
    "driftBody": "Ta sekcja pokazuje zmianę kształtu eksportu przed przyjęciem danych do zbioru docelowego. Nowe pole opcjonalne jest zgodne z polityką, brak wymaganego pola lub niezgodny typ zatrzymuje rekord w kwarantannie.",
    "driftHeaders": [
      "Scenariusz",
      "Status",
      "Źródło / mapowanie / cel",
      "Pole / reguła",
      "Oczekiwane / rzeczywiste",
      "Polityka"
    ],
    "quarantine": "kwarantanna:",
    "transformTitle": "Katalog transformacji",
    "rulesTitle": "Katalog kontroli jakości",
    "ruleHeaders": [
      "Identyfikator reguły",
      "Kategoria",
      "Warunek"
    ],
    "targetRecord": "Rekord docelowy",
    "targetField": "Pole docelowe",
    "noLineage": "Brak transformacji dla tego rekordu. Odrzucenia przed transformacją mają źródło i przyczynę w kwarantannie.",
    "rejectTitle": "Kwarantanna i oczekiwane odrzucenia",
    "rejectSet": "Zestaw odrzuceń",
    "currentRun": "Bieżący przebieg",
    "negative": "Oczekiwane przypadki negatywne",
    "rejectBody": "Odrzucone dane i wynik testu są oddzielne. Poprawnie wykryty błąd w ustalonym scenariuszu negatywnym daje test PASS.",
    "runsTitle": "Zapisane, odtwarzalne przebiegi",
    "runsBody": "D1 w wersji publicznej, SQLite lokalnie, przechowuje zapis raportu po deterministycznym run ID. Reset odtwarza to samo ID referencji, nie nową wersję danych. Czas jest stałym zegarem scenariusza.",
    "runHeaders": [
      "Przebieg / skrót",
      "Zegar",
      "Wejście / zaakceptowane / odrzucone",
      "Kontrole / błędy",
      "Status",
      "Dowód"
    ],
    "runReport": "Raport przebiegu",
    "regressionTitle": "RUN A — referencja / RUN B — bieżący wynik",
    "regressionEmpty": "Uruchom referencję, następnie kontrolowaną regresję. Reset porównuje przywróconą referencję z nią samą.",
    "reportTitle": "Raport jakości i odbioru",
    "reportBody": "Suma źródłowa dotyczy rekordów, które przeszły walidację wejścia. Sumę kandydatów porównujemy przed bramką odbioru. Rozbieżność sumy przypisana do root ID nie tworzy drugiego FAIL scenariusza.",
    "json": "Pobierz JSON",
    "csv": "Pobierz CSV",
    "archTitle": "Adapter → parser → obszar przejściowy → model kanoniczny → transformacje → jakość → cel → lineage → różnice → raport",
    "archBody": "Silnik TypeScript rozdziela kontrakt wejścia, dokładne kwoty w jednostkach setnych, daty, transformacje, odrzucenie, porównanie i raport. Python/Decimal i FastAPI stanowią referencję testową. D1 przechowuje raporty wersji publicznej, React pokazuje dowody. System nie wymaga infrastruktury klastrowej.",
    "verify": "Co możesz tutaj zweryfikować",
    "verifyBody": "Kontrakt danych, transformacje, reguły jakości, źródło błędu, lineage na poziomie pola, wartości oczekiwane i rzeczywiste, różnicę między przebiegami i powtarzalny raport odbiorczy.",
    "criteria": "Kryteria odbioru",
    "criteriaBody": "Referencja: wszystkie scenariusze PASS. Kontrolowana transformacja TX-104: jedna główna rozbieżność, jeden zmieniony rekord i jedno pole. Odrzucony rekord nie trafia do zaakceptowanego zbioru docelowego. Reset: ponownie PASS i czyste porównanie.",
    "demoScope": "Zakres demonstracji",
    "demoBody1": "Kontrolowany fragment potoku: wczytywanie danych, normalizacja, transformacje, reguły jakości i ślad od źródła do celu. Adapter do środowiska Data Lake/ETL jest osobnym zakresem integracyjnym. Dane oraz wymiar klientów są syntetyczne.",
    "demoBody2": "Publiczny zestaw danych: CSV/JSON, do 1000 rekordów dla powtarzalnego scenariusza testowego. Jedna główna przyczyna odrzucenia na rekord; walidacja zatrzymuje rekord na pierwszej blokadzie. Lineage pól dotyczy rekordów, które dotarły do transformacji. Stały zegar: 16 września 2026. Backend izoluje raporty według sesji przeglądarki i nie zapisuje do systemów źródłowych.",
    "cta": "Opisz zakres",
    "close": "Zamknij dowód",
    "dialog": "Dowód jakości i transformacji",
    "sections": "Sekcje jakości danych",
    "sourceData": "Dane źródłowe",
    "docs": "OpenAPI / dokumentacja API →"
  },
  "en": {
    "back": "← All examples",
    "eyebrow": "Technical demonstration",
    "trust": "Synthetic data · independent implementation · repeatable quality rules",
    "title": "Data quality control in a pipeline",
    "standards": "ingestion · transformations · quality rules · lineage · regression",
    "buyer": "Buyer outcome:",
    "buyerBody": "data quality report, rejected records, source-to-target transformation trace and comparison between runs.",
    "scope": "First scope:",
    "scopeBody": "data sample, export or pipeline fragment. Responsibility covers agreed transformations, quality rules, regression scenarios and acceptance report.",
    "flow": [
      [
        "Input",
        "CSV/JSON export or transaction sample."
      ],
      [
        "How the check works",
        "Ingestion → staging → normalization → transformation."
      ],
      [
        "What the system detects",
        "Schema, type, reference, transformation and consistency."
      ],
      [
        "What you receive",
        "Quality report, quarantine, lineage and run differences."
      ],
      [
        "How the result is accepted",
        "Contract, rules and transformations produce the expected result."
      ]
    ],
    "pack": "Pipeline fragment acceptance package",
    "packTitle": "From raw value to accepted dataset",
    "packBody": "The target dataset is visible before acceptance. A faulty record goes to quarantine and does not increase the accepted dataset. Expected REJECT in a negative scenario gives the test a PASS result.",
    "runRef": "Run the reference package",
    "defect": "Introduce controlled discrepancy",
    "restore": "Restore reference configuration",
    "modeControlled": "CONTROLLED TRANSFORMATION REGRESSION",
    "modeBase": "REFERENCE CONFIGURATION",
    "modeControlledBody": "TX-104: after correct normalization 1 234.50 → 1234.50, a ×100 multiplier is applied intentionally. Target value: 123450.00. One cause; the aggregate difference is evidence of the same regression.",
    "modeBaseBody": "Reference transformations contain no intentional change. The current input is checked independently; PASS is not assumed upfront. The reference package establishes RUN A for run comparison.",
    "busy": "Running pipeline…",
    "tech": "For a technical reviewer",
    "techBody": "Inspect input, rules, run identifier and evidence in the tabs below.",
    "tabs": [
      "Input",
      "Results",
      "Data contract",
      "Schema drift",
      "Transformations",
      "Rejected",
      "Lineage",
      "Runs",
      "Regression",
      "Report",
      "Architecture"
    ],
    "empty": "No result yet",
    "emptyBody": "Run the reference package to see this section and execution evidence.",
    "inputTitle": "File → staging → canonical model → target",
    "inputBody": "Comma-separated UTF-8 CSV or JSON as an array of records. Data is sent to the Worker API and stored in a D1 report (locally: SQLite). Use synthetic data only. Loading a file disables the controlled transformation defect.",
    "upload": "Upload CSV/JSON",
    "runCurrent": "Run on loaded input",
    "actualStages": "Actual run stages",
    "resultFilter": "Test result",
    "category": "Category",
    "entity": "Entity",
    "priority": "Priority",
    "search": "Search result",
    "contractTitle": "Explicit source and target contract",
    "contractBody": "Amounts are calculated as Decimal; JSON stores them as strings with two decimal places. Dates have an explicit format, and null values are allowed only in note.",
    "driftTitle": "Schema drift and versioned mapping",
    "driftBody": "This section shows a source shape change before data is accepted into the target. A new optional field follows policy, while a missing required field or incompatible type stops the record in quarantine.",
    "driftHeaders": [
      "Scenario",
      "Status",
      "Source / mapping / target",
      "Field / rule",
      "Expected / actual",
      "Policy"
    ],
    "quarantine": "quarantine:",
    "transformTitle": "Transformation catalog",
    "rulesTitle": "Quality rule catalog",
    "ruleHeaders": [
      "Rule ID",
      "Category",
      "Condition"
    ],
    "targetRecord": "Target record",
    "targetField": "Target field",
    "noLineage": "No transformation for this record. Rejections before transformation keep their source and reason in quarantine.",
    "rejectTitle": "Quarantine and expected rejections",
    "rejectSet": "Rejection set",
    "currentRun": "Current run",
    "negative": "Expected negative cases",
    "rejectBody": "Rejected data and test result are separate. Correctly detected error in an agreed negative scenario gives the test a PASS result.",
    "runsTitle": "Stored, reproducible runs",
    "runsBody": "D1 in the public version, SQLite locally, stores the report by deterministic run ID. Reset recreates the same reference ID, not a new data version. Time uses a fixed scenario clock.",
    "runHeaders": [
      "Run / hash",
      "Clock",
      "Input / accepted / rejected",
      "Checks / failures",
      "Status",
      "Evidence"
    ],
    "runReport": "Run report",
    "regressionTitle": "RUN A — reference / RUN B — current result",
    "regressionEmpty": "Run the reference, then the controlled regression. Reset compares the restored reference with itself.",
    "reportTitle": "Quality and acceptance report",
    "reportBody": "The source total covers records that passed input validation. Candidate totals are compared before the acceptance gate. The aggregate discrepancy assigned to the root ID does not create a second FAIL scenario.",
    "json": "Download JSON",
    "csv": "Download CSV",
    "archTitle": "Adapter → parser → staging → canonical → transformations → quality → target → lineage → diff → report",
    "archBody": "The TypeScript engine separates input contract, exact cent-based amounts, dates, transformations, rejection, comparison and report. Python/Decimal and FastAPI are the test reference. D1 stores public-version reports and React displays the evidence. The system does not require cluster infrastructure.",
    "verify": "What you can verify here",
    "verifyBody": "Data contract, transformations, quality rules, error source, field-level lineage, expected/actual, difference between runs and repeatable acceptance report.",
    "criteria": "Acceptance criteria",
    "criteriaBody": "Reference: all scenarios PASS. Controlled TX-104 transformation: one root discrepancy, one changed record and one field. A rejected record does not enter the accepted target dataset. Reset: PASS again and a clean comparison.",
    "demoScope": "Demonstration scope",
    "demoBody1": "Controlled pipeline fragment: ingestion, normalization, transformations, quality rules and source-to-target trace. Adapter work for a Data Lake/ETL environment is a separate integration scope. Data and customer dimensions are synthetic.",
    "demoBody2": "Public dataset: CSV/JSON, up to 1000 records for the repeatable test scenario. One root rejection cause per record; validation stops the record at the first blocking rule. Field lineage covers records that reached transformation. Fixed clock: September 16, 2026. The backend isolates reports by browser session and does not write to source systems.",
    "cta": "Describe the scope",
    "close": "Close evidence",
    "dialog": "Quality and transformation evidence",
    "sections": "Data quality sections",
    "sourceData": "Source data",
    "docs": "OpenAPI / API documentation →"
  }
});
