import {defineCopy} from './localization-contract';
export const serviceQuestions=defineCopy('service-questions',{
 en:{title:'Before you start',groups:[
 [['Can you connect my CRM to an ERP?','First I check the available API, authentication, limits and test access. We select one flow, such as orders or invoice statuses, and agree which system owns each field. The demonstration is a representative data model, not a certified connector for a particular vendor.'],['What happens if an API request fails?','A timeout can occur after the destination has already accepted a record. The agreed design must distinguish a safe retry from a second write. Stable record identifiers, operation logs and reconciliation help detect missing records and avoid duplicates.'],['What should I prepare for an integration estimate?','Send the names of the systems, API documentation, the direction of the transfer, approximate volume and a sanitised example. Describe how quickly changes must appear in the destination. Do not send passwords or production credentials through the contact form.']],
 [['How do you validate a CSV before an ERP import?','Check required fields, dates, amounts, identifiers and duplicate records, then map source values to the target model. Keep rejected rows with their original identifiers and reasons. The Migration demonstration lets you remove a product mapping, see the failed records and retry only those records after correction.'],['How can historical revenue and ERP invoices overlap?','An export can contain records after the new system becomes authoritative. In the Revenue BI example, history is authoritative through 30 June 2026 and ERP from 1 July. July history is explicitly excluded, so it cannot be counted twice. These are synthetic example rules; your cutover is agreed separately.'],['Does a reconciliation PASS mean all source data is clean?','No. In the Revenue BI example, PASS means every monetary record is accounted for, controls balance and no blocking mapping exception remains. Duplicate or invalid source records can remain quarantined with a documented reason. Source data quality therefore still shows WARNING.']],
 [['Why is an HTTP 200 response not enough to test an integration?','It confirms a successful HTTP response, but does not prove that the right customer, amount or status reached the destination. Acceptance tests compare expected business values with actual target records and check error behaviour.'],['Which failure scenarios should an API test pack include?','Choose scenarios from the agreed contract: missing fields, invalid values, duplicate requests, timeouts and retry behaviour. Include a valid control case so that a test does not pass merely because everything was rejected.'],['What makes a test report reproducible?','Record the input or fixture version, configuration, expected result, actual result and instructions to rerun the checks. A PASS applies to that tested scope and version; a change to mapping or rules can require another run.']]]},
 pl:{title:'Przed rozpoczęciem',groups:[
 [['Czy możesz połączyć mój CRM z ERP?','Najpierw sprawdzam API, uwierzytelnianie, limity i dostęp testowy. Wybieramy jeden przepływ, np. zamówienia lub statusy faktur, i ustalamy, który system jest źródłem każdego pola. Demonstracja pokazuje reprezentatywny model danych, a nie certyfikowany konektor konkretnego producenta.'],['Co się stanie, gdy żądanie API się nie powiedzie?','Przekroczenie czasu oczekiwania może nastąpić już po przyjęciu rekordu przez cel. Projekt musi odróżniać bezpieczne ponowienie od ponownego zapisu. Stałe identyfikatory rekordów, dziennik operacji i uzgodnienie danych pomagają wykrywać braki oraz zapobiegać duplikatom.'],['Co przygotować do wyceny integracji?','Podaj systemy, dokumentację API, kierunek przesyłania, przybliżoną liczbę rekordów i próbkę bez danych poufnych. Opisz, jak szybko zmiany mają być widoczne w celu. Nie przesyłaj haseł ani produkcyjnych danych dostępowych przez formularz.']],
 [['Jak sprawdzić CSV przed importem do ERP?','Sprawdzamy wymagane pola, daty, kwoty, identyfikatory i duplikaty, a następnie mapujemy wartości na model docelowy. Odrzucone wiersze zachowują identyfikator i przyczynę odrzucenia. W demonstracji migracji możesz usunąć mapowanie produktu, zobaczyć błędne rekordy i ponowić tylko je po poprawce.'],['Jak historia przychodów może nakładać się na faktury ERP?','Eksport może zawierać dane z okresu, w którym nowy system jest już źródłem nadrzędnym. W przykładzie Revenue BI historia obowiązuje do 30 czerwca 2026, a ERP od 1 lipca. Historia lipcowa jest jawnie pomijana, aby uniknąć podwójnego naliczenia. To reguły syntetycznego przykładu; datę przełączenia dla Twojego projektu ustalamy osobno.'],['Czy PASS uzgodnienia oznacza brak wad w źródłach?','Nie. W przykładzie Revenue BI PASS oznacza, że każda kwota jest rozliczona, sumy kontrolne się zgadzają i nie ma blokującego wyjątku mapowania. Duplikaty i niepoprawne rekordy mogą nadal pozostawać w kwarantannie z podaną przyczyną. Dlatego jakość danych źródłowych nadal pokazuje WARNING.']],
 [['Dlaczego HTTP 200 nie wystarcza do sprawdzenia integracji?','Potwierdza poprawną odpowiedź HTTP, ale nie dowodzi, że właściwy klient, kwota lub status trafiły do celu. Testy odbiorowe porównują oczekiwane wartości biznesowe z rzeczywistymi rekordami i sprawdzają obsługę błędów.'],['Jakie błędy powinny obejmować testy API?','Scenariusze wynikają z uzgodnionego kontraktu: brakujące pola, błędne wartości, powtórzone żądania, przekroczenie czasu i ponowienia. Potrzebny jest też poprawny przypadek kontrolny, aby test nie przechodził tylko dlatego, że wszystko zostało odrzucone.'],['Co pozwala odtworzyć wynik raportu z testów?','Zapisujemy dane wejściowe lub wersję próbki, konfigurację, wynik oczekiwany i rzeczywisty oraz instrukcję ponownego uruchomienia. PASS dotyczy sprawdzonego zakresu i wersji; zmiana mapowania lub reguł może wymagać kolejnego przebiegu.']]]}
});
