import {PracticalLinks,SampleLink} from './PracticalResources';
import {MigrationOffer} from './MigrationGuide';
import {serviceQuestions} from './service-questions';
import {RevenueEntry} from './RevenueEntry';
import {Link} from 'react-router-dom';
import {useLocale,localizedPath} from './locale';
import {servicesCopy,serviceSlugs,serviceSearchCopy} from './services-copy';
import './services.css';
export function FirstOrders(){const locale=useLocale(),c=servicesCopy[locale];return <section className="shell section first-orders" id="first-orders"><h2>{c.first}</h2><p className="section-intro">{c.intro}</p><div className="first-order-grid">{c.cards.map((s,i)=><article key={s.title}><h3>{s.scope}</h3><dl><dt>{c.input}</dt><dd>{s.input}</dd><dt>{c.output}</dt><dd>{s.output}</dd><dt>{c.acceptance}</dt><dd>{s.acceptance}</dd></dl><Link to={localizedPath('/'+serviceSlugs[i],locale)}>{c.details} →</Link></article>)}<article><h3>{c.exception.title}</h3><dl><dt>{c.input}</dt><dd>{c.exception.input}</dd><dt>{c.output}</dt><dd>{c.exception.output}</dd><dt>{c.acceptance}</dt><dd>{c.exception.acceptance}</dd></dl><Link to={localizedPath('/contact',locale)+'?service=exceptions'}>{c.cta} →</Link></article></div><p>{c.pricing}</p></section>}
export {ServiceLinks} from './ServiceLinks';
import {ServiceLinks} from './ServiceLinks';
export default function ServicePage({index}:{index:number}){const locale=useLocale(),c=servicesCopy[locale],s=c.cards[index],q=serviceQuestions[locale],search=serviceSearchCopy[locale];return <main className="service-page"><section className="shell section"><Link to={localizedPath('/',locale)}>{locale==='pl'?'← Strona główna':'← Home'}</Link><p className="eyebrow">Ivan Matiushkin · {search.role}</p><h1>{s.title}</h1><p className="section-intro">{s.description}</p><p>{s.problem}</p><h2>{search.casesTitle}</h2><p>{search.pages[index].cases}</p><Link className="button primary" to={localizedPath('/contact',locale)+'?service='+serviceSlugs[index].split('/')[1]}>{c.cta}</Link></section>{index===1&&<MigrationOffer/>}<section className="shell section"><h2>{s.scope}</h2><div className="service-outcomes">{[[c.input,s.input],[c.output,s.output],[c.acceptance,s.acceptance]].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div><p>{s.limits}</p><SampleLink/><p>{c.pricing}</p></section><section className="shell section"><h2>{c.stepsTitle}</h2><ol>{c.steps.map(step=><li key={step}>{step}</li>)}</ol><h2>{c.examples}</h2><p>{c.demo}</p><Link className="button secondary" to={localizedPath('/'+s.proof,locale)}>{c.examples} →</Link>{index===1&&<RevenueEntry/>}<section className="service-questions"><h2>{q.title}</h2>{q.groups[index].map(([question,answer])=><article key={question}><h3>{question}</h3><p>{answer}</p></article>)}</section><PracticalLinks/><ServiceLinks/></section></main>}
