import {defineCopy} from './localization-contract';
export const serviceSlugs=['services/api-integration','services/data-migration','services/integration-testing'] as const;
export const serviceSearchCopy=defineCopy('service-search',{
 pl:{role:'Niezależny wykonawca · Polska · współpraca zdalna',casesTitle:'Z jakim zadaniem możesz się zgłosić',pages:[
 {title:'Integracje API CRM i ERP — programista do współpracy',description:'Niezależny wykonawca z Polski: integracja CRM z ERP, synchronizacja danych i diagnoza błędów API. Zobacz działający przykład i opisz swój przepływ.',cases:'Potrzebujesz przesyłać zamówienia z CRM do ERP, aktualizować statusy faktur albo sprawdzić, dlaczego istniejąca synchronizacja gubi rekordy? Możemy zacząć od jednego przepływu lub diagnozy powtarzalnego błędu. Przy naprawie najpierw potrzebny jest opis problemu i dostępna dokumentacja; możliwość zmiany kodu oraz dostęp testowy sprawdzamy przed wyceną.'},
 {title:'Migracja danych CSV do ERP — walidacja i uzgadnianie',description:'Przygotowanie CSV do ERP: mapowanie pól, wykrywanie duplikatów i porównanie źródła z celem. Niezależny wykonawca z Polski; pierwszy etap dla jednego pliku.',cases:'Zmieniasz system, import odrzuca część CSV albo sumy po przeniesieniu danych nie zgadzają się ze źródłem? Pierwszym etapem może być sprawdzenie jednego eksportu, przygotowanie mapowania lub porównanie wyniku importu. Otrzymujesz listę konkretnych rekordów i przyczyn rozbieżności, zamiast samego komunikatu „import zakończony”.'},
 {title:'Automatyczne testy API i testy integracyjne — wykonawca',description:'Zleć testy API i przepływów między systemami: kontrakty, mapowanie, duplikaty i timeouty. Powtarzalny raport PASS/FAIL. Współpraca zdalna z Polski.',cases:'Wdrażasz nowe połączenie, zmieniasz mapowanie albo potrzebujesz sprawdzić integrację po aktualizacji API? Mogę przygotować powtarzalne testy jednego przepływu na uzgodnionych danych. To także wydzielony zakres dla agencji lub integratora, który potrzebuje wsparcia przy testach odbiorowych przed przekazaniem rozwiązania.'}
 ]},
 en:{role:'Independent contractor · Poland · remote collaboration',casesTitle:'Tasks you can bring',pages:[
 {title:'API integration developer — CRM and ERP data flows',description:'Independent developer in Poland for CRM/ERP API integration, data synchronization and failed-flow diagnosis. Try a working example and discuss one bounded task.',cases:'Need to transfer CRM orders to an ERP, update invoice statuses or investigate records missing from an existing sync? We can start with one flow or the diagnosis of a repeatable failure. For a repair, start with the problem and available documentation; permission to change code and test access are checked before an estimate.'},
 {title:'CSV to ERP data migration and reconciliation services',description:'CSV validation, field mapping, duplicate checks and source-to-target reconciliation. Independent contractor in Poland. Start with one export and a defined result.',cases:'Changing systems, dealing with rejected CSV rows or investigating totals that differ after an import? A first task can be checking one export, preparing a field mapping or comparing the imported result. You receive identified records and reasons for discrepancies, rather than just an “import completed” message.'},
 {title:'API integration testing — independent contractor',description:'Automated API and integration tests: contracts, mappings, duplicates and timeouts with a repeatable PASS/FAIL report. Remote contractor based in Poland.',cases:'Releasing a new connection, changing a mapping or checking an integration after an API update? I can prepare repeatable tests for one flow using agreed data. This can also be a bounded acceptance-testing package for an agency or integrator before handing over its implementation.'}
 ]}
});
export const servicesCopy=defineCopy('services',{
 pl:{title:'Wybierz zakres do realizacji',intro:'Możemy zacząć od jednego przepływu, pliku lub pakietu testów. Przed pracą ustalamy zakres, cenę i sposób sprawdzenia wyniku.',first:'Co możesz zamówić na początek',input:'Co jest potrzebne',output:'Co otrzymujesz',acceptance:'Jak sprawdzamy wynik',cta:'Opisz zadanie',details:'Zobacz zakres usługi',examples:'Sprawdź przykład',demo:'Poniższe demonstracje korzystają z danych syntetycznych. Nie są wdrożeniami klientów.',stepsTitle:'Od pierwszego pliku do przekazania',steps:['Przesyłasz opis i próbkę danych bez informacji poufnych lub dokumentację API.','Sprawdzam dostęp i ograniczenia. Uzgadniamy zakres, wycenę oraz testy odbiorowe.','Realizuję etap, pokazuję wyniki testów i przekazuję kod z instrukcją.'],pricing:'Wycena i termin po sprawdzeniu materiałów, przed rozpoczęciem płatnej pracy. Rozliczenie przez Useme.',cards:[
 {title:'Integracje API i ERP',description:'Połącz dwa systemy: przesyłanie zamówień, aktualizacja statusów lub import dokumentów z kontrolą błędów i duplikatów.',problem:'Ręczne przenoszenie zamówień i statusów zabiera czas. Przygotuję połączenie dla wybranego obiektu danych, z mapowaniem pól i obsługą błędnych odpowiedzi.',scope:'Jeden przepływ danych między dwoma systemami',input:'Dokumentacja API, przykładowe żądania i odpowiedzi, dostęp do środowiska testowego oraz opis pól.',output:'Działający adapter, mapowanie danych, dziennik operacji i testy. Ponowienia oraz ochrona przed duplikatami zgodnie z uzgodnionym procesem.',acceptance:'Poprawny rekord trafia do celu; duplikat i błąd połączenia są obsłużone zgodnie z uzgodnionymi scenariuszami.',limits:'Możliwość połączenia zależy od API, licencji i dostępów. Zakres nie obejmuje automatycznie konfiguracji całego ERP ani certyfikowanego wdrożenia konkretnego producenta.',proof:'data-bridge'},
 {title:'Migracja CSV do ERP i uzgadnianie danych',description:'Przygotuj dane do importu i sprawdź zgodność eksportów: mapowanie pól, brakujące rekordy, duplikaty i różnice w kwotach.',problem:'Przed zmianą systemu trzeba ustalić, co zostanie przeniesione i jak sprawdzić kompletność. Przygotuję mapowanie oraz raport rekordów wymagających poprawy.',scope:'Jeden eksport i jeden format docelowy',input:'Przykładowy eksport CSV, opis formatu docelowego i reguły poprawności. Inne formaty ustalamy przed startem.',output:'Skrypt mapujący lub walidator, raport rozbieżności, podsumowanie liczby rekordów i uzgodnionych sum kontrolnych.',acceptance:'Uzgodniona próbka przechodzi powtarzalną kontrolę; odrzucone rekordy mają wskazaną przyczynę i źródło.',limits:'Zapis do systemu produkcyjnego, pełne przeniesienie historii i okno migracji wymagają osobnego uzgodnienia. Pierwszy etap może obejmować samą analizę pliku.',proof:'proof/migration'},
 {title:'Testy integracyjne i odbiorowe',description:'Sprawdź działanie API lub przepływu przed uruchomieniem: scenariusze poprawne, błędy, wyniki oczekiwane i raport z testów.',problem:'Poprawna odpowiedź HTTP nie oznacza jeszcze poprawnych danych. Przygotuję testy kontraktu i scenariuszy procesu, które można powtórzyć po zmianach.',scope:'Pakiet testów dla jednego API lub przepływu',input:'Opis API lub procesu, środowisko testowe, przykładowe dane i oczekiwane zachowanie.',output:'Uruchamialne testy, raport wyników oraz lista wykrytych niezgodności z instrukcją odtworzenia.',acceptance:'Każdy uzgodniony scenariusz ma oczekiwany rezultat, rzeczywisty wynik i jednoznaczny status PASS lub FAIL.',limits:'Zakres testów ustalamy przed pracą. Pakiet nie zastępuje audytu bezpieczeństwa, certyfikacji ani pełnych testów obciążeniowych.',proof:'api-tests'}],exception:{title:'Raport wyjątków do sprawdzenia',input:'Eksporty i lista reguł, np. brak dokumentu, niezgodna kwota lub opóźniony status.',output:'Raport lub kolejka spraw z rekordem źródłowym, przyczyną i kolejną czynnością.',acceptance:'Znane błędy z próbki są wykryte, a poprawne rekordy nie trafiają do listy wyjątków.'}},
 en:{title:'Choose the work you need',intro:'Start with one data flow, file or test pack. Before work begins, we agree the scope, price and how to check the result.',first:'What you can order first',input:'What I need',output:'What you receive',acceptance:'How we check the result',cta:'Describe your task',details:'See service details',examples:'Try an example',demo:'The demonstrations below use synthetic data. They are not client deployments.',stepsTitle:'From your first sample to delivery',steps:['Send a task description and a sample without confidential data, or API documentation.','I check access and constraints. We agree the scope, price and acceptance tests.','I implement the stage, show the test results and deliver the code with instructions.'],pricing:'Price and timing are agreed after reviewing your materials, before paid work begins. Project payments are handled through Useme.',cards:[
 {title:'API and ERP integrations',description:'Connect two systems to transfer orders, update statuses or import documents, with error handling and duplicate checks.',problem:'Moving orders and statuses by hand takes time. I can connect a selected data object between your systems, including field mapping and handling failed responses.',scope:'One data flow between two systems',input:'API documentation, sample requests and responses, test access and field definitions.',output:'A working adapter, data mapping, operation logs and tests. Retries and duplicate protection follow the agreed process.',acceptance:'A valid record reaches the destination; duplicates and connection failures are handled according to the agreed scenarios.',limits:'Feasibility depends on API access, licensing and permissions. The scope does not automatically include configuring an entire ERP or a certified vendor implementation.',proof:'data-bridge'},
 {title:'CSV to ERP migration and data reconciliation',description:'Prepare data for import and compare exports: field mapping, missing records, duplicates and amount differences.',problem:'Before changing systems, you need to know what will be transferred and how to check completeness. I prepare the mapping and report records that need correction.',scope:'One source export and one target format',input:'A sample CSV export, the target format and validation rules. Other formats can be agreed before starting.',output:'A mapping script or validator, discrepancy report, record counts and agreed control totals.',acceptance:'The agreed sample passes repeatable checks; rejected records include the reason and source.',limits:'Production writes, full historical migration and the migration window are agreed separately. The first stage can cover file analysis only.',proof:'proof/migration'},
 {title:'Integration and acceptance testing',description:'Check an API or workflow before release: successful cases, failures, expected results and a test report.',problem:'A successful HTTP response does not always mean the data is correct. I build contract and process tests that can be repeated after changes.',scope:'A test pack for one API or workflow',input:'API or process documentation, a test environment, sample data and expected behaviour.',output:'Executable tests, a results report and reproducible steps for each issue found.',acceptance:'Every agreed scenario has an expected outcome, an actual result and a clear PASS or FAIL status.',limits:'We agree the test scope before starting. The pack does not replace a security audit, certification or full load testing.',proof:'api-tests'}],exception:{title:'An exception report for review',input:'Exports and rules such as missing documents, incorrect amounts or delayed statuses.',output:'A report or review queue with source records, reasons and next actions.',acceptance:'Known defects in the sample are detected and valid records stay out of the exception list.'}}
});
