import {defineCopy,selectCopy} from './localization-contract';
import {useLocale} from './locale';
export const sharedCopy=defineCopy('shared-ui',{
  "pl": {
 "nav":[["pomoc","Usługi"],["zakres","Zakres"],["jak-pracuje","Jak zaczynamy"]],
    "sd2fe4a5869a6": "Strona główna Ivan Matiushkin",
    "saf66cac1eb7f": "Integracje, automatyzacja i systemy wewnętrzne dla firm",
    "s342e63de46f2": "Główna nawigacja",
    "sdd94b6145e4e": "← Wszystkie przykłady",
    "scda0fb0dc106": "Kontakt",
    "s313597ce2a2e": "Język",
    "s43d65ed3e1d4": "Integracje systemów · migracje danych · narzędzia wewnętrzne",
    "sbfb24cd23e8a": "Nie znaleziono strony",
    "s94a32c06b903": "Podany adres nie prowadzi do dostępnego przykładu technicznego.",
    "s08c3a528f835": "Wróć do strony głównej",
    "s10fa4d3ee56d": "O przykładach na tej stronie",
    "scab41fdb1fcf": "Przykłady korzystają z danych testowych. Możesz sprawdzić dane wejściowe, uruchomić testy i pobrać raport.",
    "sdfb831b62e96": "Wejście → Przetwarzanie → Wykrywanie błędów → Raport → Mierzalny odbiór",
    "s928ef9c5223e": "Dla osoby technicznej",
    "s0f557c587081": "Jak to jest sprawdzane",
    "s6a1b281859d8": "Reguły i kontrakty mają testy jednostkowe oraz scenariusze negatywne. Testy przeglądarkowe sprawdzają wykonanie, dowody i eksport. Wynik PASS oznacza zgodność z oczekiwaniem scenariusza — również wtedy, gdy błędne wejście zostało poprawnie odrzucone.",
    "s066c61053dac": "Wykonanie publiczne: API TypeScript w Cloudflare Worker → silnik reguł → raport w D1. Python/FastAPI pozostaje implementacją referencyjną, porównywaną w testach. Każda przeglądarka ma odrębną, losową sesję. Dane wejściowe są przesyłane do API; raport i dowody są dostępne przez 24 godziny, a czyszczenie fizyczne odbywa się co godzinę. Używaj wyłącznie danych syntetycznych, bez danych poufnych.",
    "s079c7e2134b4": "Kontrakt API / OpenAPI",
    "sfcc011945554": [
      "Wejście",
      "Jak działa kontrola",
      "Co system wykrywa",
      "Co otrzymujesz",
      "Jak odbierany jest wynik"
    ],
    "s7e45f27ac88a": "Model odbioru",
    "s44a5161624f7": "Sprawdź sam w 30 sekund",
    "s0fb3bd1cc0f7": "Do weryfikacji wystarczą trzy rzeczy: poprawny wynik, wykryta rozbieżność i ponowny PASS po naprawie.",
    "s69b4bf65a0ee": "Uruchom referencję → PASS",
    "sbc4afe704889": "Poprawne dane spełniają kryteria odbioru.",
    "s368d458bed53": "Wprowadź kontrolowaną rozbieżność → 1 FAIL",
    "s30dd48f1101e": "System wskazuje rekord, regułę i przyczynę.",
    "s780b280573d8": "Przywróć konfigurację → PASS",
    "s812682962783": "Po usunięciu przyczyny proces ponownie spełnia kryteria odbioru.",
    "s1c23b884d77f": "Pakiet dodatkowy async",
    "s71f55d0475a6": "Odbiór dostarczania webhooków",
    "s349326ec9a5c": "HMAC-SHA256, klucz idempotencji, duplikat dostarczenia, limit czasu i ponowienie. Izolowany odbiornik wykonuje scenariusze w jednym żądaniu do API. Timeout jest kontrolowaną symulacją transportu.",
    "sef7d07b6cfde": "Referencja: wszystkie testy PASS. Kontrolowana zmiana: wyłączenie deduplikacji jednego dostarczenia. Oczekiwane odrzucenie błędnego wejścia oznacza PASS testu.",
    "s502845736df2": "Pakiet dodatkowy healthcare",
    "s202733bfbd4c": "Uzupełnienie kontraktu: HL7 v2 / metadane DICOM",
    "s4e6f8fb6dc25": "FHIR pozostaje głównym modelem. Ten pakiet sprawdza wybrane pola MSH/PID komunikatu ADT^A01 oraz identyfikatory i referencje metadanych DICOM. Zakres obejmuje strukturę komunikatu i metadane; przetwarzanie obrazów oraz pełne profile zgodności wymagają osobnego kontraktu.",
    "sabae849b7239": "Referencja: wszystkie testy PASS. Kontrolowana zmiana: zmiana PatientID jednego badania na nieznany identyfikator. Oczekiwane odrzucenie błędnego wejścia oznacza PASS testu.",
    "s21f7edf80357": "Uruchom referencję dodatku",
    "s121e654cdc71": "Wprowadź regresję dodatku",
    "sf5869210b908": "Przywróć referencję dodatku",
    "s7d364b770841": "Reguła",
    "s533ec8f80643": "Oczekiwane",
    "s0b2659865556": "Rzeczywiste",
    "se966f1ec9b8c": "Test",
    "s162c1ecbb6bb": "Dowód",
    "sc797895b5350": "Pokaż dowód",
    "s374a5ff9a9d1": "Eksportuj raport dodatku JSON"
  },
  "en": {
 "nav":[["services","Services"],["scope","Scope"],["how-i-work","How we start"]],
    "sd2fe4a5869a6": "Ivan Matiushkin home",
    "saf66cac1eb7f": "Integrations, automation and internal systems for businesses",
    "s342e63de46f2": "Main navigation",
    "sdd94b6145e4e": "← All examples",
    "scda0fb0dc106": "Contact",
    "s313597ce2a2e": "Language",
    "s43d65ed3e1d4": "System integrations · data migration · internal tools",
    "sbfb24cd23e8a": "Page not found",
    "s94a32c06b903": "This address does not lead to an available technical demonstration.",
    "s08c3a528f835": "Back to home",
    "s10fa4d3ee56d": "About these examples",
    "scab41fdb1fcf": "The examples use test data. You can inspect the input, run the checks and download a report.",
    "sdfb831b62e96": "Input → Processing → Error detection → Report → Measurable acceptance",
    "s928ef9c5223e": "For a technical reviewer",
    "s0f557c587081": "How it is verified",
    "s6a1b281859d8": "Rules and contracts are covered by unit tests and negative scenarios. Browser tests verify execution, evidence and export. PASS means the result matches the scenario expectation — including cases where invalid input is correctly rejected.",
    "s066c61053dac": "Public execution: TypeScript API in a Cloudflare Worker → rules engine → D1 report. Python/FastAPI remains the reference implementation compared in tests. Each browser has a separate random session. Input data is sent to the API; reports and evidence are available for 24 hours, and physical cleanup runs hourly. Use synthetic data only, with no confidential data.",
    "s079c7e2134b4": "API contract / OpenAPI",
    "sfcc011945554": [
      "Input",
      "How the check works",
      "What the system detects",
      "What you receive",
      "How the result is accepted"
    ],
    "s7e45f27ac88a": "Acceptance model",
    "s44a5161624f7": "Verify it yourself in 30 seconds",
    "s0fb3bd1cc0f7": "Three checks are enough: a correct result, a detected discrepancy and PASS again after repair.",
    "s69b4bf65a0ee": "Run reference → PASS",
    "sbc4afe704889": "Valid data meets the acceptance criteria.",
    "s368d458bed53": "Introduce controlled discrepancy → 1 FAIL",
    "s30dd48f1101e": "The system points to the record, rule and reason.",
    "s780b280573d8": "Restore configuration → PASS",
    "s812682962783": "After the cause is removed, the process meets the criteria again.",
    "s1c23b884d77f": "Supplement pack async",
    "s71f55d0475a6": "Webhook delivery acceptance",
    "s349326ec9a5c": "HMAC-SHA256, idempotency key, duplicate delivery, timeout and retry. An isolated receiver executes scenarios in one API request. Timeout is a controlled transport simulation.",
    "sef7d07b6cfde": "Reference: all tests PASS. Controlled change: deduplication is disabled for one delivery. Expected rejection of invalid input means the test passes.",
    "s502845736df2": "Supplement pack healthcare",
    "s202733bfbd4c": "Contract supplement: HL7 v2 / DICOM metadata",
    "s4e6f8fb6dc25": "FHIR remains the main model. This pack checks selected MSH/PID fields from an ADT^A01 message plus identifiers and references in DICOM metadata. The scope covers message structure and metadata; image processing and full conformance profiles require a separate contract.",
    "sabae849b7239": "Reference: all tests PASS. Controlled change: PatientID of one study changes to an unknown identifier. Expected rejection of invalid input means the test passes.",
    "s21f7edf80357": "Run supplement reference",
    "s121e654cdc71": "Introduce supplement regression",
    "sf5869210b908": "Restore supplement reference",
    "s7d364b770841": "Rule",
    "s533ec8f80643": "Expected",
    "s0b2659865556": "Actual",
    "se966f1ec9b8c": "Test",
    "s162c1ecbb6bb": "Evidence",
    "sc797895b5350": "Show evidence",
    "s374a5ff9a9d1": "Export supplement JSON report"
  }
});
export function useSharedCopy(){return selectCopy(sharedCopy,useLocale());}
