import {defineCopy} from './localization-contract';
export const taskRoutes=[
 {id:'integration',proof:'data-bridge',secondary:'erp-sync',service:'api-integration'},
 {id:'migration',proof:'proof/migration',secondary:'data-quality',service:'data-migration'},
 {id:'reporting',proof:'proof/revenue-bi',secondary:'reconciliation',service:'data-migration'},
 {id:'testing',proof:'operations-exceptions',secondary:'workflow-access',service:'exceptions'},
 {id:'ai',proof:'proof/ai-automation',secondary:'api-tests',service:'other'},
 {id:'tools',proof:'operations-exceptions',secondary:'workflow-access',service:'exceptions'},
] as const;
export function taskIndex(value:string|null){const i=taskRoutes.findIndex(t=>t.id===value);return i<0?0:i;}
export const taskFit=defineCopy('task-fit',{
 en:{title:'What are you trying to improve?',intro:'Choose a familiar situation, or describe your problem without choosing a category.',choose:'Choose a task',first:'First paid step',input:'What I need',output:'What you receive',acceptance:'How we check it',proof:'Inspect the working example',deeper:'More technical evidence',ask:'Discuss this task',boundary:'Scope and proof limits',disclosure:'Independent working demonstrations using synthetic data. Not client deployments.',start:'How we start',steps:['Describe one process or share a written brief; no credentials needed for the first enquiry.','Agree the result, access, price, timing and acceptance checks before paid work.','Review the result with repeatable tests, open issues and written handover.'],collaboration:'Written-first collaboration',terms:'Independent contractor in Poland, working remotely. We can start by email with a written brief and an agreed paid test task. Working hours and any prepared calls are agreed separately. Settlement through Useme where compatible with the client; Useme is not my company.',items:[
 {label:'Our systems do not work together',title:'Connect one data flow or investigate failed updates',first:'Validate or implement one API operation after checking access and the interface contract.',input:'API documentation, sanitised request/response examples and test access when execution is needed.',output:'An adapter or diagnostic report, mapping rules, failed-record evidence and repeatable checks.',acceptance:'Agreed valid, duplicate and failure cases have explicit expected and observed outcomes.',demonstrated:'See what happens when an update fails or the same record arrives twice.',limits:'These examples are controlled systems. They do not establish a certified connector or production history with your ERP/CRM. Platform access, licences and write permissions must be verified.'},
 {label:'We keep moving data manually',title:'Check one export before moving data',first:'Validate one CSV export against one target specification.',input:'A sanitised export, target fields and the record identifiers and totals that must agree.',output:'Field mapping, rejected-record reasons and a reproducible acceptance report.',acceptance:'Each in-scope record is accepted or explained; the agreed source/target checks reconcile.',demonstrated:'Check the source, resolve a missing match, retry only failed records and compare the result.',limits:'A controlled target is used. A sample check does not include a full historical migration, production cutover or ERP configuration.'},
 {label:'Our reports do not match',title:'Explain why two reports disagree',first:'Define one metric and reconcile it across two exports.',input:'Sanitised source records, period, currency and the business definition of the metric.',output:'A discrepancy table, source-record trace and a documented calculation; a dashboard if separately scoped.',acceptance:'Included and excluded amounts are explained; corrections change only the dependent results.',demonstrated:'See why a total differs, which records were excluded and where each reported amount comes from.',limits:'The revenue demo uses fixed synthetic EUR data and no FX conversion. It does not establish accounting certification, Power BI experience or industry-specific expertise.'},
 {label:'We need a better internal workflow',title:'Keep exceptions and decisions in one place',first:'Build one review queue with agreed statuses and responsibilities.',input:'A written process, example records, decision rules and the people involved.',output:'A review screen with reasons, source records and clear next actions.',acceptance:'Agreed exceptions reach the queue and decisions follow the defined rules.',demonstrated:'Inspect missing documents, delays and mismatches in a controlled queue, with evidence and role-based workflow checks.',limits:'Synthetic examples do not connect to your live systems. Notifications, permissions and production writes require a separately agreed implementation.'},
 {label:'We need to process written requests',title:'Turn a request into validated data with human review',first:'Evaluate one extraction workflow against an agreed sample set before adding downstream writes.',input:'Synthetic or authorised examples, required fields, reference documents and review rules.',output:'Structured extraction, retrieval evidence, validation findings and per-case evaluation results.',acceptance:'Schema and citation checks are visible; uncertain results are reviewed and actions require approval.',demonstrated:'Turn a synthetic written request into structured requirements, inspect supporting sources and review the suggested action.',limits:'Retrieval is lexical, not vector search. Actions are simulated. This is not proof of autonomous production agents, paid AI delivery or n8n/Make/Zapier client experience.'},
 {label:'We need a small custom tool',title:'Build one review screen or operational queue',first:'Implement one form, review queue or API-backed React/TypeScript screen.',input:'A written workflow, fields, roles, example records and an existing API contract if applicable.',output:'A responsive interface, validation and error states, tests and setup instructions.',acceptance:'Agreed user actions, permissions and failure states can be demonstrated on the sample.',demonstrated:'Try a review screen that brings problem records and the next decisions together.',limits:'This portfolio runs React/TypeScript with a native Cloudflare Worker. It does not establish Next.js/WordPress delivery history or clinical-system certification.'}
 ]},
 pl:{title:'Co chcesz usprawnić?',intro:'Wybierz znajomą sytuację lub opisz problem bez wybierania kategorii.',choose:'Wybierz zadanie',first:'Pierwszy płatny etap',input:'Czego potrzebuję',output:'Co otrzymasz',acceptance:'Jak sprawdzimy wynik',proof:'Sprawdź działający przykład',deeper:'Dodatkowe dowody techniczne',ask:'Omów to zadanie',boundary:'Zakres i ograniczenia dowodów',disclosure:'Niezależne działające demonstracje na danych syntetycznych. To nie są wdrożenia klientów.',start:'Jak zaczynamy',steps:['Opisz jeden proces lub prześlij pisemne wymagania; pierwsze zapytanie nie wymaga haseł ani dostępów.','Przed płatną pracą uzgadniamy wynik, dostępy, cenę, termin i kryteria odbioru.','Sprawdzamy wynik na powtarzalnych testach, zapisujemy otwarte kwestie i przekazujemy dokumentację.'],collaboration:'Współpraca oparta na pisemnych ustaleniach',terms:'Niezależny wykonawca w Polsce, współpraca zdalna. Możemy zacząć e-mailem od pisemnych wymagań i uzgodnionego płatnego zadania próbnego. Godziny pracy i ewentualne przygotowane rozmowy ustalamy osobno. Rozliczenie przez Useme, jeśli odpowiada klientowi; Useme nie jest moją firmą.',items:[
 {label:'Nasze systemy nie współpracują',title:'Połącz jeden przepływ danych lub zbadaj błędne aktualizacje',first:'Sprawdzenie lub implementacja jednej operacji API po weryfikacji dostępu i kontraktu interfejsu.',input:'Dokumentacja API, przykłady żądań i odpowiedzi bez danych poufnych oraz dostęp testowy, jeśli potrzebne jest wykonanie.',output:'Adapter lub raport diagnostyczny, reguły mapowania, dowody błędnych rekordów i powtarzalne kontrole.',acceptance:'Uzgodnione poprawne dane, duplikaty i błędy mają jawne wyniki oczekiwane oraz zaobserwowane.',demonstrated:'Sprawdź, co dzieje się po nieudanej aktualizacji lub ponownym otrzymaniu tego samego rekordu.',limits:'Przykłady używają kontrolowanych systemów. Nie potwierdzają certyfikowanego konektora ani historii wdrożeń Twojego ERP/CRM. Dostępy, licencje i uprawnienia do zapisu wymagają sprawdzenia.'},
 {label:'Ręcznie przenosimy dane',title:'Sprawdź jeden eksport przed przeniesieniem danych',first:'Walidacja jednego eksportu CSV według jednej specyfikacji docelowej.',input:'Eksport bez danych poufnych, pola docelowe oraz identyfikatory i sumy wymagające zgodności.',output:'Mapowanie pól, przyczyny odrzuceń i powtarzalny raport odbioru.',acceptance:'Każdy rekord w zakresie jest zaakceptowany albo wyjaśniony; uzgodnione kontrole źródła i celu są zgodne.',demonstrated:'Sprawdź źródło, popraw brakujące dopasowanie, ponów tylko błędne rekordy i porównaj wynik.',limits:'Cel jest kontrolowany. Sprawdzenie próbki nie obejmuje całej historii, przełączenia produkcyjnego ani konfiguracji ERP.'},
 {label:'Nasze raporty się nie zgadzają',title:'Wyjaśnij różnice między dwoma raportami',first:'Definicja jednej metryki i uzgodnienie jej między dwoma eksportami.',input:'Rekordy źródłowe bez danych poufnych, okres, waluta i biznesowa definicja metryki.',output:'Tabela różnic, ślad do rekordów źródłowych i opis obliczeń; panel po osobnym uzgodnieniu zakresu.',acceptance:'Kwoty uwzględnione i pominięte są wyjaśnione; poprawki zmieniają tylko zależne wyniki.',demonstrated:'Zobacz, dlaczego sumy się różnią, które rekordy pominięto i skąd pochodzi każda raportowana kwota.',limits:'Demonstracja przychodów używa stałych danych syntetycznych w EUR, bez przewalutowania. Nie potwierdza certyfikacji księgowej, doświadczenia Power BI ani wiedzy branżowej.'},
 {label:'Potrzebujemy lepszego obiegu pracy',title:'Zbierz wyjątki i decyzje w jednym miejscu',first:'Jedna kolejka przeglądu z uzgodnionymi statusami i odpowiedzialnością.',input:'Pisemny proces, przykładowe rekordy, reguły decyzji i osoby zaangażowane.',output:'Ekran przeglądu z przyczynami, rekordami źródłowymi i kolejnymi działaniami.',acceptance:'Uzgodnione wyjątki trafiają do kolejki, a decyzje przebiegają według reguł.',demonstrated:'Sprawdź braki dokumentów, opóźnienia i rozbieżności w kontrolowanej kolejce z dowodami oraz kontrolami procesu według ról.',limits:'Syntetyczne przykłady nie łączą się z Twoimi systemami. Powiadomienia, uprawnienia i zapisy produkcyjne wymagają osobno uzgodnionej implementacji.'},
 {label:'Chcemy przetwarzać zapytania tekstowe',title:'Zamień zapytanie w zweryfikowane dane z kontrolą człowieka',first:'Ocena jednego procesu ekstrakcji na uzgodnionej próbce przed dodaniem zapisów do kolejnych systemów.',input:'Syntetyczne lub autoryzowane przykłady, wymagane pola, dokumenty referencyjne i zasady przeglądu.',output:'Dane strukturalne, dowody wyszukiwania, wyniki walidacji i ocena poszczególnych przypadków.',acceptance:'Kontrole schematu i cytowań są widoczne; niepewne wyniki trafiają do przeglądu, a działania wymagają akceptacji.',demonstrated:'Zamień syntetyczne zapytanie tekstowe w uporządkowane wymagania, sprawdź źródła i oceń proponowane działanie.',limits:'Wyszukiwanie jest leksykalne, nie wektorowe. Akcje są symulowane. To nie dowód autonomicznych agentów produkcyjnych, płatnych wdrożeń AI ani doświadczenia klientowskiego n8n/Make/Zapier.'},
 {label:'Potrzebujemy małego narzędzia',title:'Zbuduj jeden ekran przeglądu lub kolejkę operacyjną',first:'Jeden formularz, kolejka przeglądu albo ekran React/TypeScript połączony z API.',input:'Pisemny proces, pola, role, przykładowe rekordy i kontrakt istniejącego API, jeśli dotyczy.',output:'Responsywny interfejs, walidacja i stany błędów, testy oraz instrukcja uruchomienia.',acceptance:'Uzgodnione działania użytkownika, uprawnienia i błędy można pokazać na próbce.',demonstrated:'Wypróbuj ekran przeglądu, który zbiera problematyczne rekordy i kolejne decyzje.',limits:'Portfolio działa w React/TypeScript z natywnym Cloudflare Workerem. Nie potwierdza historii wdrożeń Next.js/WordPress ani certyfikacji systemu medycznego.'}
 ]}
});

