import {defineCopy} from './localization-contract';
export const transitUiCopy=defineCopy('transit-ui',{
  "pl": {"all":"Wszystkie",
    "back": "← Wszystkie przykłady",
    "demo": "Demonstracja techniczna",
    "trust": "Dane syntetyczne · niezależna implementacja · powtarzalne scenariusze testowe",
    "buyer": "Wynik dla odbiorcy:",
    "first": "Pierwszy zakres:",
    "reportLine": "raport JSON/CSV z rozbieżnościami, dowodami i wynikiem PASS/FAIL względem uzgodnionych reguł.",
    "boundary": "próbka / eksport / środowisko testowe. Odpowiedzialność obejmuje uzgodnione reguły i raport odbiorczy.",
    "flow": [
      "Wejście",
      "Jak działa kontrola",
      "Co system wykrywa",
      "Co otrzymujesz",
      "Jak odbierany jest wynik"
    ],
    "controlled": "Kontrolowana zmiana: znacznik czasu feedu GTFS-RT zostaje cofnięty o 4812 sekund. Pozostałe dane pozostają referencyjne.",
    "runRef": "Uruchom referencję",
    "introduce": "Wprowadź kontrolowaną rozbieżność",
    "restore": "Przywróć konfigurację",
    "scope": "Weryfikowalny zakres",
    "pack": "Pakiet odbiorczy",
    "separate": "Walidacja danych i test poprawnego wykrywania błędów to dwa osobne wyniki.",
    "validate": "Waliduj wejście",
    "runScenarios": "Uruchom scenariusze",
    "reset": "Resetuj",
    "processing": "Przetwarzanie…",
    "tabs": {
      "Wejście": "Wejście",
      "Wyniki": "Wyniki",
      "Scenariusze": "Scenariusze",
      "Model i mapowanie": "Model i mapowanie",
      "Raport": "Raport",
      "Architektura": "Architektura"
    },
    "inputHelp": "Edytowalny zestaw danych JSON. Dane są przesyłane do API wykonawczego, a raport jest przechowywany w D1 w obrębie sesji (lokalnie: SQLite). Używaj wyłącznie danych syntetycznych.",
    "inputJson": "Wejście JSON",
    "inputValidation": "Walidacja wejścia",
    "valid": "Poprawne",
    "result": "Wynik",
    "searchEvidence": "Szukaj dowodu",
    "searchPlaceholder": "Szukaj reguły, ID, wartości",
    "ruleSource": "Reguła / źródło",
    "priority": "Priorytet",
    "expected": "Oczekiwane",
    "actual": "Rzeczywiste",
    "evidence": "Dowód",
    "details": "Szczegóły",
    "noFilter": "Brak wyników dla tego filtra. Poprawne wejście nie generuje kolejki rozbieżności.",
    "emptyHead": "Uruchom walidację lub scenariusze",
    "emptyBody": "Zestaw danych jest dostępny w zakładce Wejście. Raport powstaje na podstawie faktycznie wykonanych reguł.",
    "scenarioIntro": "PASS oznacza, że scenariusz wykrył oczekiwany wynik. Celowo błędne dane nadal mają wynik walidacji FAIL.",
    "noScenarios": "Brak wyników scenariuszy. Uruchom scenariusze, aby sprawdzić odbiór przypadków negatywnych.",
    "scenario": "Scenariusz",
    "detected": "Wykryte reguły",
    "acceptance": "Odbiór testu",
    "reproduction": "Reprodukcja",
    "openRun": "Otwórz przebieg",
    "firstRun": "Najpierw wykonaj przebieg.",
    "downloadJson": "Pobierz JSON",
    "downloadCsv": "Pobierz CSV",
    "archHead": "Wejście → parser / model → reguły → D1 / SQLite → raport",
    "archBody": "React → API TypeScript w Workerze → deterministyczny silnik domenowy. Python/FastAPI pozostaje referencją porównawczą testów. Raporty mają hash wejścia i są odczytywane po ID. Kontrolowany zestaw danych pozwala powtórzyć ocenę w izolowanym środowisku.",
    "params": "Parametry publicznego scenariusza",
    "verify": "Co możesz tutaj zweryfikować",
    "verifyBody": "Sposób walidacji danych, obsługę błędów, raport rozbieżności, scenariusze PASS/FAIL i kryteria odbioru.",
    "problem": "Problem → wejście → rezultat → odbiór",
    "describe": "Opisz zakres",
    "closeEvidence": "Zamknij dowód",
    "source": "Źródło:",
    "dialog": "Dowód walidacji",
    "sections": "Sekcje przykładu",
    "modelTitle": "Model po przetwarzaniu i dowody wykonania",
    "clock": "Zegar oceny:",
    "docs": "OpenAPI / dokumentacja kontraktu →",
    "reproduce": "Powtórz żądanie POST /lab-api/transit-validation/validate z tym samym wejściem JSON i zegarem oceny 2026-09-16 12:00 UTC."
  },
  "en": {"all":"All",
    "back": "← All examples",
    "demo": "Technical demonstration",
    "trust": "Synthetic data · independent implementation · repeatable test scenarios",
    "buyer": "Buyer outcome:",
    "first": "First scope:",
    "reportLine": "JSON/CSV report with discrepancies, evidence and PASS/FAIL result against agreed rules.",
    "boundary": "sample / export / test environment. Responsibility covers the agreed rules and acceptance report.",
    "flow": [
      "Input",
      "How the check works",
      "What the system detects",
      "What you receive",
      "How the result is accepted"
    ],
    "controlled": "Controlled change: the GTFS-RT feed timestamp is moved back by 4812 seconds. Other data remains reference data.",
    "runRef": "Run reference",
    "introduce": "Introduce controlled discrepancy",
    "restore": "Restore configuration",
    "scope": "Verifiable scope",
    "pack": "Acceptance package",
    "separate": "Data validation and the test for correct error detection are two separate results.",
    "validate": "Validate input",
    "runScenarios": "Run scenarios",
    "reset": "Reset",
    "processing": "Processing…",
    "tabs": {
      "Wejście": "Input",
      "Wyniki": "Results",
      "Scenariusze": "Scenario",
      "Model i mapowanie": "Model and mapping",
      "Raport": "Report",
      "Architektura": "Architecture"
    },
    "inputHelp": "Editable JSON dataset. Data is sent to the execution API, and the report is stored in D1 within the session (locally: SQLite). Use synthetic data only.",
    "inputJson": "Input JSON",
    "inputValidation": "Input validation",
    "valid": "Valid",
    "result": "Result",
    "searchEvidence": "Search evidence",
    "searchPlaceholder": "Search rule, ID, values",
    "ruleSource": "Rule / source",
    "priority": "Priority",
    "expected": "Expected",
    "actual": "Actual",
    "evidence": "Evidence",
    "details": "Details",
    "noFilter": "No results for this filter. Valid input does not create a discrepancy queue.",
    "emptyHead": "Run validation or scenarios",
    "emptyBody": "The dataset is available in the Input tab. The report is created from the rules actually executed.",
    "scenarioIntro": "PASS means the scenario detected the expected result. Intentionally invalid data still has a FAIL validation result.",
    "noScenarios": "No scenario results yet. Run scenarios to check acceptance of negative cases.",
    "scenario": "Scenario",
    "detected": "Detected rules",
    "acceptance": "Test acceptance",
    "reproduction": "Reproduction",
    "openRun": "Open run",
    "firstRun": "Run a scenario first.",
    "downloadJson": "Download JSON",
    "downloadCsv": "Download CSV",
    "archHead": "Input → parser / model → rules → D1 / SQLite → report",
    "archBody": "React → TypeScript API in a Worker → deterministic domain engine. Python/FastAPI remains the comparative reference for tests. Reports include the input hash and are read by ID. A controlled dataset makes the assessment repeatable in an isolated environment.",
    "params": "Public scenario parameters",
    "verify": "What you can verify here",
    "verifyBody": "Data validation method, error handling, discrepancy report, PASS/FAIL scenarios and acceptance criteria.",
    "problem": "Problem → input → result → acceptance",
    "describe": "Describe the scope",
    "closeEvidence": "Close evidence",
    "source": "Source:",
    "dialog": "Validation evidence",
    "sections": "Example sections",
    "modelTitle": "Processed model and execution evidence",
    "clock": "Evaluation clock:",
    "docs": "OpenAPI / contract documentation →",
    "reproduce": "Repeat POST /lab-api/transit-validation/validate with the same JSON input and evaluation clock 2026-09-16 12:00 UTC."
  }
});
